// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterOrganizationReq struct {
	// The name of the organization. This value has to be unique.
	OrgName string `protobuf:"bytes,1,opt,name=orgName,proto3" json:"orgName,omitempty"`
	// The email of the organization.
	OrgEmail string `protobuf:"bytes,2,opt,name=orgEmail,proto3" json:"orgEmail,omitempty"`
	// The address of the organization. This is optional.
	OrgAddr string `protobuf:"bytes,3,opt,name=orgAddr,proto3" json:"orgAddr,omitempty"`
	// The administrator username. If the administrator does not exist,
	// it will be created.
	UserName string `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	// The administrator password.
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// The administrator email. This serves as the unique ID of
	// the administrator user.
	AdminEmail string `protobuf:"bytes,6,opt,name=adminEmail,proto3" json:"adminEmail,omitempty"`
	// The list of sharable organization IDs. The users in this
	// organization can only share documents to other users in
	// the organizations in the sharableOrgs list.
	SharableOrgs []string `protobuf:"bytes,7,rep,name=sharableOrgs,proto3" json:"sharableOrgs,omitempty"`
	// Enables the ability to "reshare" a document that was shared
	// to him/her to another user.
	MultiLevelShare bool `protobuf:"varint,8,opt,name=multiLevelShare,proto3" json:"multiLevelShare,omitempty"`
	// How was the organization registered (e.g. from "AWS Marketplace")
	Source string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	// Any data related to registration from the source (in JSON)
	SourceData string `protobuf:"bytes,10,opt,name=sourceData,proto3" json:"sourceData,omitempty"`
	// Stripe paymentID for syncronous account setup
	PmID                 string   `protobuf:"bytes,11,opt,name=pmID,proto3" json:"pmID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterOrganizationReq) Reset()         { *m = RegisterOrganizationReq{} }
func (m *RegisterOrganizationReq) String() string { return proto.CompactTextString(m) }
func (*RegisterOrganizationReq) ProtoMessage()    {}
func (*RegisterOrganizationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *RegisterOrganizationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterOrganizationReq.Unmarshal(m, b)
}
func (m *RegisterOrganizationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterOrganizationReq.Marshal(b, m, deterministic)
}
func (m *RegisterOrganizationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterOrganizationReq.Merge(m, src)
}
func (m *RegisterOrganizationReq) XXX_Size() int {
	return xxx_messageInfo_RegisterOrganizationReq.Size(m)
}
func (m *RegisterOrganizationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterOrganizationReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterOrganizationReq proto.InternalMessageInfo

func (m *RegisterOrganizationReq) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *RegisterOrganizationReq) GetOrgEmail() string {
	if m != nil {
		return m.OrgEmail
	}
	return ""
}

func (m *RegisterOrganizationReq) GetOrgAddr() string {
	if m != nil {
		return m.OrgAddr
	}
	return ""
}

func (m *RegisterOrganizationReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterOrganizationReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterOrganizationReq) GetAdminEmail() string {
	if m != nil {
		return m.AdminEmail
	}
	return ""
}

func (m *RegisterOrganizationReq) GetSharableOrgs() []string {
	if m != nil {
		return m.SharableOrgs
	}
	return nil
}

func (m *RegisterOrganizationReq) GetMultiLevelShare() bool {
	if m != nil {
		return m.MultiLevelShare
	}
	return false
}

func (m *RegisterOrganizationReq) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *RegisterOrganizationReq) GetSourceData() string {
	if m != nil {
		return m.SourceData
	}
	return ""
}

func (m *RegisterOrganizationReq) GetPmID() string {
	if m != nil {
		return m.PmID
	}
	return ""
}

type RegisterOrganizationResp struct {
	// The ID of the created organization. This is the unique ID to
	// use on future operation with the organization.
	OrgID string `protobuf:"bytes,1,opt,name=orgID,proto3" json:"orgID,omitempty"`
	// The newly created unique administrator user ID.
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	// Token used for Stripe integration
	ClientSecret         string   `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterOrganizationResp) Reset()         { *m = RegisterOrganizationResp{} }
func (m *RegisterOrganizationResp) String() string { return proto.CompactTextString(m) }
func (*RegisterOrganizationResp) ProtoMessage()    {}
func (*RegisterOrganizationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *RegisterOrganizationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterOrganizationResp.Unmarshal(m, b)
}
func (m *RegisterOrganizationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterOrganizationResp.Marshal(b, m, deterministic)
}
func (m *RegisterOrganizationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterOrganizationResp.Merge(m, src)
}
func (m *RegisterOrganizationResp) XXX_Size() int {
	return xxx_messageInfo_RegisterOrganizationResp.Size(m)
}
func (m *RegisterOrganizationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterOrganizationResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterOrganizationResp proto.InternalMessageInfo

func (m *RegisterOrganizationResp) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *RegisterOrganizationResp) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RegisterOrganizationResp) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type RegisterUserReq struct {
	// The new username. If the user does not exist, it will be created.
	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	// The user password.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// The user email. This serves as the unique ID of the user.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Whether this new user is an administrator of the organization.
	Admin                bool     `protobuf:"varint,4,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserReq) Reset()         { *m = RegisterUserReq{} }
func (m *RegisterUserReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUserReq) ProtoMessage()    {}
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *RegisterUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserReq.Unmarshal(m, b)
}
func (m *RegisterUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserReq.Marshal(b, m, deterministic)
}
func (m *RegisterUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserReq.Merge(m, src)
}
func (m *RegisterUserReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUserReq.Size(m)
}
func (m *RegisterUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserReq proto.InternalMessageInfo

func (m *RegisterUserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserReq) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type RegisterUserResp struct {
	// The newly added unique user ID.
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResp) Reset()         { *m = RegisterUserResp{} }
func (m *RegisterUserResp) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResp) ProtoMessage()    {}
func (*RegisterUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *RegisterUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResp.Unmarshal(m, b)
}
func (m *RegisterUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResp.Marshal(b, m, deterministic)
}
func (m *RegisterUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResp.Merge(m, src)
}
func (m *RegisterUserResp) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResp.Size(m)
}
func (m *RegisterUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResp proto.InternalMessageInfo

func (m *RegisterUserResp) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RemoveUserReq struct {
	// The ID of the user to remove.
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserReq) Reset()         { *m = RemoveUserReq{} }
func (m *RemoveUserReq) String() string { return proto.CompactTextString(m) }
func (*RemoveUserReq) ProtoMessage()    {}
func (*RemoveUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *RemoveUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserReq.Unmarshal(m, b)
}
func (m *RemoveUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserReq.Marshal(b, m, deterministic)
}
func (m *RemoveUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserReq.Merge(m, src)
}
func (m *RemoveUserReq) XXX_Size() int {
	return xxx_messageInfo_RemoveUserReq.Size(m)
}
func (m *RemoveUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserReq proto.InternalMessageInfo

func (m *RemoveUserReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RemoveUserResp struct {
	// The count of the number of users removed
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserResp) Reset()         { *m = RemoveUserResp{} }
func (m *RemoveUserResp) String() string { return proto.CompactTextString(m) }
func (*RemoveUserResp) ProtoMessage()    {}
func (*RemoveUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{5}
}

func (m *RemoveUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserResp.Unmarshal(m, b)
}
func (m *RemoveUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserResp.Marshal(b, m, deterministic)
}
func (m *RemoveUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserResp.Merge(m, src)
}
func (m *RemoveUserResp) XXX_Size() int {
	return xxx_messageInfo_RemoveUserResp.Size(m)
}
func (m *RemoveUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserResp proto.InternalMessageInfo

func (m *RemoveUserResp) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PromoteUserReq struct {
	// The ID of the user to promote.
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromoteUserReq) Reset()         { *m = PromoteUserReq{} }
func (m *PromoteUserReq) String() string { return proto.CompactTextString(m) }
func (*PromoteUserReq) ProtoMessage()    {}
func (*PromoteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{6}
}

func (m *PromoteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromoteUserReq.Unmarshal(m, b)
}
func (m *PromoteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromoteUserReq.Marshal(b, m, deterministic)
}
func (m *PromoteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromoteUserReq.Merge(m, src)
}
func (m *PromoteUserReq) XXX_Size() int {
	return xxx_messageInfo_PromoteUserReq.Size(m)
}
func (m *PromoteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PromoteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_PromoteUserReq proto.InternalMessageInfo

func (m *PromoteUserReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type PromoteUserResp struct {
	// Whether the promotion was successful.
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromoteUserResp) Reset()         { *m = PromoteUserResp{} }
func (m *PromoteUserResp) String() string { return proto.CompactTextString(m) }
func (*PromoteUserResp) ProtoMessage()    {}
func (*PromoteUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{7}
}

func (m *PromoteUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromoteUserResp.Unmarshal(m, b)
}
func (m *PromoteUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromoteUserResp.Marshal(b, m, deterministic)
}
func (m *PromoteUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromoteUserResp.Merge(m, src)
}
func (m *PromoteUserResp) XXX_Size() int {
	return xxx_messageInfo_PromoteUserResp.Size(m)
}
func (m *PromoteUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PromoteUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_PromoteUserResp proto.InternalMessageInfo

func (m *PromoteUserResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DemoteUserReq struct {
	// The ID of the user to demote.
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoteUserReq) Reset()         { *m = DemoteUserReq{} }
func (m *DemoteUserReq) String() string { return proto.CompactTextString(m) }
func (*DemoteUserReq) ProtoMessage()    {}
func (*DemoteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{8}
}

func (m *DemoteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoteUserReq.Unmarshal(m, b)
}
func (m *DemoteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoteUserReq.Marshal(b, m, deterministic)
}
func (m *DemoteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoteUserReq.Merge(m, src)
}
func (m *DemoteUserReq) XXX_Size() int {
	return xxx_messageInfo_DemoteUserReq.Size(m)
}
func (m *DemoteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DemoteUserReq proto.InternalMessageInfo

func (m *DemoteUserReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DemoteUserResp struct {
	// Whether the demotion was successful.
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoteUserResp) Reset()         { *m = DemoteUserResp{} }
func (m *DemoteUserResp) String() string { return proto.CompactTextString(m) }
func (*DemoteUserResp) ProtoMessage()    {}
func (*DemoteUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{9}
}

func (m *DemoteUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoteUserResp.Unmarshal(m, b)
}
func (m *DemoteUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoteUserResp.Marshal(b, m, deterministic)
}
func (m *DemoteUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoteUserResp.Merge(m, src)
}
func (m *DemoteUserResp) XXX_Size() int {
	return xxx_messageInfo_DemoteUserResp.Size(m)
}
func (m *DemoteUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoteUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_DemoteUserResp proto.InternalMessageInfo

func (m *DemoteUserResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LoginReq struct {
	// The ID of the user to login as.
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// The password of the user.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// The ID of the organization.
	OrgID                string   `protobuf:"bytes,3,opt,name=orgID,proto3" json:"orgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{10}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

type LoginResp struct {
	// The JWT token to be used for all APIs that require authentication.
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	KdfMeta              string   `protobuf:"bytes,2,opt,name=kdfMeta,proto3" json:"kdfMeta,omitempty"`
	KeyID                string   `protobuf:"bytes,3,opt,name=keyID,proto3" json:"keyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{11}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetKdfMeta() string {
	if m != nil {
		return m.KdfMeta
	}
	return ""
}

func (m *LoginResp) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

type LogoutReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{12}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

type LogoutResp struct {
	// The logout status.
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResp) Reset()         { *m = LogoutResp{} }
func (m *LogoutResp) String() string { return proto.CompactTextString(m) }
func (*LogoutResp) ProtoMessage()    {}
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{13}
}

func (m *LogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResp.Unmarshal(m, b)
}
func (m *LogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResp.Marshal(b, m, deterministic)
}
func (m *LogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResp.Merge(m, src)
}
func (m *LogoutResp) XXX_Size() int {
	return xxx_messageInfo_LogoutResp.Size(m)
}
func (m *LogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResp proto.InternalMessageInfo

func (m *LogoutResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListUsersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersReq) Reset()         { *m = ListUsersReq{} }
func (m *ListUsersReq) String() string { return proto.CompactTextString(m) }
func (*ListUsersReq) ProtoMessage()    {}
func (*ListUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{14}
}

func (m *ListUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersReq.Unmarshal(m, b)
}
func (m *ListUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersReq.Marshal(b, m, deterministic)
}
func (m *ListUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersReq.Merge(m, src)
}
func (m *ListUsersReq) XXX_Size() int {
	return xxx_messageInfo_ListUsersReq.Size(m)
}
func (m *ListUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersReq proto.InternalMessageInfo

type ListUsersResp struct {
	// The list of users in the organization.
	OrgUsers             []*ListUsersResp_OrgUser `protobuf:"bytes,1,rep,name=orgUsers,proto3" json:"orgUsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListUsersResp) Reset()         { *m = ListUsersResp{} }
func (m *ListUsersResp) String() string { return proto.CompactTextString(m) }
func (*ListUsersResp) ProtoMessage()    {}
func (*ListUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{15}
}

func (m *ListUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResp.Unmarshal(m, b)
}
func (m *ListUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResp.Marshal(b, m, deterministic)
}
func (m *ListUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResp.Merge(m, src)
}
func (m *ListUsersResp) XXX_Size() int {
	return xxx_messageInfo_ListUsersResp.Size(m)
}
func (m *ListUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResp proto.InternalMessageInfo

func (m *ListUsersResp) GetOrgUsers() []*ListUsersResp_OrgUser {
	if m != nil {
		return m.OrgUsers
	}
	return nil
}

type ListUsersResp_OrgUser struct {
	// The name of the user.
	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	// The ID of the user.
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	// Whether the user is an administrator.
	IsAdmin              bool     `protobuf:"varint,3,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResp_OrgUser) Reset()         { *m = ListUsersResp_OrgUser{} }
func (m *ListUsersResp_OrgUser) String() string { return proto.CompactTextString(m) }
func (*ListUsersResp_OrgUser) ProtoMessage()    {}
func (*ListUsersResp_OrgUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{15, 0}
}

func (m *ListUsersResp_OrgUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResp_OrgUser.Unmarshal(m, b)
}
func (m *ListUsersResp_OrgUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResp_OrgUser.Marshal(b, m, deterministic)
}
func (m *ListUsersResp_OrgUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResp_OrgUser.Merge(m, src)
}
func (m *ListUsersResp_OrgUser) XXX_Size() int {
	return xxx_messageInfo_ListUsersResp_OrgUser.Size(m)
}
func (m *ListUsersResp_OrgUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResp_OrgUser.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResp_OrgUser proto.InternalMessageInfo

func (m *ListUsersResp_OrgUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ListUsersResp_OrgUser) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ListUsersResp_OrgUser) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type RemoveOrganizationReq struct {
	// Whether to force removal of organization or not.
	Force                bool     `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrganizationReq) Reset()         { *m = RemoveOrganizationReq{} }
func (m *RemoveOrganizationReq) String() string { return proto.CompactTextString(m) }
func (*RemoveOrganizationReq) ProtoMessage()    {}
func (*RemoveOrganizationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{16}
}

func (m *RemoveOrganizationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrganizationReq.Unmarshal(m, b)
}
func (m *RemoveOrganizationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrganizationReq.Marshal(b, m, deterministic)
}
func (m *RemoveOrganizationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrganizationReq.Merge(m, src)
}
func (m *RemoveOrganizationReq) XXX_Size() int {
	return xxx_messageInfo_RemoveOrganizationReq.Size(m)
}
func (m *RemoveOrganizationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrganizationReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrganizationReq proto.InternalMessageInfo

func (m *RemoveOrganizationReq) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type RemoveOrganizationResp struct {
	// Whether the removal was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// True in case the removal will happen later after org has been charged one last time
	Postponed            bool     `protobuf:"varint,2,opt,name=postponed,proto3" json:"postponed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrganizationResp) Reset()         { *m = RemoveOrganizationResp{} }
func (m *RemoveOrganizationResp) String() string { return proto.CompactTextString(m) }
func (*RemoveOrganizationResp) ProtoMessage()    {}
func (*RemoveOrganizationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{17}
}

func (m *RemoveOrganizationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrganizationResp.Unmarshal(m, b)
}
func (m *RemoveOrganizationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrganizationResp.Marshal(b, m, deterministic)
}
func (m *RemoveOrganizationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrganizationResp.Merge(m, src)
}
func (m *RemoveOrganizationResp) XXX_Size() int {
	return xxx_messageInfo_RemoveOrganizationResp.Size(m)
}
func (m *RemoveOrganizationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrganizationResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrganizationResp proto.InternalMessageInfo

func (m *RemoveOrganizationResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RemoveOrganizationResp) GetPostponed() bool {
	if m != nil {
		return m.Postponed
	}
	return false
}

type AddSharableOrgReq struct {
	// The ID of the new sharable org.
	NewOrgID             string   `protobuf:"bytes,1,opt,name=newOrgID,proto3" json:"newOrgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSharableOrgReq) Reset()         { *m = AddSharableOrgReq{} }
func (m *AddSharableOrgReq) String() string { return proto.CompactTextString(m) }
func (*AddSharableOrgReq) ProtoMessage()    {}
func (*AddSharableOrgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{18}
}

func (m *AddSharableOrgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSharableOrgReq.Unmarshal(m, b)
}
func (m *AddSharableOrgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSharableOrgReq.Marshal(b, m, deterministic)
}
func (m *AddSharableOrgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSharableOrgReq.Merge(m, src)
}
func (m *AddSharableOrgReq) XXX_Size() int {
	return xxx_messageInfo_AddSharableOrgReq.Size(m)
}
func (m *AddSharableOrgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSharableOrgReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddSharableOrgReq proto.InternalMessageInfo

func (m *AddSharableOrgReq) GetNewOrgID() string {
	if m != nil {
		return m.NewOrgID
	}
	return ""
}

type AddSharableOrgResp struct {
	// Whether the add was successful
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSharableOrgResp) Reset()         { *m = AddSharableOrgResp{} }
func (m *AddSharableOrgResp) String() string { return proto.CompactTextString(m) }
func (*AddSharableOrgResp) ProtoMessage()    {}
func (*AddSharableOrgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{19}
}

func (m *AddSharableOrgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSharableOrgResp.Unmarshal(m, b)
}
func (m *AddSharableOrgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSharableOrgResp.Marshal(b, m, deterministic)
}
func (m *AddSharableOrgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSharableOrgResp.Merge(m, src)
}
func (m *AddSharableOrgResp) XXX_Size() int {
	return xxx_messageInfo_AddSharableOrgResp.Size(m)
}
func (m *AddSharableOrgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSharableOrgResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddSharableOrgResp proto.InternalMessageInfo

func (m *AddSharableOrgResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveSharableOrgReq struct {
	// The ID of the sharable org to remove.
	RemoveOrgID          string   `protobuf:"bytes,1,opt,name=removeOrgID,proto3" json:"removeOrgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSharableOrgReq) Reset()         { *m = RemoveSharableOrgReq{} }
func (m *RemoveSharableOrgReq) String() string { return proto.CompactTextString(m) }
func (*RemoveSharableOrgReq) ProtoMessage()    {}
func (*RemoveSharableOrgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{20}
}

func (m *RemoveSharableOrgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSharableOrgReq.Unmarshal(m, b)
}
func (m *RemoveSharableOrgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSharableOrgReq.Marshal(b, m, deterministic)
}
func (m *RemoveSharableOrgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSharableOrgReq.Merge(m, src)
}
func (m *RemoveSharableOrgReq) XXX_Size() int {
	return xxx_messageInfo_RemoveSharableOrgReq.Size(m)
}
func (m *RemoveSharableOrgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSharableOrgReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSharableOrgReq proto.InternalMessageInfo

func (m *RemoveSharableOrgReq) GetRemoveOrgID() string {
	if m != nil {
		return m.RemoveOrgID
	}
	return ""
}

type RemoveSharableOrgResp struct {
	// Whether the removal was successful
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSharableOrgResp) Reset()         { *m = RemoveSharableOrgResp{} }
func (m *RemoveSharableOrgResp) String() string { return proto.CompactTextString(m) }
func (*RemoveSharableOrgResp) ProtoMessage()    {}
func (*RemoveSharableOrgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{21}
}

func (m *RemoveSharableOrgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSharableOrgResp.Unmarshal(m, b)
}
func (m *RemoveSharableOrgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSharableOrgResp.Marshal(b, m, deterministic)
}
func (m *RemoveSharableOrgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSharableOrgResp.Merge(m, src)
}
func (m *RemoveSharableOrgResp) XXX_Size() int {
	return xxx_messageInfo_RemoveSharableOrgResp.Size(m)
}
func (m *RemoveSharableOrgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSharableOrgResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSharableOrgResp proto.InternalMessageInfo

func (m *RemoveSharableOrgResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetMultiLevelSharingReq struct {
	// Whether or not to enable multi-level sharing
	Enable               bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMultiLevelSharingReq) Reset()         { *m = SetMultiLevelSharingReq{} }
func (m *SetMultiLevelSharingReq) String() string { return proto.CompactTextString(m) }
func (*SetMultiLevelSharingReq) ProtoMessage()    {}
func (*SetMultiLevelSharingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{22}
}

func (m *SetMultiLevelSharingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMultiLevelSharingReq.Unmarshal(m, b)
}
func (m *SetMultiLevelSharingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMultiLevelSharingReq.Marshal(b, m, deterministic)
}
func (m *SetMultiLevelSharingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMultiLevelSharingReq.Merge(m, src)
}
func (m *SetMultiLevelSharingReq) XXX_Size() int {
	return xxx_messageInfo_SetMultiLevelSharingReq.Size(m)
}
func (m *SetMultiLevelSharingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMultiLevelSharingReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetMultiLevelSharingReq proto.InternalMessageInfo

func (m *SetMultiLevelSharingReq) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type SetMultiLevelSharingResp struct {
	// Whether the update was successful
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMultiLevelSharingResp) Reset()         { *m = SetMultiLevelSharingResp{} }
func (m *SetMultiLevelSharingResp) String() string { return proto.CompactTextString(m) }
func (*SetMultiLevelSharingResp) ProtoMessage()    {}
func (*SetMultiLevelSharingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{23}
}

func (m *SetMultiLevelSharingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMultiLevelSharingResp.Unmarshal(m, b)
}
func (m *SetMultiLevelSharingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMultiLevelSharingResp.Marshal(b, m, deterministic)
}
func (m *SetMultiLevelSharingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMultiLevelSharingResp.Merge(m, src)
}
func (m *SetMultiLevelSharingResp) XXX_Size() int {
	return xxx_messageInfo_SetMultiLevelSharingResp.Size(m)
}
func (m *SetMultiLevelSharingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMultiLevelSharingResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetMultiLevelSharingResp proto.InternalMessageInfo

func (m *SetMultiLevelSharingResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetAccountInfoReq struct {
	// The new organization email address
	OrgEmail string `protobuf:"bytes,1,opt,name=orgEmail,proto3" json:"orgEmail,omitempty"`
	// The new organization address
	OrgAddress           string   `protobuf:"bytes,2,opt,name=orgAddress,proto3" json:"orgAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAccountInfoReq) Reset()         { *m = SetAccountInfoReq{} }
func (m *SetAccountInfoReq) String() string { return proto.CompactTextString(m) }
func (*SetAccountInfoReq) ProtoMessage()    {}
func (*SetAccountInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{24}
}

func (m *SetAccountInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAccountInfoReq.Unmarshal(m, b)
}
func (m *SetAccountInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAccountInfoReq.Marshal(b, m, deterministic)
}
func (m *SetAccountInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAccountInfoReq.Merge(m, src)
}
func (m *SetAccountInfoReq) XXX_Size() int {
	return xxx_messageInfo_SetAccountInfoReq.Size(m)
}
func (m *SetAccountInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAccountInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetAccountInfoReq proto.InternalMessageInfo

func (m *SetAccountInfoReq) GetOrgEmail() string {
	if m != nil {
		return m.OrgEmail
	}
	return ""
}

func (m *SetAccountInfoReq) GetOrgAddress() string {
	if m != nil {
		return m.OrgAddress
	}
	return ""
}

type SetAccountInfoResp struct {
	// Whether the update was successful
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAccountInfoResp) Reset()         { *m = SetAccountInfoResp{} }
func (m *SetAccountInfoResp) String() string { return proto.CompactTextString(m) }
func (*SetAccountInfoResp) ProtoMessage()    {}
func (*SetAccountInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{25}
}

func (m *SetAccountInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAccountInfoResp.Unmarshal(m, b)
}
func (m *SetAccountInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAccountInfoResp.Marshal(b, m, deterministic)
}
func (m *SetAccountInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAccountInfoResp.Merge(m, src)
}
func (m *SetAccountInfoResp) XXX_Size() int {
	return xxx_messageInfo_SetAccountInfoResp.Size(m)
}
func (m *SetAccountInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAccountInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetAccountInfoResp proto.InternalMessageInfo

func (m *SetAccountInfoResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetUserInfoReq struct {
	// The new user name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The new user email
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserInfoReq) Reset()         { *m = SetUserInfoReq{} }
func (m *SetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*SetUserInfoReq) ProtoMessage()    {}
func (*SetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{26}
}

func (m *SetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserInfoReq.Unmarshal(m, b)
}
func (m *SetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *SetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserInfoReq.Merge(m, src)
}
func (m *SetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_SetUserInfoReq.Size(m)
}
func (m *SetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserInfoReq proto.InternalMessageInfo

func (m *SetUserInfoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetUserInfoReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SetUserInfoResp struct {
	// Whether the update was successful
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserInfoResp) Reset()         { *m = SetUserInfoResp{} }
func (m *SetUserInfoResp) String() string { return proto.CompactTextString(m) }
func (*SetUserInfoResp) ProtoMessage()    {}
func (*SetUserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{27}
}

func (m *SetUserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserInfoResp.Unmarshal(m, b)
}
func (m *SetUserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserInfoResp.Marshal(b, m, deterministic)
}
func (m *SetUserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserInfoResp.Merge(m, src)
}
func (m *SetUserInfoResp) XXX_Size() int {
	return xxx_messageInfo_SetUserInfoResp.Size(m)
}
func (m *SetUserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserInfoResp proto.InternalMessageInfo

func (m *SetUserInfoResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ChangeUserPasswordReq struct {
	// The old user password
	OldPassword string `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	// The new user password
	NewPassword          string   `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeUserPasswordReq) Reset()         { *m = ChangeUserPasswordReq{} }
func (m *ChangeUserPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ChangeUserPasswordReq) ProtoMessage()    {}
func (*ChangeUserPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{28}
}

func (m *ChangeUserPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserPasswordReq.Unmarshal(m, b)
}
func (m *ChangeUserPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserPasswordReq.Marshal(b, m, deterministic)
}
func (m *ChangeUserPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserPasswordReq.Merge(m, src)
}
func (m *ChangeUserPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ChangeUserPasswordReq.Size(m)
}
func (m *ChangeUserPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserPasswordReq proto.InternalMessageInfo

func (m *ChangeUserPasswordReq) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangeUserPasswordReq) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangeUserPasswordResp struct {
	// Whether the update was successful
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeUserPasswordResp) Reset()         { *m = ChangeUserPasswordResp{} }
func (m *ChangeUserPasswordResp) String() string { return proto.CompactTextString(m) }
func (*ChangeUserPasswordResp) ProtoMessage()    {}
func (*ChangeUserPasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{29}
}

func (m *ChangeUserPasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserPasswordResp.Unmarshal(m, b)
}
func (m *ChangeUserPasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserPasswordResp.Marshal(b, m, deterministic)
}
func (m *ChangeUserPasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserPasswordResp.Merge(m, src)
}
func (m *ChangeUserPasswordResp) XXX_Size() int {
	return xxx_messageInfo_ChangeUserPasswordResp.Size(m)
}
func (m *ChangeUserPasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserPasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserPasswordResp proto.InternalMessageInfo

func (m *ChangeUserPasswordResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Subscription struct {
	// Subscription type (AWS Marketplace, Credit Card, etc.)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// State of the subscription (Created, Subscribed, Unsubscribed, etc.)
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{30}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Subscription) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Payment struct {
	// Timestamp of the payment billing transaction
	BilledAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=billedAt,proto3" json:"billedAt,omitempty"`
	// Start of the payment period
	PeriodStart *timestamp.Timestamp `protobuf:"bytes,2,opt,name=periodStart,proto3" json:"periodStart,omitempty"`
	// End of the payment period
	PeriodEnd *timestamp.Timestamp `protobuf:"bytes,3,opt,name=periodEnd,proto3" json:"periodEnd,omitempty"`
	// Amount of  payment
	Amount float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// Payment status ("No Payment","Zero Payment","Payment Pending","Payment Success","Payment Failed")
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{31}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetBilledAt() *timestamp.Timestamp {
	if m != nil {
		return m.BilledAt
	}
	return nil
}

func (m *Payment) GetPeriodStart() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodStart
	}
	return nil
}

func (m *Payment) GetPeriodEnd() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodEnd
	}
	return nil
}

func (m *Payment) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAccountInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountInfoReq) Reset()         { *m = GetAccountInfoReq{} }
func (m *GetAccountInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoReq) ProtoMessage()    {}
func (*GetAccountInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{32}
}

func (m *GetAccountInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountInfoReq.Unmarshal(m, b)
}
func (m *GetAccountInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountInfoReq.Marshal(b, m, deterministic)
}
func (m *GetAccountInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountInfoReq.Merge(m, src)
}
func (m *GetAccountInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetAccountInfoReq.Size(m)
}
func (m *GetAccountInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountInfoReq proto.InternalMessageInfo

type GetAccountInfoResp struct {
	// Account's orgID
	OrgID string `protobuf:"bytes,1,opt,name=orgID,proto3" json:"orgID,omitempty"`
	// Account's email
	OrgEmail string `protobuf:"bytes,2,opt,name=orgEmail,proto3" json:"orgEmail,omitempty"`
	// Account's subscription info
	Subscription *Subscription `protobuf:"bytes,3,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// List of all account's payments
	Payments []*Payment `protobuf:"bytes,4,rep,name=payments,proto3" json:"payments,omitempty"`
	// The address of the organization
	OrgAddress string `protobuf:"bytes,5,opt,name=orgAddress,proto3" json:"orgAddress,omitempty"`
	// The ability to "reshare" a document that was shared to him/her to another user
	MultiLevelShare bool `protobuf:"varint,6,opt,name=multiLevelShare,proto3" json:"multiLevelShare,omitempty"`
	// The list of sharable organization IDs.
	SharableOrgs         []string `protobuf:"bytes,7,rep,name=sharableOrgs,proto3" json:"sharableOrgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountInfoResp) Reset()         { *m = GetAccountInfoResp{} }
func (m *GetAccountInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoResp) ProtoMessage()    {}
func (*GetAccountInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{33}
}

func (m *GetAccountInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountInfoResp.Unmarshal(m, b)
}
func (m *GetAccountInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountInfoResp.Marshal(b, m, deterministic)
}
func (m *GetAccountInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountInfoResp.Merge(m, src)
}
func (m *GetAccountInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetAccountInfoResp.Size(m)
}
func (m *GetAccountInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountInfoResp proto.InternalMessageInfo

func (m *GetAccountInfoResp) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *GetAccountInfoResp) GetOrgEmail() string {
	if m != nil {
		return m.OrgEmail
	}
	return ""
}

func (m *GetAccountInfoResp) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *GetAccountInfoResp) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func (m *GetAccountInfoResp) GetOrgAddress() string {
	if m != nil {
		return m.OrgAddress
	}
	return ""
}

func (m *GetAccountInfoResp) GetMultiLevelShare() bool {
	if m != nil {
		return m.MultiLevelShare
	}
	return false
}

func (m *GetAccountInfoResp) GetSharableOrgs() []string {
	if m != nil {
		return m.SharableOrgs
	}
	return nil
}

type GetUserInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{34}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

type GetUserInfoResp struct {
	// The user's userID
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// The user's email
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// The user's name
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	// The user's orgID
	OrgID string `protobuf:"bytes,4,opt,name=orgID,proto3" json:"orgID,omitempty"`
	// Whether the user is an admin
	IsAdmin bool `protobuf:"varint,5,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	// Returns organization and user keypairs if e2e enabled
	Keyse2E              *KeysE2E `protobuf:"bytes,6,opt,name=keyse2e,proto3" json:"keyse2e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoResp) Reset()         { *m = GetUserInfoResp{} }
func (m *GetUserInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResp) ProtoMessage()    {}
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{35}
}

func (m *GetUserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResp.Unmarshal(m, b)
}
func (m *GetUserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResp.Merge(m, src)
}
func (m *GetUserInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResp.Size(m)
}
func (m *GetUserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResp proto.InternalMessageInfo

func (m *GetUserInfoResp) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserInfoResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserInfoResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserInfoResp) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *GetUserInfoResp) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *GetUserInfoResp) GetKeyse2E() *KeysE2E {
	if m != nil {
		return m.Keyse2E
	}
	return nil
}

type KeysE2E struct {
	OrgPubKey            string   `protobuf:"bytes,1,opt,name=orgPubKey,proto3" json:"orgPubKey,omitempty"`
	OrgEncPrivKey        string   `protobuf:"bytes,2,opt,name=orgEncPrivKey,proto3" json:"orgEncPrivKey,omitempty"`
	UserPubKey           string   `protobuf:"bytes,3,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	UserEncPrivKey       string   `protobuf:"bytes,4,opt,name=userEncPrivKey,proto3" json:"userEncPrivKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysE2E) Reset()         { *m = KeysE2E{} }
func (m *KeysE2E) String() string { return proto.CompactTextString(m) }
func (*KeysE2E) ProtoMessage()    {}
func (*KeysE2E) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{36}
}

func (m *KeysE2E) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysE2E.Unmarshal(m, b)
}
func (m *KeysE2E) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysE2E.Marshal(b, m, deterministic)
}
func (m *KeysE2E) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysE2E.Merge(m, src)
}
func (m *KeysE2E) XXX_Size() int {
	return xxx_messageInfo_KeysE2E.Size(m)
}
func (m *KeysE2E) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysE2E.DiscardUnknown(m)
}

var xxx_messageInfo_KeysE2E proto.InternalMessageInfo

func (m *KeysE2E) GetOrgPubKey() string {
	if m != nil {
		return m.OrgPubKey
	}
	return ""
}

func (m *KeysE2E) GetOrgEncPrivKey() string {
	if m != nil {
		return m.OrgEncPrivKey
	}
	return ""
}

func (m *KeysE2E) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *KeysE2E) GetUserEncPrivKey() string {
	if m != nil {
		return m.UserEncPrivKey
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterOrganizationReq)(nil), "proto.RegisterOrganizationReq")
	proto.RegisterType((*RegisterOrganizationResp)(nil), "proto.RegisterOrganizationResp")
	proto.RegisterType((*RegisterUserReq)(nil), "proto.RegisterUserReq")
	proto.RegisterType((*RegisterUserResp)(nil), "proto.RegisterUserResp")
	proto.RegisterType((*RemoveUserReq)(nil), "proto.RemoveUserReq")
	proto.RegisterType((*RemoveUserResp)(nil), "proto.RemoveUserResp")
	proto.RegisterType((*PromoteUserReq)(nil), "proto.PromoteUserReq")
	proto.RegisterType((*PromoteUserResp)(nil), "proto.PromoteUserResp")
	proto.RegisterType((*DemoteUserReq)(nil), "proto.DemoteUserReq")
	proto.RegisterType((*DemoteUserResp)(nil), "proto.DemoteUserResp")
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "proto.LoginResp")
	proto.RegisterType((*LogoutReq)(nil), "proto.LogoutReq")
	proto.RegisterType((*LogoutResp)(nil), "proto.LogoutResp")
	proto.RegisterType((*ListUsersReq)(nil), "proto.ListUsersReq")
	proto.RegisterType((*ListUsersResp)(nil), "proto.ListUsersResp")
	proto.RegisterType((*ListUsersResp_OrgUser)(nil), "proto.ListUsersResp.OrgUser")
	proto.RegisterType((*RemoveOrganizationReq)(nil), "proto.RemoveOrganizationReq")
	proto.RegisterType((*RemoveOrganizationResp)(nil), "proto.RemoveOrganizationResp")
	proto.RegisterType((*AddSharableOrgReq)(nil), "proto.AddSharableOrgReq")
	proto.RegisterType((*AddSharableOrgResp)(nil), "proto.AddSharableOrgResp")
	proto.RegisterType((*RemoveSharableOrgReq)(nil), "proto.RemoveSharableOrgReq")
	proto.RegisterType((*RemoveSharableOrgResp)(nil), "proto.RemoveSharableOrgResp")
	proto.RegisterType((*SetMultiLevelSharingReq)(nil), "proto.SetMultiLevelSharingReq")
	proto.RegisterType((*SetMultiLevelSharingResp)(nil), "proto.SetMultiLevelSharingResp")
	proto.RegisterType((*SetAccountInfoReq)(nil), "proto.SetAccountInfoReq")
	proto.RegisterType((*SetAccountInfoResp)(nil), "proto.SetAccountInfoResp")
	proto.RegisterType((*SetUserInfoReq)(nil), "proto.SetUserInfoReq")
	proto.RegisterType((*SetUserInfoResp)(nil), "proto.SetUserInfoResp")
	proto.RegisterType((*ChangeUserPasswordReq)(nil), "proto.ChangeUserPasswordReq")
	proto.RegisterType((*ChangeUserPasswordResp)(nil), "proto.ChangeUserPasswordResp")
	proto.RegisterType((*Subscription)(nil), "proto.Subscription")
	proto.RegisterType((*Payment)(nil), "proto.Payment")
	proto.RegisterType((*GetAccountInfoReq)(nil), "proto.GetAccountInfoReq")
	proto.RegisterType((*GetAccountInfoResp)(nil), "proto.GetAccountInfoResp")
	proto.RegisterType((*GetUserInfoReq)(nil), "proto.GetUserInfoReq")
	proto.RegisterType((*GetUserInfoResp)(nil), "proto.GetUserInfoResp")
	proto.RegisterType((*KeysE2E)(nil), "proto.KeysE2e")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 2272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x18, 0x5d, 0x6f, 0xdc, 0x58,
	0x55, 0xce, 0x34, 0x4d, 0x72, 0x93, 0xe6, 0xe3, 0xf6, 0x6b, 0x1a, 0x96, 0xc5, 0xba, 0xb0, 0x34,
	0xeb, 0x4e, 0x27, 0x33, 0xee, 0xb6, 0x54, 0x16, 0xcb, 0xc6, 0x4d, 0x4a, 0xa9, 0xfa, 0x91, 0x30,
	0xe9, 0x52, 0xc4, 0xb6, 0xcb, 0x7a, 0xec, 0x1b, 0xc7, 0x64, 0xc6, 0x9e, 0xbd, 0xd7, 0x93, 0x28,
	0x1d, 0x59, 0x3c, 0x21, 0x81, 0xc4, 0x4a, 0xc8, 0x12, 0x12, 0xaf, 0x48, 0x7c, 0x88, 0x57, 0x84,
	0xb4, 0x0f, 0x3c, 0xf0, 0xcc, 0xdb, 0x22, 0xf8, 0x13, 0x08, 0xb1, 0xe2, 0x27, 0xa0, 0xfb, 0xe1,
	0x99, 0x6b, 0xc7, 0x33, 0x9d, 0x7d, 0x5b, 0x29, 0xd1, 0xf8, 0x9c, 0x7b, 0xce, 0xb9, 0xe7, 0xfb,
	0x9e, 0x7b, 0xc1, 0xb2, 0xe3, 0xba, 0x51, 0x3f, 0x8c, 0x69, 0xbd, 0x47, 0xa2, 0x38, 0x82, 0xb3,
	0xfc, 0x67, 0xbd, 0xc6, 0x7f, 0xdc, 0x9b, 0x3e, 0x0e, 0x6f, 0xd2, 0x13, 0xc7, 0xf7, 0x31, 0xd9,
	0x8c, 0x7a, 0x71, 0x10, 0x85, 0x74, 0xd3, 0x09, 0xc3, 0x28, 0x76, 0xf8, 0xb7, 0x60, 0x5a, 0xff,
	0x9a, 0x1f, 0x45, 0x7e, 0x07, 0x6f, 0x72, 0xa8, 0xdd, 0x3f, 0xd8, 0x8c, 0x83, 0x2e, 0xa6, 0xb1,
	0xd3, 0xed, 0x09, 0x02, 0xf4, 0xf9, 0x2c, 0xb8, 0xda, 0xc2, 0x7e, 0x40, 0x63, 0x4c, 0x76, 0x89,
	0xef, 0x84, 0xc1, 0x2b, 0x2e, 0xa0, 0x85, 0x3f, 0x86, 0x55, 0x30, 0x17, 0x11, 0xff, 0xa9, 0xd3,
	0xc5, 0x55, 0x4d, 0xd7, 0x36, 0x16, 0x5a, 0x19, 0x08, 0xd7, 0xc1, 0x7c, 0x44, 0xfc, 0xfb, 0x5d,
	0x27, 0xe8, 0x54, 0x67, 0xf8, 0xd2, 0x10, 0x96, 0x5c, 0xb6, 0xe7, 0x91, 0x6a, 0x65, 0xc8, 0xc5,
	0x40, 0xc6, 0xd5, 0xa7, 0x98, 0x70, 0x81, 0xe7, 0x04, 0x57, 0x06, 0xb3, 0xb5, 0x9e, 0x43, 0xe9,
	0x49, 0x44, 0xbc, 0xea, 0xac, 0x58, 0xcb, 0x60, 0xf8, 0x26, 0x00, 0x8e, 0xd7, 0x0d, 0x42, 0xb1,
	0xdf, 0x79, 0xbe, 0xaa, 0x60, 0x20, 0x02, 0x4b, 0xf4, 0xd0, 0x21, 0x4e, 0xbb, 0x83, 0x77, 0x89,
	0x4f, 0xab, 0x73, 0x7a, 0x65, 0x63, 0xa1, 0x95, 0xc3, 0xc1, 0x0d, 0xb0, 0xd2, 0xed, 0x77, 0xe2,
	0xe0, 0x31, 0x3e, 0xc6, 0x9d, 0xfd, 0x43, 0x87, 0xe0, 0xea, 0xbc, 0xae, 0x6d, 0xcc, 0xb7, 0x8a,
	0x68, 0x78, 0x05, 0x9c, 0xa7, 0x51, 0x9f, 0xb8, 0xb8, 0xba, 0xc0, 0x77, 0x92, 0x10, 0xd3, 0x42,
	0x7c, 0xed, 0x38, 0xb1, 0x53, 0x05, 0x42, 0x8b, 0x11, 0x06, 0x42, 0x70, 0xae, 0xd7, 0x7d, 0xb8,
	0x53, 0x5d, 0xe4, 0x2b, 0xfc, 0xdb, 0xfa, 0x55, 0x25, 0xb5, 0x7f, 0x59, 0x01, 0xd7, 0x8c, 0x71,
	0x3e, 0x36, 0x3f, 0x9f, 0x81, 0xff, 0x99, 0x19, 0x20, 0xe9, 0x58, 0x64, 0xe9, 0xe8, 0xf9, 0x61,
	0x10, 0xe3, 0xef, 0x45, 0x7d, 0x8a, 0x51, 0x4d, 0x47, 0x99, 0x5b, 0xd9, 0x0a, 0x66, 0x1f, 0x5b,
	0x6e, 0xd4, 0xed, 0x39, 0xe1, 0x69, 0xdd, 0x8d, 0xba, 0x92, 0x80, 0x39, 0x97, 0xad, 0x37, 0xef,
	0x34, 0x1a, 0xfa, 0x1e, 0x0e, 0x43, 0x7a, 0xda, 0x39, 0x76, 0xc2, 0xc0, 0xd1, 0xed, 0x63, 0xac,
	0x3f, 0x7d, 0x5e, 0xd3, 0x9f, 0x3b, 0xf4, 0x30, 0x08, 0xfd, 0x38, 0x0a, 0x6b, 0xfa, 0xce, 0xb6,
	0x6e, 0x36, 0x6e, 0x37, 0x1a, 0x8c, 0x39, 0x73, 0x3f, 0xe3, 0xde, 0x89, 0x42, 0xa7, 0xe3, 0xe9,
	0xcf, 0x48, 0xbf, 0xdb, 0x63, 0x6b, 0x99, 0xfb, 0xd9, 0x5a, 0xff, 0x88, 0x38, 0x41, 0x18, 0xd0,
	0xee, 0xe9, 0x01, 0x09, 0x70, 0xe8, 0xb1, 0xf5, 0x51, 0x00, 0x18, 0x85, 0xc7, 0xb9, 0xeb, 0x31,
	0xe3, 0xde, 0x3a, 0x61, 0x26, 0x1c, 0x32, 0x13, 0xea, 0x7e, 0x74, 0xcc, 0x88, 0xd5, 0x58, 0x20,
	0x4b, 0xff, 0x00, 0xb9, 0x61, 0xc8, 0xf0, 0x07, 0xed, 0x80, 0xfd, 0x78, 0xb8, 0x1b, 0xb9, 0xc4,
	0x89, 0x29, 0x7a, 0x59, 0xd3, 0x51, 0x21, 0x22, 0xc8, 0xd2, 0x63, 0xd2, 0xc7, 0x4c, 0x0a, 0xf7,
	0x36, 0xdb, 0x0e, 0x0d, 0x21, 0xe6, 0x7b, 0x86, 0x19, 0xbc, 0x40, 0x84, 0xfb, 0x98, 0x70, 0xdf,
	0x3e, 0x8b, 0x8e, 0x70, 0xf8, 0x02, 0x59, 0xfa, 0x0b, 0xe4, 0xb4, 0x5d, 0xaf, 0x69, 0xde, 0x7a,
	0xe7, 0x05, 0x4a, 0x50, 0x82, 0xfe, 0xa1, 0x81, 0x6a, 0x79, 0x30, 0x68, 0x0f, 0x5e, 0x02, 0xb3,
	0x11, 0xf1, 0x1f, 0xee, 0xc8, 0x7c, 0x17, 0x00, 0xcb, 0x08, 0xe6, 0xa8, 0x87, 0x3b, 0x32, 0xd7,
	0x25, 0xc4, 0xf2, 0xce, 0xed, 0x04, 0x38, 0x8c, 0xf7, 0xb1, 0x4b, 0x70, 0x2c, 0xd3, 0x3d, 0x87,
	0xb3, 0xdc, 0xd4, 0xfe, 0x08, 0xac, 0x1b, 0x63, 0xb7, 0x34, 0xef, 0xc1, 0x2d, 0x1e, 0xfe, 0x87,
	0x3b, 0x67, 0x83, 0x2f, 0xf6, 0x79, 0x9d, 0x7b, 0x13, 0xf4, 0xb3, 0x19, 0xb0, 0x92, 0x6d, 0xf0,
	0x3e, 0xc5, 0x84, 0x15, 0xaf, 0x5a, 0x6c, 0xda, 0x84, 0x62, 0x9b, 0x29, 0x14, 0xdb, 0x25, 0x30,
	0xcb, 0xf3, 0x4c, 0x5a, 0x23, 0x00, 0x86, 0xe5, 0xf1, 0xe6, 0x75, 0x3b, 0xdf, 0x12, 0x80, 0xf5,
	0x89, 0x96, 0xda, 0xbf, 0xd0, 0xc0, 0x9a, 0x51, 0xdc, 0xdd, 0x8c, 0x21, 0x19, 0xe4, 0xb2, 0xeb,
	0x49, 0x70, 0x84, 0x59, 0x6e, 0xba, 0xb8, 0x98, 0x5b, 0xc2, 0xb4, 0x7c, 0x6e, 0xe1, 0x2c, 0xad,
	0xba, 0xc1, 0x11, 0xae, 0xf7, 0x18, 0x5b, 0x49, 0x52, 0x71, 0x25, 0x18, 0xd5, 0x81, 0xd3, 0xa1,
	0x18, 0x25, 0x28, 0x04, 0xab, 0x79, 0x45, 0x68, 0x4f, 0x09, 0x9e, 0xa6, 0x06, 0xcf, 0xba, 0x97,
	0xda, 0xef, 0x01, 0x68, 0x9c, 0x61, 0x30, 0xdf, 0x86, 0xd7, 0x07, 0x8a, 0xe7, 0xc7, 0x6b, 0x90,
	0xa0, 0x00, 0x5c, 0x68, 0xe1, 0x6e, 0x74, 0x8c, 0x33, 0xa7, 0x8f, 0xdb, 0x6c, 0x2b, 0xb5, 0xdf,
	0x05, 0x2b, 0x46, 0x9e, 0xda, 0x34, 0xe0, 0xc6, 0xa0, 0x18, 0xe3, 0x71, 0x21, 0x7e, 0x02, 0x96,
	0x55, 0x66, 0x91, 0xab, 0xfc, 0x7c, 0xe0, 0x5b, 0x55, 0x5a, 0x02, 0xb0, 0xde, 0x4a, 0x6d, 0x04,
	0x56, 0x8d, 0x02, 0xb1, 0xb9, 0x0c, 0x97, 0x06, 0x88, 0x53, 0x20, 0x4b, 0x6f, 0x26, 0xe8, 0x08,
	0x2c, 0xef, 0x91, 0xa8, 0x1b, 0xc5, 0xaf, 0x55, 0xdd, 0x4e, 0xed, 0xef, 0x30, 0x81, 0x79, 0xf2,
	0x52, 0xdd, 0xbd, 0xba, 0xd7, 0x77, 0x8f, 0xce, 0xea, 0xfe, 0x43, 0xb0, 0x92, 0xe3, 0xa6, 0x3d,
	0x76, 0x48, 0xd0, 0xbe, 0xeb, 0x62, 0x4a, 0xf9, 0x76, 0xf3, 0xad, 0x0c, 0xb4, 0x6e, 0xa4, 0xf6,
	0x06, 0xcb, 0xa8, 0x02, 0x87, 0x79, 0x11, 0xae, 0x0d, 0x90, 0x24, 0x92, 0x1d, 0x21, 0x41, 0x3f,
	0x01, 0x17, 0x76, 0xf0, 0xd4, 0x56, 0xac, 0x18, 0x79, 0x6a, 0xf3, 0x06, 0x7c, 0x7b, 0x30, 0x75,
	0x91, 0xfd, 0x00, 0x2c, 0xab, 0xdc, 0x13, 0x8d, 0x30, 0x52, 0xfb, 0x3a, 0x73, 0x5a, 0x9e, 0xa1,
	0xdc, 0x86, 0xbf, 0x6b, 0x60, 0xfe, 0x71, 0xe4, 0x07, 0xe1, 0x04, 0xfd, 0x5f, 0x57, 0xb1, 0xa2,
	0x69, 0x55, 0x94, 0xa6, 0x65, 0xd1, 0xd4, 0xee, 0x01, 0x60, 0x0c, 0x45, 0x9b, 0x6d, 0xf8, 0xd1,
	0xb4, 0xc6, 0x4e, 0xd1, 0xfd, 0xcb, 0x3a, 0x56, 0x82, 0x7e, 0xa7, 0x81, 0x05, 0xb9, 0xa1, 0xc8,
	0xd0, 0x98, 0xb5, 0xe1, 0xac, 0x9b, 0x72, 0x80, 0x79, 0xed, 0xc8, 0x3b, 0x78, 0x82, 0x63, 0x47,
	0x5a, 0x92, 0x81, 0x8c, 0xfe, 0x08, 0x9f, 0x8e, 0x0c, 0xe1, 0x80, 0xf5, 0xfd, 0xd4, 0x7e, 0x0a,
	0x16, 0x8d, 0x91, 0x5c, 0xf3, 0x3d, 0xf8, 0xee, 0x00, 0x71, 0x61, 0x4c, 0x81, 0x76, 0xc7, 0x39,
	0xcc, 0xfe, 0x99, 0x66, 0x52, 0x1a, 0x5b, 0xa2, 0x98, 0x04, 0x4e, 0x27, 0x78, 0x85, 0xbd, 0x47,
	0x02, 0xc9, 0x0f, 0x8b, 0x04, 0x7d, 0x95, 0x6b, 0x19, 0xf5, 0xe3, 0x16, 0xfe, 0xd8, 0x5a, 0x4d,
	0xed, 0x0b, 0x52, 0xbe, 0xc0, 0xa0, 0x3d, 0x00, 0x32, 0x40, 0x34, 0x10, 0x1a, 0x3b, 0x71, 0x9f,
	0x66, 0x21, 0x11, 0x90, 0x88, 0xf1, 0x92, 0xa1, 0x90, 0x9a, 0x57, 0xe1, 0xe5, 0x01, 0x12, 0xcb,
	0x6c, 0xfb, 0xd3, 0xa8, 0xaf, 0xef, 0xbe, 0xff, 0x0c, 0x25, 0xe8, 0xeb, 0x60, 0xe9, 0x71, 0x40,
	0x63, 0x96, 0x08, 0x94, 0xed, 0x79, 0x31, 0xb5, 0x57, 0xc1, 0xb2, 0x91, 0x43, 0xa2, 0xdf, 0xce,
	0x80, 0x0b, 0x0a, 0x82, 0xf6, 0xe0, 0x5d, 0x3e, 0x66, 0x71, 0xb8, 0xaa, 0xe9, 0x95, 0x8d, 0x45,
	0xf3, 0x0d, 0x31, 0xb6, 0xd5, 0x73, 0x74, 0xf5, 0x5d, 0x41, 0xd4, 0x1a, 0x52, 0xaf, 0x3f, 0x07,
	0x73, 0x12, 0x39, 0xf1, 0x20, 0x18, 0x77, 0xb2, 0x55, 0xc1, 0x5c, 0x40, 0x6d, 0xde, 0xf0, 0x2b,
	0x22, 0xb3, 0x25, 0x68, 0x25, 0xa9, 0xfd, 0x8a, 0x15, 0x52, 0x4e, 0x01, 0xd3, 0x87, 0x98, 0x1f,
	0x62, 0x1c, 0x83, 0xac, 0x0f, 0x06, 0x13, 0x27, 0x8b, 0xa9, 0x93, 0x50, 0x6e, 0x9a, 0x95, 0xca,
	0xcb, 0x04, 0x7d, 0x08, 0x2e, 0x8b, 0xce, 0x56, 0x9c, 0x55, 0x2f, 0x81, 0xd9, 0x83, 0x88, 0x0d,
	0x6d, 0xa2, 0x12, 0x05, 0x60, 0x6d, 0xa6, 0x76, 0x0d, 0x5c, 0x35, 0xca, 0x79, 0xcc, 0x35, 0xb8,
	0x32, 0x40, 0x9c, 0x70, 0x58, 0x8c, 0xbf, 0xd1, 0xc0, 0x95, 0x32, 0xe2, 0x49, 0xd5, 0x0e, 0xdf,
	0x00, 0x0b, 0xbd, 0x88, 0xc6, 0xbd, 0x28, 0xc4, 0xa2, 0x3a, 0xe7, 0x5b, 0x23, 0x84, 0xf5, 0xdd,
	0xd4, 0xde, 0x06, 0x55, 0x63, 0x8c, 0x58, 0xf3, 0x3a, 0x7c, 0xab, 0xd8, 0x13, 0x58, 0xf9, 0x65,
	0xec, 0xc8, 0xd2, 0xf9, 0xe9, 0x96, 0x20, 0x17, 0xac, 0xd9, 0x9e, 0xb7, 0x3f, 0x1a, 0xa4, 0xe4,
	0x29, 0x1f, 0xe2, 0x93, 0x5d, 0x65, 0x66, 0x19, 0xc2, 0x96, 0x99, 0xda, 0x9b, 0xe0, 0xa2, 0x71,
	0x96, 0xcb, 0xac, 0xc2, 0x2b, 0x03, 0x94, 0xd1, 0xf1, 0x42, 0x89, 0x49, 0x10, 0xfa, 0x88, 0xf9,
	0x17, 0x16, 0xc9, 0x27, 0x36, 0xba, 0x7a, 0x6a, 0xdf, 0x00, 0x97, 0x8c, 0x12, 0xa6, 0xf2, 0x66,
	0x47, 0xc0, 0x25, 0xe1, 0x87, 0x82, 0x1d, 0x3a, 0x58, 0x24, 0x99, 0x7f, 0x86, 0xa6, 0xa8, 0x28,
	0xeb, 0x6e, 0x6a, 0xdf, 0x06, 0x57, 0x8c, 0x52, 0x76, 0xf3, 0x2b, 0xf0, 0xda, 0x00, 0x29, 0xd4,
	0x39, 0x9b, 0xbc, 0x2c, 0x67, 0xa6, 0x37, 0xab, 0x99, 0xda, 0xf5, 0x51, 0xde, 0x4c, 0x65, 0x19,
	0x06, 0x57, 0xf7, 0x71, 0xfc, 0x24, 0x37, 0xba, 0x06, 0xa1, 0x2f, 0x9b, 0x3a, 0x0e, 0x99, 0x00,
	0xb9, 0x8d, 0x84, 0x44, 0x80, 0xae, 0x19, 0xe3, 0xf8, 0x4c, 0x08, 0x57, 0x07, 0x48, 0xd0, 0x2a,
	0x27, 0x5e, 0xb5, 0x9c, 0x7c, 0xa2, 0x3d, 0xef, 0xa4, 0x76, 0x93, 0x4d, 0xa1, 0xe3, 0x58, 0xcb,
	0x4d, 0xfa, 0xb3, 0x06, 0xd6, 0xf6, 0x71, 0x6c, 0x8b, 0x7b, 0xe8, 0xc3, 0xf0, 0x20, 0x92, 0x29,
	0x37, 0xbc, 0xfb, 0x69, 0x85, 0xbb, 0xdf, 0x9b, 0x00, 0xc8, 0xfb, 0x08, 0x53, 0x42, 0xf4, 0x14,
	0x05, 0x63, 0x39, 0xa9, 0xfd, 0x21, 0x4b, 0xc9, 0x33, 0x52, 0xcd, 0x07, 0xf0, 0xfe, 0x20, 0x77,
	0xd9, 0x09, 0xf1, 0x09, 0xff, 0xde, 0x8a, 0x88, 0x7f, 0x82, 0xdb, 0x34, 0x88, 0x71, 0xe1, 0xca,
	0x23, 0x54, 0x45, 0x6c, 0xb4, 0xd7, 0x77, 0x89, 0xaf, 0xef, 0xc7, 0x75, 0x91, 0xc1, 0x45, 0xe9,
	0x53, 0x65, 0xf0, 0x59, 0xa6, 0x72, 0xa7, 0x7c, 0xa2, 0x81, 0xe5, 0x7d, 0xcc, 0x7b, 0x5f, 0xe6,
	0x11, 0x08, 0xce, 0x85, 0xa3, 0xee, 0xca, 0xbf, 0x47, 0x63, 0xf4, 0x8c, 0x32, 0x46, 0x8b, 0xb3,
	0x6c, 0xd5, 0x28, 0x08, 0x30, 0x2d, 0x78, 0x77, 0x80, 0x42, 0xd9, 0x2d, 0xd9, 0x82, 0xbe, 0x87,
	0x09, 0x8d, 0xc2, 0xdc, 0x28, 0x3c, 0x74, 0x88, 0xea, 0x0d, 0x3e, 0x5c, 0xe5, 0xa4, 0x4d, 0x35,
	0x5c, 0x15, 0x38, 0xca, 0x2d, 0xfd, 0x9b, 0x06, 0x2e, 0x6f, 0x1f, 0x3a, 0xa1, 0xcf, 0x07, 0x98,
	0x3d, 0x39, 0x10, 0xc8, 0x6a, 0x8d, 0x3a, 0x5e, 0x86, 0xc9, 0xaa, 0x55, 0x41, 0x31, 0x8a, 0x10,
	0x9f, 0xec, 0xe5, 0x47, 0x16, 0x15, 0x65, 0xb5, 0x53, 0xfb, 0xc7, 0xac, 0xc4, 0x4a, 0x77, 0x30,
	0x77, 0xe0, 0xbd, 0x01, 0x52, 0x04, 0x32, 0x07, 0x28, 0x60, 0xd3, 0xbc, 0xc5, 0x7c, 0xa3, 0xc8,
	0x93, 0x1e, 0x52, 0x09, 0x12, 0x74, 0x00, 0xae, 0x94, 0x89, 0x9f, 0xe8, 0x22, 0x5e, 0x94, 0x55,
	0x63, 0x0c, 0x63, 0xb9, 0xa7, 0x7e, 0x0a, 0x96, 0xf6, 0xfb, 0x6d, 0xea, 0x92, 0x80, 0x3f, 0xc4,
	0xb0, 0x84, 0x88, 0x4f, 0x7b, 0xc3, 0x84, 0x60, 0xdf, 0xca, 0x18, 0x31, 0x93, 0x1b, 0x23, 0xb6,
	0x53, 0x7b, 0x8b, 0x8d, 0x02, 0xaa, 0x00, 0xb3, 0x0e, 0x6b, 0x03, 0xc4, 0xd8, 0x90, 0x85, 0xb6,
	0x09, 0xf6, 0x82, 0x58, 0xdf, 0x76, 0x88, 0x87, 0x6a, 0xc3, 0xe9, 0x02, 0x49, 0xfa, 0x36, 0xf6,
	0x50, 0x82, 0xfe, 0x58, 0x01, 0x73, 0x7b, 0xce, 0x69, 0x17, 0x87, 0x31, 0xbc, 0x03, 0xe6, 0xdb,
	0x41, 0xa7, 0x83, 0x3d, 0x5b, 0x5c, 0x0d, 0x16, 0xcd, 0xf5, 0xba, 0x78, 0x05, 0xaa, 0x67, 0xaf,
	0x40, 0xf5, 0x67, 0xd9, 0x2b, 0x50, 0x6b, 0x48, 0x0b, 0xbf, 0x0d, 0x16, 0x7b, 0x98, 0x04, 0x91,
	0xb7, 0x1f, 0x3b, 0x24, 0xe6, 0x5a, 0x4e, 0x66, 0x55, 0xc9, 0xe1, 0x5d, 0xb0, 0x20, 0xc0, 0xfb,
	0xa1, 0xc7, 0x67, 0x86, 0xc9, 0xbc, 0x23, 0x62, 0xe6, 0x18, 0xa7, 0xcb, 0x2f, 0x32, 0xec, 0x6e,
	0xa9, 0xb5, 0x24, 0xa4, 0x38, 0x6c, 0x36, 0xe7, 0xb0, 0xbf, 0x6a, 0xa9, 0xfd, 0xa9, 0x06, 0x16,
	0x8c, 0xcc, 0x62, 0xf3, 0x4f, 0x1a, 0xfc, 0x83, 0x36, 0x40, 0x99, 0x25, 0x2c, 0x15, 0xcc, 0x86,
	0xd9, 0xb8, 0xd9, 0x30, 0x6f, 0x36, 0x9a, 0xcf, 0x9a, 0xa6, 0x75, 0xab, 0x61, 0x35, 0x6f, 0xd7,
	0x9b, 0xe6, 0xad, 0x1f, 0xf1, 0xd1, 0x76, 0xa4, 0xf6, 0x88, 0xb4, 0xc9, 0x48, 0x1b, 0x0d, 0x8b,
	0xff, 0xd5, 0x1b, 0x8d, 0x86, 0x42, 0x7a, 0x3f, 0xf4, 0x0a, 0x32, 0xcf, 0x10, 0x0a, 0x9d, 0x91,
	0xa5, 0xdf, 0x36, 0xeb, 0xcd, 0x3b, 0x35, 0x5d, 0x99, 0x02, 0x9f, 0x46, 0xba, 0x54, 0x14, 0xe9,
	0x09, 0xba, 0x08, 0xd6, 0x1e, 0x14, 0x9b, 0x1f, 0xfa, 0xdf, 0x2c, 0x80, 0x0f, 0xce, 0x36, 0xad,
	0xf2, 0xd7, 0x88, 0x49, 0x6f, 0x6f, 0xdf, 0x02, 0x4b, 0x54, 0xc9, 0x23, 0x19, 0x88, 0x8b, 0x72,
	0x68, 0x54, 0x53, 0xac, 0x95, 0x23, 0x84, 0x06, 0xbb, 0x5f, 0x70, 0x25, 0x69, 0xf5, 0x1c, 0x9f,
	0x34, 0x97, 0x25, 0x93, 0xd4, 0xbd, 0x35, 0x5c, 0x2f, 0x34, 0xf9, 0xd9, 0x62, 0x93, 0x2f, 0x7b,
	0x6a, 0x3b, 0x5f, 0xfe, 0xd4, 0x36, 0xc5, 0xc3, 0x9d, 0xf5, 0xaf, 0x4a, 0x6a, 0x7f, 0x56, 0x61,
	0x1d, 0xfa, 0xac, 0x87, 0xcc, 0x4f, 0x2b, 0xf0, 0x2f, 0x15, 0xe5, 0xf9, 0x24, 0x3e, 0x0c, 0xa8,
	0x3a, 0x61, 0x4d, 0xf5, 0x82, 0xa6, 0x3a, 0x02, 0x59, 0x5f, 0xa4, 0xee, 0xf8, 0x3d, 0x49, 0x78,
	0x85, 0x0f, 0xbd, 0x5f, 0xd2, 0x0c, 0x94, 0x21, 0xd4, 0xf7, 0x65, 0xdb, 0xd2, 0x93, 0x97, 0x67,
	0x4f, 0xd1, 0x2f, 0xfc, 0x76, 0x38, 0xfe, 0x95, 0x6e, 0xcc, 0x5b, 0x9f, 0xf2, 0xc8, 0x97, 0xa0,
	0x55, 0xb0, 0xfc, 0x20, 0x77, 0x08, 0xa2, 0xdf, 0x57, 0xc0, 0xca, 0x83, 0xc2, 0x49, 0x36, 0xee,
	0x3a, 0x5c, 0x7a, 0xba, 0xe6, 0x6e, 0x3a, 0x95, 0xc2, 0x4d, 0x67, 0x58, 0x4b, 0xe7, 0xd4, 0x5a,
	0x52, 0xee, 0x39, 0xb3, 0xb9, 0x7b, 0x0e, 0xdc, 0x00, 0x73, 0x47, 0xf8, 0x94, 0x62, 0x53, 0x24,
	0xef, 0xa8, 0x1e, 0x1e, 0xe1, 0x53, 0x7a, 0xdf, 0xc4, 0xad, 0x6c, 0xd9, 0xfa, 0xaf, 0x96, 0xda,
	0xff, 0xe6, 0x8f, 0x60, 0x05, 0xed, 0xcd, 0x7f, 0x6a, 0xf0, 0x33, 0x4d, 0xbd, 0x73, 0xcb, 0x2f,
	0xf5, 0x54, 0x17, 0x1f, 0x85, 0xa7, 0xd8, 0xe1, 0xb7, 0x7a, 0xd1, 0x16, 0x1f, 0x35, 0x24, 0xf7,
	0x65, 0x99, 0x1a, 0x11, 0x7f, 0xaf, 0xdf, 0x7e, 0x84, 0x4f, 0x91, 0xa5, 0x7c, 0xd7, 0x78, 0xca,
	0x87, 0xee, 0x1e, 0x09, 0x8e, 0x87, 0x6b, 0x0a, 0x5c, 0xe3, 0xf2, 0x87, 0x8c, 0x0a, 0x20, 0x56,
	0x72, 0xac, 0x05, 0x44, 0x92, 0xa0, 0x5f, 0x6b, 0x60, 0x4e, 0x3a, 0x81, 0xdd, 0x7c, 0x86, 0xfb,
	0xca, 0x10, 0x8d, 0x10, 0xf0, 0x1b, 0xe0, 0x42, 0x6e, 0x67, 0x19, 0xad, 0x3c, 0x92, 0xb5, 0x93,
	0x91, 0x0a, 0x32, 0x6e, 0x0a, 0x06, 0x7e, 0x13, 0x2c, 0xe7, 0x95, 0x90, 0x21, 0x2c, 0x60, 0xef,
	0x35, 0x00, 0x72, 0xa3, 0x6e, 0x9d, 0xc6, 0x24, 0x0a, 0x7d, 0xea, 0x74, 0x62, 0xf9, 0xe9, 0x45,
	0x6e, 0x9d, 0x7a, 0x47, 0x22, 0x7c, 0xf7, 0xe6, 0x64, 0x0b, 0xf9, 0xb9, 0xa6, 0xb5, 0xcf, 0x73,
	0xd4, 0xad, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x06, 0xa4, 0xc2, 0x6e, 0x6a, 0x19, 0x00, 0x00,
}
