// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeInterval int32

const (
	TimeInterval_UNDEFINED TimeInterval = 0
	TimeInterval_MONTHLY   TimeInterval = 1
	TimeInterval_YEARLY    TimeInterval = 2
)

var TimeInterval_name = map[int32]string{
	0: "UNDEFINED",
	1: "MONTHLY",
	2: "YEARLY",
}

var TimeInterval_value = map[string]int32{
	"UNDEFINED": 0,
	"MONTHLY":   1,
	"YEARLY":    2,
}

func (x TimeInterval) String() string {
	return proto.EnumName(TimeInterval_name, int32(x))
}

func (TimeInterval) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{0}
}

type GetBillingDetailsReq struct {
	// Timestamp of the requested billing details
	At                   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetBillingDetailsReq) Reset()         { *m = GetBillingDetailsReq{} }
func (m *GetBillingDetailsReq) String() string { return proto.CompactTextString(m) }
func (*GetBillingDetailsReq) ProtoMessage()    {}
func (*GetBillingDetailsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{0}
}

func (m *GetBillingDetailsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillingDetailsReq.Unmarshal(m, b)
}
func (m *GetBillingDetailsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillingDetailsReq.Marshal(b, m, deterministic)
}
func (m *GetBillingDetailsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillingDetailsReq.Merge(m, src)
}
func (m *GetBillingDetailsReq) XXX_Size() int {
	return xxx_messageInfo_GetBillingDetailsReq.Size(m)
}
func (m *GetBillingDetailsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillingDetailsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillingDetailsReq proto.InternalMessageInfo

func (m *GetBillingDetailsReq) GetAt() *timestamp.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

type GetBillingDetailsResp struct {
	// Start of the requested billing period
	PeriodStart *timestamp.Timestamp `protobuf:"bytes,1,opt,name=periodStart,proto3" json:"periodStart,omitempty"`
	// End of the requested billing period
	PeriodEnd *timestamp.Timestamp `protobuf:"bytes,2,opt,name=periodEnd,proto3" json:"periodEnd,omitempty"`
	// Total cost incurred during the requested billing period
	TotalCost float64 `protobuf:"fixed64,3,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	// Usage and cost breakdown for stored documents
	Documents *DocumentCosts `protobuf:"bytes,4,opt,name=documents,proto3" json:"documents,omitempty"`
	// Usage and cost breakdown for stored search indices
	Search *SearchCosts `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	// Usage and cost breakdown for used traffic
	Traffic *TrafficCosts `protobuf:"bytes,6,opt,name=traffic,proto3" json:"traffic,omitempty"`
	// Billing frequency used during the requested billing period
	BillingFrequency     *BillingFrequency `protobuf:"bytes,7,opt,name=billingFrequency,proto3" json:"billingFrequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetBillingDetailsResp) Reset()         { *m = GetBillingDetailsResp{} }
func (m *GetBillingDetailsResp) String() string { return proto.CompactTextString(m) }
func (*GetBillingDetailsResp) ProtoMessage()    {}
func (*GetBillingDetailsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{1}
}

func (m *GetBillingDetailsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillingDetailsResp.Unmarshal(m, b)
}
func (m *GetBillingDetailsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillingDetailsResp.Marshal(b, m, deterministic)
}
func (m *GetBillingDetailsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillingDetailsResp.Merge(m, src)
}
func (m *GetBillingDetailsResp) XXX_Size() int {
	return xxx_messageInfo_GetBillingDetailsResp.Size(m)
}
func (m *GetBillingDetailsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillingDetailsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillingDetailsResp proto.InternalMessageInfo

func (m *GetBillingDetailsResp) GetPeriodStart() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodStart
	}
	return nil
}

func (m *GetBillingDetailsResp) GetPeriodEnd() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodEnd
	}
	return nil
}

func (m *GetBillingDetailsResp) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *GetBillingDetailsResp) GetDocuments() *DocumentCosts {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *GetBillingDetailsResp) GetSearch() *SearchCosts {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *GetBillingDetailsResp) GetTraffic() *TrafficCosts {
	if m != nil {
		return m.Traffic
	}
	return nil
}

func (m *GetBillingDetailsResp) GetBillingFrequency() *BillingFrequency {
	if m != nil {
		return m.BillingFrequency
	}
	return nil
}

type GetBillingFrequencyListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBillingFrequencyListReq) Reset()         { *m = GetBillingFrequencyListReq{} }
func (m *GetBillingFrequencyListReq) String() string { return proto.CompactTextString(m) }
func (*GetBillingFrequencyListReq) ProtoMessage()    {}
func (*GetBillingFrequencyListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{2}
}

func (m *GetBillingFrequencyListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillingFrequencyListReq.Unmarshal(m, b)
}
func (m *GetBillingFrequencyListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillingFrequencyListReq.Marshal(b, m, deterministic)
}
func (m *GetBillingFrequencyListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillingFrequencyListReq.Merge(m, src)
}
func (m *GetBillingFrequencyListReq) XXX_Size() int {
	return xxx_messageInfo_GetBillingFrequencyListReq.Size(m)
}
func (m *GetBillingFrequencyListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillingFrequencyListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillingFrequencyListReq proto.InternalMessageInfo

type GetBillingFrequencyListResp struct {
	// List of billing frequencies
	BillingFrequencyList []*BillingFrequency `protobuf:"bytes,1,rep,name=billingFrequencyList,proto3" json:"billingFrequencyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetBillingFrequencyListResp) Reset()         { *m = GetBillingFrequencyListResp{} }
func (m *GetBillingFrequencyListResp) String() string { return proto.CompactTextString(m) }
func (*GetBillingFrequencyListResp) ProtoMessage()    {}
func (*GetBillingFrequencyListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{3}
}

func (m *GetBillingFrequencyListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillingFrequencyListResp.Unmarshal(m, b)
}
func (m *GetBillingFrequencyListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillingFrequencyListResp.Marshal(b, m, deterministic)
}
func (m *GetBillingFrequencyListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillingFrequencyListResp.Merge(m, src)
}
func (m *GetBillingFrequencyListResp) XXX_Size() int {
	return xxx_messageInfo_GetBillingFrequencyListResp.Size(m)
}
func (m *GetBillingFrequencyListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillingFrequencyListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillingFrequencyListResp proto.InternalMessageInfo

func (m *GetBillingFrequencyListResp) GetBillingFrequencyList() []*BillingFrequency {
	if m != nil {
		return m.BillingFrequencyList
	}
	return nil
}

type SetNextBillingFrequencyReq struct {
	// Billing frequency
	Frequency TimeInterval `protobuf:"varint,1,opt,name=frequency,proto3,enum=proto.TimeInterval" json:"frequency,omitempty"`
	// When this billing frequency becomes valid
	ValidFrom            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=validFrom,proto3" json:"validFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetNextBillingFrequencyReq) Reset()         { *m = SetNextBillingFrequencyReq{} }
func (m *SetNextBillingFrequencyReq) String() string { return proto.CompactTextString(m) }
func (*SetNextBillingFrequencyReq) ProtoMessage()    {}
func (*SetNextBillingFrequencyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{4}
}

func (m *SetNextBillingFrequencyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNextBillingFrequencyReq.Unmarshal(m, b)
}
func (m *SetNextBillingFrequencyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNextBillingFrequencyReq.Marshal(b, m, deterministic)
}
func (m *SetNextBillingFrequencyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNextBillingFrequencyReq.Merge(m, src)
}
func (m *SetNextBillingFrequencyReq) XXX_Size() int {
	return xxx_messageInfo_SetNextBillingFrequencyReq.Size(m)
}
func (m *SetNextBillingFrequencyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNextBillingFrequencyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetNextBillingFrequencyReq proto.InternalMessageInfo

func (m *SetNextBillingFrequencyReq) GetFrequency() TimeInterval {
	if m != nil {
		return m.Frequency
	}
	return TimeInterval_UNDEFINED
}

func (m *SetNextBillingFrequencyReq) GetValidFrom() *timestamp.Timestamp {
	if m != nil {
		return m.ValidFrom
	}
	return nil
}

type SetNextBillingFrequencyResp struct {
	// Next billing frequency
	NextBillingFrequency *BillingFrequency `protobuf:"bytes,1,opt,name=nextBillingFrequency,proto3" json:"nextBillingFrequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetNextBillingFrequencyResp) Reset()         { *m = SetNextBillingFrequencyResp{} }
func (m *SetNextBillingFrequencyResp) String() string { return proto.CompactTextString(m) }
func (*SetNextBillingFrequencyResp) ProtoMessage()    {}
func (*SetNextBillingFrequencyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{5}
}

func (m *SetNextBillingFrequencyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNextBillingFrequencyResp.Unmarshal(m, b)
}
func (m *SetNextBillingFrequencyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNextBillingFrequencyResp.Marshal(b, m, deterministic)
}
func (m *SetNextBillingFrequencyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNextBillingFrequencyResp.Merge(m, src)
}
func (m *SetNextBillingFrequencyResp) XXX_Size() int {
	return xxx_messageInfo_SetNextBillingFrequencyResp.Size(m)
}
func (m *SetNextBillingFrequencyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNextBillingFrequencyResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetNextBillingFrequencyResp proto.InternalMessageInfo

func (m *SetNextBillingFrequencyResp) GetNextBillingFrequency() *BillingFrequency {
	if m != nil {
		return m.NextBillingFrequency
	}
	return nil
}

type GetLargeTrafficReq struct {
	// Timestamp of the requested traffic information
	At                   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetLargeTrafficReq) Reset()         { *m = GetLargeTrafficReq{} }
func (m *GetLargeTrafficReq) String() string { return proto.CompactTextString(m) }
func (*GetLargeTrafficReq) ProtoMessage()    {}
func (*GetLargeTrafficReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{6}
}

func (m *GetLargeTrafficReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLargeTrafficReq.Unmarshal(m, b)
}
func (m *GetLargeTrafficReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLargeTrafficReq.Marshal(b, m, deterministic)
}
func (m *GetLargeTrafficReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLargeTrafficReq.Merge(m, src)
}
func (m *GetLargeTrafficReq) XXX_Size() int {
	return xxx_messageInfo_GetLargeTrafficReq.Size(m)
}
func (m *GetLargeTrafficReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLargeTrafficReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLargeTrafficReq proto.InternalMessageInfo

func (m *GetLargeTrafficReq) GetAt() *timestamp.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

type GetLargeTrafficResp struct {
	// Details of large traffic events
	LargeTraffic []*TrafficDetail `protobuf:"bytes,1,rep,name=largeTraffic,proto3" json:"largeTraffic,omitempty"`
	// Start of the requested billing period
	PeriodStart *timestamp.Timestamp `protobuf:"bytes,2,opt,name=periodStart,proto3" json:"periodStart,omitempty"`
	// End of the requested billing period
	PeriodEnd            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=periodEnd,proto3" json:"periodEnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetLargeTrafficResp) Reset()         { *m = GetLargeTrafficResp{} }
func (m *GetLargeTrafficResp) String() string { return proto.CompactTextString(m) }
func (*GetLargeTrafficResp) ProtoMessage()    {}
func (*GetLargeTrafficResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{7}
}

func (m *GetLargeTrafficResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLargeTrafficResp.Unmarshal(m, b)
}
func (m *GetLargeTrafficResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLargeTrafficResp.Marshal(b, m, deterministic)
}
func (m *GetLargeTrafficResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLargeTrafficResp.Merge(m, src)
}
func (m *GetLargeTrafficResp) XXX_Size() int {
	return xxx_messageInfo_GetLargeTrafficResp.Size(m)
}
func (m *GetLargeTrafficResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLargeTrafficResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLargeTrafficResp proto.InternalMessageInfo

func (m *GetLargeTrafficResp) GetLargeTraffic() []*TrafficDetail {
	if m != nil {
		return m.LargeTraffic
	}
	return nil
}

func (m *GetLargeTrafficResp) GetPeriodStart() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodStart
	}
	return nil
}

func (m *GetLargeTrafficResp) GetPeriodEnd() *timestamp.Timestamp {
	if m != nil {
		return m.PeriodEnd
	}
	return nil
}

type TrafficDetail struct {
	// Timestamp of the large traffic event
	Time *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// The ID of the user who made the request
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	// HTTP method of the request
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// URI called by the request
	URI string `protobuf:"bytes,4,opt,name=URI,proto3" json:"URI,omitempty"`
	// Size of the request (in MB)
	Incoming float64 `protobuf:"fixed64,5,opt,name=incoming,proto3" json:"incoming,omitempty"`
	// Size of the response (in MB)
	Outgoing             float64  `protobuf:"fixed64,6,opt,name=outgoing,proto3" json:"outgoing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficDetail) Reset()         { *m = TrafficDetail{} }
func (m *TrafficDetail) String() string { return proto.CompactTextString(m) }
func (*TrafficDetail) ProtoMessage()    {}
func (*TrafficDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{8}
}

func (m *TrafficDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficDetail.Unmarshal(m, b)
}
func (m *TrafficDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficDetail.Marshal(b, m, deterministic)
}
func (m *TrafficDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficDetail.Merge(m, src)
}
func (m *TrafficDetail) XXX_Size() int {
	return xxx_messageInfo_TrafficDetail.Size(m)
}
func (m *TrafficDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficDetail proto.InternalMessageInfo

func (m *TrafficDetail) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *TrafficDetail) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *TrafficDetail) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TrafficDetail) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *TrafficDetail) GetIncoming() float64 {
	if m != nil {
		return m.Incoming
	}
	return 0
}

func (m *TrafficDetail) GetOutgoing() float64 {
	if m != nil {
		return m.Outgoing
	}
	return 0
}

type BillingFrequency struct {
	// Billing frequency
	Frequency TimeInterval `protobuf:"varint,1,opt,name=frequency,proto3,enum=proto.TimeInterval" json:"frequency,omitempty"`
	// Start fo billing frequency validity
	ValidFrom *timestamp.Timestamp `protobuf:"bytes,2,opt,name=validFrom,proto3" json:"validFrom,omitempty"`
	// End of billing frequency validity
	ValidTo              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=validTo,proto3" json:"validTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BillingFrequency) Reset()         { *m = BillingFrequency{} }
func (m *BillingFrequency) String() string { return proto.CompactTextString(m) }
func (*BillingFrequency) ProtoMessage()    {}
func (*BillingFrequency) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{9}
}

func (m *BillingFrequency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillingFrequency.Unmarshal(m, b)
}
func (m *BillingFrequency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillingFrequency.Marshal(b, m, deterministic)
}
func (m *BillingFrequency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillingFrequency.Merge(m, src)
}
func (m *BillingFrequency) XXX_Size() int {
	return xxx_messageInfo_BillingFrequency.Size(m)
}
func (m *BillingFrequency) XXX_DiscardUnknown() {
	xxx_messageInfo_BillingFrequency.DiscardUnknown(m)
}

var xxx_messageInfo_BillingFrequency proto.InternalMessageInfo

func (m *BillingFrequency) GetFrequency() TimeInterval {
	if m != nil {
		return m.Frequency
	}
	return TimeInterval_UNDEFINED
}

func (m *BillingFrequency) GetValidFrom() *timestamp.Timestamp {
	if m != nil {
		return m.ValidFrom
	}
	return nil
}

func (m *BillingFrequency) GetValidTo() *timestamp.Timestamp {
	if m != nil {
		return m.ValidTo
	}
	return nil
}

type DocumentCosts struct {
	// Cost of document storage incurred during a billing period
	Cost float64 `protobuf:"fixed64,1,opt,name=cost,proto3" json:"cost,omitempty"`
	// Size of documents stored during a billing period (in MBhours)
	Size float64 `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	// Cost tier reached for document storage during a billing period
	Tier                 string   `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentCosts) Reset()         { *m = DocumentCosts{} }
func (m *DocumentCosts) String() string { return proto.CompactTextString(m) }
func (*DocumentCosts) ProtoMessage()    {}
func (*DocumentCosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{10}
}

func (m *DocumentCosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentCosts.Unmarshal(m, b)
}
func (m *DocumentCosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentCosts.Marshal(b, m, deterministic)
}
func (m *DocumentCosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentCosts.Merge(m, src)
}
func (m *DocumentCosts) XXX_Size() int {
	return xxx_messageInfo_DocumentCosts.Size(m)
}
func (m *DocumentCosts) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentCosts.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentCosts proto.InternalMessageInfo

func (m *DocumentCosts) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *DocumentCosts) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DocumentCosts) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

type SearchCosts struct {
	// Cost of search index storage incurred during a billing period
	Cost float64 `protobuf:"fixed64,1,opt,name=cost,proto3" json:"cost,omitempty"`
	// Size of search indices stored during a billing period (in MBhours)
	Size float64 `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	// Cost tier reached for search index storage during a billing period
	Tier                 string   `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchCosts) Reset()         { *m = SearchCosts{} }
func (m *SearchCosts) String() string { return proto.CompactTextString(m) }
func (*SearchCosts) ProtoMessage()    {}
func (*SearchCosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{11}
}

func (m *SearchCosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCosts.Unmarshal(m, b)
}
func (m *SearchCosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCosts.Marshal(b, m, deterministic)
}
func (m *SearchCosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCosts.Merge(m, src)
}
func (m *SearchCosts) XXX_Size() int {
	return xxx_messageInfo_SearchCosts.Size(m)
}
func (m *SearchCosts) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCosts.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCosts proto.InternalMessageInfo

func (m *SearchCosts) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *SearchCosts) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchCosts) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

type TrafficCosts struct {
	// Cost of network traffic incurred during a billing period
	Cost float64 `protobuf:"fixed64,1,opt,name=cost,proto3" json:"cost,omitempty"`
	// Size of incoming requests during a billing period (in MB)
	Incoming float64 `protobuf:"fixed64,2,opt,name=incoming,proto3" json:"incoming,omitempty"`
	// Size of outgoing requests during a billing period (in MB)
	Outgoing float64 `protobuf:"fixed64,3,opt,name=outgoing,proto3" json:"outgoing,omitempty"`
	// Cost tier reached for network traffic during a billing period
	Tier                 string   `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficCosts) Reset()         { *m = TrafficCosts{} }
func (m *TrafficCosts) String() string { return proto.CompactTextString(m) }
func (*TrafficCosts) ProtoMessage()    {}
func (*TrafficCosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{12}
}

func (m *TrafficCosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficCosts.Unmarshal(m, b)
}
func (m *TrafficCosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficCosts.Marshal(b, m, deterministic)
}
func (m *TrafficCosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficCosts.Merge(m, src)
}
func (m *TrafficCosts) XXX_Size() int {
	return xxx_messageInfo_TrafficCosts.Size(m)
}
func (m *TrafficCosts) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficCosts.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficCosts proto.InternalMessageInfo

func (m *TrafficCosts) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *TrafficCosts) GetIncoming() float64 {
	if m != nil {
		return m.Incoming
	}
	return 0
}

func (m *TrafficCosts) GetOutgoing() float64 {
	if m != nil {
		return m.Outgoing
	}
	return 0
}

func (m *TrafficCosts) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.TimeInterval", TimeInterval_name, TimeInterval_value)
	proto.RegisterType((*GetBillingDetailsReq)(nil), "proto.GetBillingDetailsReq")
	proto.RegisterType((*GetBillingDetailsResp)(nil), "proto.GetBillingDetailsResp")
	proto.RegisterType((*GetBillingFrequencyListReq)(nil), "proto.GetBillingFrequencyListReq")
	proto.RegisterType((*GetBillingFrequencyListResp)(nil), "proto.GetBillingFrequencyListResp")
	proto.RegisterType((*SetNextBillingFrequencyReq)(nil), "proto.SetNextBillingFrequencyReq")
	proto.RegisterType((*SetNextBillingFrequencyResp)(nil), "proto.SetNextBillingFrequencyResp")
	proto.RegisterType((*GetLargeTrafficReq)(nil), "proto.GetLargeTrafficReq")
	proto.RegisterType((*GetLargeTrafficResp)(nil), "proto.GetLargeTrafficResp")
	proto.RegisterType((*TrafficDetail)(nil), "proto.TrafficDetail")
	proto.RegisterType((*BillingFrequency)(nil), "proto.BillingFrequency")
	proto.RegisterType((*DocumentCosts)(nil), "proto.DocumentCosts")
	proto.RegisterType((*SearchCosts)(nil), "proto.SearchCosts")
	proto.RegisterType((*TrafficCosts)(nil), "proto.TrafficCosts")
}

func init() { proto.RegisterFile("billing.proto", fileDescriptor_958db8ba491a6b57) }

var fileDescriptor_958db8ba491a6b57 = []byte{
	// 1268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcb, 0x6f, 0x1b, 0x45,
	0x18, 0x67, 0xbd, 0x69, 0x82, 0x27, 0x4d, 0x65, 0x4d, 0x53, 0x6a, 0xa5, 0x45, 0xac, 0xe6, 0x54,
	0x59, 0xce, 0x7a, 0x76, 0xfc, 0x60, 0xb3, 0xe2, 0x50, 0xa7, 0x4e, 0x4a, 0x44, 0x1a, 0xa4, 0x8d,
	0xa3, 0xd2, 0x56, 0x11, 0xda, 0xac, 0x27, 0xee, 0xaa, 0xf6, 0x8e, 0xbb, 0x3b, 0xe9, 0x83, 0x60,
	0x1e, 0x12, 0x07, 0x6e, 0x48, 0xfe, 0x1f, 0x90, 0x38, 0x70, 0xe0, 0x84, 0xc4, 0x15, 0x89, 0xff,
	0x82, 0x0b, 0x07, 0x0e, 0x5c, 0x90, 0xb8, 0x72, 0x42, 0x33, 0xbb, 0x5e, 0xaf, 0x9d, 0x6d, 0x48,
	0x94, 0x82, 0x64, 0xc9, 0xf3, 0x7d, 0xfb, 0xfb, 0x1e, 0xf3, 0xbd, 0xe6, 0x03, 0x4b, 0x07, 0x5e,
	0xaf, 0xe7, 0xf9, 0x5d, 0x7d, 0x10, 0x30, 0xce, 0xe0, 0x25, 0xf9, 0xb7, 0xf2, 0x4e, 0x97, 0xb1,
	0x6e, 0x8f, 0x56, 0x24, 0x75, 0x70, 0x74, 0x58, 0xe1, 0x5e, 0x9f, 0x86, 0xdc, 0xe9, 0x0f, 0x22,
	0xdc, 0x4a, 0x59, 0xfe, 0xb9, 0xab, 0x5d, 0xea, 0xaf, 0x86, 0xcf, 0x9d, 0x6e, 0x97, 0x06, 0x15,
	0x36, 0xe0, 0x1e, 0xf3, 0xc3, 0x8a, 0xe3, 0xfb, 0x8c, 0x3b, 0xf2, 0x1c, 0xa1, 0xd1, 0x3a, 0x58,
	0xbe, 0x4b, 0xf9, 0x7a, 0x64, 0xa9, 0x45, 0xb9, 0xe3, 0xf5, 0x42, 0x9b, 0x3e, 0x85, 0x25, 0x90,
	0x73, 0x78, 0x51, 0xd1, 0x94, 0x5b, 0x8b, 0x64, 0x45, 0x8f, 0x6c, 0xea, 0x63, 0x9b, 0x7a, 0x7b,
	0x6c, 0xd3, 0xce, 0x39, 0x1c, 0xfd, 0x31, 0x0f, 0xae, 0x65, 0x28, 0x09, 0x07, 0xf0, 0x3d, 0xb0,
	0x38, 0xa0, 0x81, 0xc7, 0x3a, 0xbb, 0xdc, 0x09, 0xce, 0xa2, 0x2e, 0x0d, 0x87, 0x26, 0xc8, 0x47,
	0xe4, 0x86, 0xdf, 0x29, 0xe6, 0xfe, 0x55, 0x76, 0x02, 0x86, 0x37, 0x41, 0x9e, 0x33, 0xee, 0xf4,
	0xee, 0xb0, 0x90, 0x17, 0x55, 0x4d, 0xb9, 0xa5, 0xd8, 0x13, 0x06, 0x24, 0x20, 0xdf, 0x61, 0xee,
	0x51, 0x9f, 0xfa, 0x3c, 0x2c, 0xce, 0x49, 0xbd, 0xcb, 0x91, 0x42, 0xbd, 0x15, 0xf3, 0x05, 0x2e,
	0xb4, 0x27, 0x30, 0x58, 0x02, 0xf3, 0x21, 0x75, 0x02, 0xf7, 0x71, 0xf1, 0x92, 0x14, 0x80, 0xb1,
	0xc0, 0xae, 0x64, 0x46, 0xf0, 0x18, 0x01, 0x57, 0xc1, 0x02, 0x0f, 0x9c, 0xc3, 0x43, 0xcf, 0x2d,
	0xce, 0x4b, 0xf0, 0xd5, 0x18, 0xdc, 0x8e, 0xb8, 0x11, 0x7a, 0x8c, 0x81, 0x77, 0x40, 0x21, 0xce,
	0xf4, 0x66, 0x40, 0x9f, 0x1e, 0x51, 0xdf, 0x7d, 0x59, 0x5c, 0x90, 0x72, 0xd7, 0x63, 0xb9, 0xf5,
	0x99, 0xcf, 0xf6, 0x09, 0x01, 0xeb, 0x77, 0x75, 0xd4, 0xfc, 0x4d, 0x05, 0xd7, 0x4b, 0xd9, 0x99,
	0x20, 0xbf, 0xa8, 0xf0, 0x67, 0xf5, 0x18, 0xa5, 0xc2, 0x8b, 0x2c, 0x0d, 0x11, 0x4c, 0xf0, 0x2a,
	0x26, 0xab, 0x06, 0x6e, 0x1b, 0xc4, 0xaa, 0x62, 0xcb, 0xa8, 0xeb, 0x06, 0xa9, 0x3e, 0x44, 0x65,
	0x0d, 0x25, 0xd1, 0x9c, 0x00, 0xab, 0xab, 0xd8, 0x68, 0x63, 0x6c, 0xc9, 0x9f, 0x04, 0x25, 0x41,
	0x45, 0x96, 0x66, 0x62, 0x5c, 0xaf, 0x99, 0x3a, 0xc6, 0x65, 0x0d, 0x25, 0x81, 0x43, 0x96, 0x76,
	0x8c, 0xdc, 0x08, 0x60, 0x34, 0x74, 0x6c, 0x96, 0x35, 0x14, 0x7a, 0x9f, 0x50, 0x41, 0xd6, 0x4c,
	0x63, 0xad, 0x4a, 0x4c, 0x81, 0xe7, 0x1e, 0x0d, 0x84, 0x9d, 0x71, 0xfc, 0xb5, 0x5d, 0xce, 0x02,
	0xa7, 0x4b, 0xb5, 0x7b, 0x5e, 0x07, 0x0d, 0x85, 0x8c, 0x0c, 0x6d, 0x5a, 0x1b, 0x89, 0x2c, 0xc5,
	0xca, 0xea, 0xe6, 0x9a, 0x49, 0x6a, 0x38, 0xad, 0x2b, 0x4a, 0x8d, 0xb6, 0xe5, 0x77, 0xe8, 0x8b,
	0x44, 0xdf, 0x36, 0x7b, 0x2e, 0xf5, 0xc5, 0xc1, 0x4f, 0x2b, 0x14, 0xb2, 0x9e, 0xef, 0xb2, 0xbe,
	0xe7, 0x77, 0x85, 0x46, 0x8c, 0xf5, 0x5a, 0xbd, 0x51, 0xd6, 0x10, 0x3b, 0xe2, 0x5d, 0x16, 0x31,
	0x09, 0xc6, 0x7a, 0xbd, 0x51, 0x4b, 0x59, 0xd9, 0xa1, 0xfc, 0x39, 0x0b, 0x9e, 0x68, 0x71, 0x6e,
	0xb5, 0xcd, 0x80, 0x52, 0x69, 0x61, 0x36, 0x45, 0xd2, 0xd4, 0x61, 0x8a, 0x42, 0xf7, 0x3e, 0xdc,
	0x69, 0xbf, 0xbf, 0xfd, 0x40, 0xc4, 0xf1, 0x99, 0xd3, 0xf3, 0x3a, 0x9b, 0x01, 0xeb, 0x9f, 0x9a,
	0x95, 0xe1, 0x10, 0xdd, 0x04, 0x2b, 0x93, 0x04, 0x27, 0xba, 0xb7, 0xbd, 0x90, 0xdb, 0xf4, 0x29,
	0xfa, 0x4b, 0x01, 0x37, 0x5e, 0xf9, 0x39, 0x1c, 0xc0, 0x0f, 0xc0, 0xf2, 0x41, 0xc6, 0xb7, 0xa2,
	0xa2, 0xa9, 0xa7, 0x95, 0x5b, 0xa6, 0x90, 0xf5, 0x95, 0x32, 0x6a, 0x7e, 0xa1, 0x80, 0xb7, 0x4b,
	0xa7, 0x99, 0x24, 0x1f, 0xc3, 0xfd, 0x63, 0x94, 0x25, 0x8f, 0x2c, 0xed, 0xd1, 0x85, 0x03, 0xb2,
	0x3f, 0x14, 0x77, 0x5e, 0xd9, 0xa5, 0x7c, 0x87, 0xbe, 0x38, 0xe1, 0x84, 0x18, 0x64, 0x06, 0xc8,
	0x27, 0x36, 0xe4, 0x00, 0xba, 0x32, 0x69, 0x47, 0xaf, 0x4f, 0xb7, 0x7c, 0x4e, 0x83, 0x67, 0x4e,
	0xcf, 0x9e, 0xa0, 0xc4, 0xdc, 0x49, 0xcc, 0x9f, 0x65, 0xee, 0x24, 0x60, 0xeb, 0x70, 0xd4, 0x74,
	0xc1, 0xcd, 0xd2, 0x29, 0xfe, 0x90, 0x3b, 0xb0, 0x79, 0xe1, 0x5b, 0xa3, 0x3f, 0x15, 0x70, 0xe3,
	0x95, 0x36, 0xa2, 0x3c, 0xfb, 0x19, 0xdf, 0xe2, 0x01, 0xfc, 0xea, 0x3c, 0x67, 0x09, 0x59, 0x5f,
	0x2a, 0xa3, 0xe6, 0x67, 0x22, 0xcd, 0xa7, 0x58, 0x24, 0xfb, 0xf0, 0xd1, 0x31, 0xca, 0x12, 0x7f,
	0x3d, 0x65, 0x7f, 0x1b, 0xc0, 0xbb, 0x94, 0x6f, 0x3b, 0x41, 0x97, 0xc6, 0x8d, 0x76, 0xde, 0x47,
	0xea, 0xef, 0x39, 0x70, 0xf5, 0x84, 0x8a, 0x70, 0x00, 0x4d, 0x70, 0xb9, 0x97, 0xe2, 0xc5, 0xad,
	0xb0, 0x3c, 0x3d, 0xb1, 0xa3, 0x49, 0x6a, 0x4f, 0x21, 0x67, 0x1f, 0xb7, 0xdc, 0x05, 0x1e, 0x37,
	0xf5, 0x1c, 0x8f, 0x9b, 0xf5, 0x83, 0x3a, 0x6a, 0x7e, 0xaf, 0x82, 0x6b, 0xa5, 0xac, 0xfb, 0x90,
	0x91, 0x0a, 0xbf, 0x51, 0x8f, 0x51, 0xda, 0xd3, 0xa8, 0xd3, 0xc4, 0x9e, 0x90, 0x1e, 0xe5, 0x04,
	0xb7, 0x0d, 0xc3, 0xc2, 0x75, 0xcb, 0x30, 0xf4, 0xb5, 0x7a, 0xc3, 0x34, 0xd7, 0x8c, 0x5a, 0xed,
	0x21, 0x2a, 0xa3, 0xa3, 0x90, 0x06, 0x5b, 0x2d, 0x01, 0x15, 0xa7, 0xdb, 0x2e, 0xeb, 0x0f, 0x1c,
	0xff, 0xa5, 0xee, 0xb2, 0x3e, 0x2a, 0xa3, 0x3e, 0xe5, 0x8f, 0x99, 0x7c, 0x12, 0xee, 0x6e, 0xb4,
	0x51, 0x19, 0xed, 0xd9, 0x5b, 0x82, 0xa8, 0x3c, 0x33, 0x2a, 0x8e, 0xeb, 0xb2, 0x23, 0x9f, 0x57,
	0xe2, 0x66, 0x47, 0xe5, 0xf4, 0x34, 0x35, 0x0d, 0x5c, 0x4e, 0x0f, 0xd2, 0xea, 0x1a, 0x19, 0x96,
	0xc7, 0x4e, 0xcd, 0xf8, 0x54, 0xc5, 0x56, 0xb5, 0xa6, 0x37, 0xaa, 0xb8, 0x5a, 0xad, 0x36, 0x0c,
	0xf3, 0xa4, 0x4f, 0xe4, 0xfc, 0x4e, 0x4d, 0xc5, 0x63, 0xc6, 0xb3, 0xc6, 0x94, 0x67, 0x6b, 0xf5,
	0xe1, 0x7e, 0x39, 0xfb, 0xa1, 0x4c, 0x82, 0x56, 0xb3, 0x6a, 0xef, 0xea, 0xc4, 0x10, 0x6f, 0x60,
	0xd6, 0x3b, 0x59, 0x9b, 0x7e, 0x27, 0x87, 0xe8, 0x27, 0x05, 0x2c, 0x4d, 0x95, 0x12, 0xd4, 0xc1,
	0x9c, 0xb8, 0xfb, 0x19, 0x8a, 0x57, 0xe2, 0xe0, 0x5b, 0x60, 0x3e, 0x8a, 0x81, 0xac, 0xb3, 0xbc,
	0x1d, 0x53, 0x82, 0x1f, 0xdd, 0x5e, 0xd6, 0x50, 0xde, 0x8e, 0x29, 0x58, 0x00, 0xea, 0x9e, 0xbd,
	0x25, 0xb7, 0x9b, 0xbc, 0x2d, 0x8e, 0x70, 0x05, 0xbc, 0x39, 0xbe, 0xb5, 0xdc, 0x61, 0x14, 0x3b,
	0xa1, 0xc5, 0xb7, 0x71, 0x04, 0xe4, 0xca, 0xa2, 0xd8, 0x09, 0x8d, 0x7e, 0xcc, 0x81, 0xc2, 0x6c,
	0x53, 0xff, 0xaf, 0x53, 0x15, 0xd6, 0xc0, 0x82, 0x24, 0xda, 0xec, 0x0c, 0x8d, 0x32, 0x86, 0x5a,
	0x9f, 0x8f, 0x9a, 0x9f, 0x02, 0x58, 0x3a, 0xe1, 0x3b, 0x39, 0x84, 0x9d, 0x73, 0x4d, 0xa4, 0xd4,
	0xd6, 0x93, 0x5a, 0x8f, 0x62, 0x33, 0x13, 0x58, 0x63, 0x36, 0xe9, 0xdf, 0x29, 0x60, 0x69, 0x6a,
	0x9f, 0x84, 0x10, 0xcc, 0x89, 0x5d, 0x43, 0x06, 0x4c, 0xb1, 0xe5, 0x59, 0xf0, 0xc4, 0x0a, 0x23,
	0x23, 0xa2, 0xd8, 0xf2, 0x2c, 0x78, 0x62, 0xbd, 0x88, 0x53, 0x2a, 0xcf, 0xd6, 0xa3, 0x51, 0xf3,
	0x23, 0x50, 0x28, 0x5d, 0x19, 0x6b, 0x0c, 0xa5, 0x4a, 0xd2, 0x82, 0xeb, 0x17, 0xdf, 0xaf, 0xd0,
	0xb7, 0x0a, 0x58, 0x4c, 0x6d, 0xb2, 0x17, 0x72, 0xf4, 0xe1, 0xa8, 0x79, 0x1f, 0x2c, 0x95, 0xd2,
	0xfa, 0xc8, 0x26, 0x6c, 0xbd, 0x8e, 0xbd, 0x0d, 0xfd, 0xaa, 0x80, 0xcb, 0xe9, 0x25, 0x3a, 0xd3,
	0xd1, 0x74, 0xa1, 0xe7, 0x4e, 0x29, 0x74, 0x75, 0xba, 0xd0, 0x93, 0xcb, 0xcc, 0xa5, 0x2e, 0xd3,
	0x1b, 0x35, 0x3d, 0x70, 0xa5, 0x34, 0x65, 0x94, 0xdc, 0x87, 0x7b, 0xff, 0xc9, 0xd2, 0x58, 0x6a,
	0x80, 0xcb, 0xe9, 0xee, 0x81, 0x4b, 0x20, 0xbf, 0xb7, 0xd3, 0xda, 0xd8, 0xdc, 0xda, 0xd9, 0x68,
	0x15, 0xde, 0x80, 0x8b, 0x60, 0x21, 0xae, 0xd4, 0x82, 0x02, 0x01, 0x98, 0x7f, 0xb0, 0xd1, 0xb4,
	0xb7, 0x1f, 0x14, 0x72, 0xeb, 0x18, 0x20, 0x97, 0xf5, 0xf5, 0x90, 0x07, 0xcc, 0xef, 0x86, 0x4e,
	0x8f, 0xc7, 0xc7, 0x0e, 0x73, 0xf5, 0xb0, 0xf3, 0x24, 0x6a, 0x93, 0xf5, 0x85, 0xb8, 0x13, 0xbe,
	0x56, 0x94, 0x83, 0x79, 0xc9, 0xaa, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x66, 0x8a, 0xf0,
	0x64, 0x0e, 0x00, 0x00,
}
