// Code generated by protoc-gen-go. DO NOT EDIT.
// source: document.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadDocStreamReq struct {
	// Types that are valid to be assigned to NameOrData:
	//	*UploadDocStreamReq_DocName
	//	*UploadDocStreamReq_Plaintext
	NameOrData           isUploadDocStreamReq_NameOrData `protobuf_oneof:"NameOrData"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UploadDocStreamReq) Reset()         { *m = UploadDocStreamReq{} }
func (m *UploadDocStreamReq) String() string { return proto.CompactTextString(m) }
func (*UploadDocStreamReq) ProtoMessage()    {}
func (*UploadDocStreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{0}
}

func (m *UploadDocStreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadDocStreamReq.Unmarshal(m, b)
}
func (m *UploadDocStreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadDocStreamReq.Marshal(b, m, deterministic)
}
func (m *UploadDocStreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadDocStreamReq.Merge(m, src)
}
func (m *UploadDocStreamReq) XXX_Size() int {
	return xxx_messageInfo_UploadDocStreamReq.Size(m)
}
func (m *UploadDocStreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadDocStreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadDocStreamReq proto.InternalMessageInfo

type isUploadDocStreamReq_NameOrData interface {
	isUploadDocStreamReq_NameOrData()
}

type UploadDocStreamReq_DocName struct {
	DocName string `protobuf:"bytes,1,opt,name=docName,proto3,oneof"`
}

type UploadDocStreamReq_Plaintext struct {
	Plaintext []byte `protobuf:"bytes,2,opt,name=plaintext,proto3,oneof"`
}

func (*UploadDocStreamReq_DocName) isUploadDocStreamReq_NameOrData() {}

func (*UploadDocStreamReq_Plaintext) isUploadDocStreamReq_NameOrData() {}

func (m *UploadDocStreamReq) GetNameOrData() isUploadDocStreamReq_NameOrData {
	if m != nil {
		return m.NameOrData
	}
	return nil
}

func (m *UploadDocStreamReq) GetDocName() string {
	if x, ok := m.GetNameOrData().(*UploadDocStreamReq_DocName); ok {
		return x.DocName
	}
	return ""
}

func (m *UploadDocStreamReq) GetPlaintext() []byte {
	if x, ok := m.GetNameOrData().(*UploadDocStreamReq_Plaintext); ok {
		return x.Plaintext
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UploadDocStreamReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UploadDocStreamReq_DocName)(nil),
		(*UploadDocStreamReq_Plaintext)(nil),
	}
}

type UploadDocStreamResp struct {
	// The ID of the newly uploaded document.
	DocID string `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	// The number of bytes uploaded and stored.
	Bytes                int64    `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadDocStreamResp) Reset()         { *m = UploadDocStreamResp{} }
func (m *UploadDocStreamResp) String() string { return proto.CompactTextString(m) }
func (*UploadDocStreamResp) ProtoMessage()    {}
func (*UploadDocStreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{1}
}

func (m *UploadDocStreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadDocStreamResp.Unmarshal(m, b)
}
func (m *UploadDocStreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadDocStreamResp.Marshal(b, m, deterministic)
}
func (m *UploadDocStreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadDocStreamResp.Merge(m, src)
}
func (m *UploadDocStreamResp) XXX_Size() int {
	return xxx_messageInfo_UploadDocStreamResp.Size(m)
}
func (m *UploadDocStreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadDocStreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadDocStreamResp proto.InternalMessageInfo

func (m *UploadDocStreamResp) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *UploadDocStreamResp) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

type E2EEUploadDocStreamReq struct {
	// Types that are valid to be assigned to StageData:
	//	*E2EEUploadDocStreamReq_PreMetaData
	//	*E2EEUploadDocStreamReq_EncDocKeys
	//	*E2EEUploadDocStreamReq_CipherText
	//	*E2EEUploadDocStreamReq_PostMetaData
	StageData            isE2EEUploadDocStreamReq_StageData `protobuf_oneof:"stageData"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *E2EEUploadDocStreamReq) Reset()         { *m = E2EEUploadDocStreamReq{} }
func (m *E2EEUploadDocStreamReq) String() string { return proto.CompactTextString(m) }
func (*E2EEUploadDocStreamReq) ProtoMessage()    {}
func (*E2EEUploadDocStreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{2}
}

func (m *E2EEUploadDocStreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEUploadDocStreamReq.Unmarshal(m, b)
}
func (m *E2EEUploadDocStreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEUploadDocStreamReq.Marshal(b, m, deterministic)
}
func (m *E2EEUploadDocStreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEUploadDocStreamReq.Merge(m, src)
}
func (m *E2EEUploadDocStreamReq) XXX_Size() int {
	return xxx_messageInfo_E2EEUploadDocStreamReq.Size(m)
}
func (m *E2EEUploadDocStreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEUploadDocStreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEUploadDocStreamReq proto.InternalMessageInfo

type isE2EEUploadDocStreamReq_StageData interface {
	isE2EEUploadDocStreamReq_StageData()
}

type E2EEUploadDocStreamReq_PreMetaData struct {
	PreMetaData *E2EEUploadDocStreamReq_PreMetaDataType `protobuf:"bytes,1,opt,name=preMetaData,proto3,oneof"`
}

type E2EEUploadDocStreamReq_EncDocKeys struct {
	EncDocKeys *E2EEUploadDocStreamReq_EncKeyList `protobuf:"bytes,2,opt,name=encDocKeys,proto3,oneof"`
}

type E2EEUploadDocStreamReq_CipherText struct {
	CipherText []byte `protobuf:"bytes,3,opt,name=cipherText,proto3,oneof"`
}

type E2EEUploadDocStreamReq_PostMetaData struct {
	PostMetaData *E2EEUploadDocStreamReq_PostMetaDataType `protobuf:"bytes,4,opt,name=postMetaData,proto3,oneof"`
}

func (*E2EEUploadDocStreamReq_PreMetaData) isE2EEUploadDocStreamReq_StageData() {}

func (*E2EEUploadDocStreamReq_EncDocKeys) isE2EEUploadDocStreamReq_StageData() {}

func (*E2EEUploadDocStreamReq_CipherText) isE2EEUploadDocStreamReq_StageData() {}

func (*E2EEUploadDocStreamReq_PostMetaData) isE2EEUploadDocStreamReq_StageData() {}

func (m *E2EEUploadDocStreamReq) GetStageData() isE2EEUploadDocStreamReq_StageData {
	if m != nil {
		return m.StageData
	}
	return nil
}

func (m *E2EEUploadDocStreamReq) GetPreMetaData() *E2EEUploadDocStreamReq_PreMetaDataType {
	if x, ok := m.GetStageData().(*E2EEUploadDocStreamReq_PreMetaData); ok {
		return x.PreMetaData
	}
	return nil
}

func (m *E2EEUploadDocStreamReq) GetEncDocKeys() *E2EEUploadDocStreamReq_EncKeyList {
	if x, ok := m.GetStageData().(*E2EEUploadDocStreamReq_EncDocKeys); ok {
		return x.EncDocKeys
	}
	return nil
}

func (m *E2EEUploadDocStreamReq) GetCipherText() []byte {
	if x, ok := m.GetStageData().(*E2EEUploadDocStreamReq_CipherText); ok {
		return x.CipherText
	}
	return nil
}

func (m *E2EEUploadDocStreamReq) GetPostMetaData() *E2EEUploadDocStreamReq_PostMetaDataType {
	if x, ok := m.GetStageData().(*E2EEUploadDocStreamReq_PostMetaData); ok {
		return x.PostMetaData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*E2EEUploadDocStreamReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*E2EEUploadDocStreamReq_PreMetaData)(nil),
		(*E2EEUploadDocStreamReq_EncDocKeys)(nil),
		(*E2EEUploadDocStreamReq_CipherText)(nil),
		(*E2EEUploadDocStreamReq_PostMetaData)(nil),
	}
}

type E2EEUploadDocStreamReq_PreMetaDataType struct {
	DocName              string   `protobuf:"bytes,1,opt,name=docName,proto3" json:"docName,omitempty"`
	IsEncryptedByClient  bool     `protobuf:"varint,2,opt,name=isEncryptedByClient,proto3" json:"isEncryptedByClient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *E2EEUploadDocStreamReq_PreMetaDataType) Reset() {
	*m = E2EEUploadDocStreamReq_PreMetaDataType{}
}
func (m *E2EEUploadDocStreamReq_PreMetaDataType) String() string { return proto.CompactTextString(m) }
func (*E2EEUploadDocStreamReq_PreMetaDataType) ProtoMessage()    {}
func (*E2EEUploadDocStreamReq_PreMetaDataType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{2, 0}
}

func (m *E2EEUploadDocStreamReq_PreMetaDataType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEUploadDocStreamReq_PreMetaDataType.Unmarshal(m, b)
}
func (m *E2EEUploadDocStreamReq_PreMetaDataType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEUploadDocStreamReq_PreMetaDataType.Marshal(b, m, deterministic)
}
func (m *E2EEUploadDocStreamReq_PreMetaDataType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEUploadDocStreamReq_PreMetaDataType.Merge(m, src)
}
func (m *E2EEUploadDocStreamReq_PreMetaDataType) XXX_Size() int {
	return xxx_messageInfo_E2EEUploadDocStreamReq_PreMetaDataType.Size(m)
}
func (m *E2EEUploadDocStreamReq_PreMetaDataType) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEUploadDocStreamReq_PreMetaDataType.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEUploadDocStreamReq_PreMetaDataType proto.InternalMessageInfo

func (m *E2EEUploadDocStreamReq_PreMetaDataType) GetDocName() string {
	if m != nil {
		return m.DocName
	}
	return ""
}

func (m *E2EEUploadDocStreamReq_PreMetaDataType) GetIsEncryptedByClient() bool {
	if m != nil {
		return m.IsEncryptedByClient
	}
	return false
}

type E2EEUploadDocStreamReq_PostMetaDataType struct {
	MacOfCipherText      string   `protobuf:"bytes,1,opt,name=macOfCipherText,proto3" json:"macOfCipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *E2EEUploadDocStreamReq_PostMetaDataType) Reset() {
	*m = E2EEUploadDocStreamReq_PostMetaDataType{}
}
func (m *E2EEUploadDocStreamReq_PostMetaDataType) String() string { return proto.CompactTextString(m) }
func (*E2EEUploadDocStreamReq_PostMetaDataType) ProtoMessage()    {}
func (*E2EEUploadDocStreamReq_PostMetaDataType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{2, 1}
}

func (m *E2EEUploadDocStreamReq_PostMetaDataType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEUploadDocStreamReq_PostMetaDataType.Unmarshal(m, b)
}
func (m *E2EEUploadDocStreamReq_PostMetaDataType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEUploadDocStreamReq_PostMetaDataType.Marshal(b, m, deterministic)
}
func (m *E2EEUploadDocStreamReq_PostMetaDataType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEUploadDocStreamReq_PostMetaDataType.Merge(m, src)
}
func (m *E2EEUploadDocStreamReq_PostMetaDataType) XXX_Size() int {
	return xxx_messageInfo_E2EEUploadDocStreamReq_PostMetaDataType.Size(m)
}
func (m *E2EEUploadDocStreamReq_PostMetaDataType) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEUploadDocStreamReq_PostMetaDataType.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEUploadDocStreamReq_PostMetaDataType proto.InternalMessageInfo

func (m *E2EEUploadDocStreamReq_PostMetaDataType) GetMacOfCipherText() string {
	if m != nil {
		return m.MacOfCipherText
	}
	return ""
}

type E2EEUploadDocStreamReq_EncKeyList struct {
	EncDocKeys           []*EncryptedKey `protobuf:"bytes,1,rep,name=encDocKeys,proto3" json:"encDocKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *E2EEUploadDocStreamReq_EncKeyList) Reset()         { *m = E2EEUploadDocStreamReq_EncKeyList{} }
func (m *E2EEUploadDocStreamReq_EncKeyList) String() string { return proto.CompactTextString(m) }
func (*E2EEUploadDocStreamReq_EncKeyList) ProtoMessage()    {}
func (*E2EEUploadDocStreamReq_EncKeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{2, 2}
}

func (m *E2EEUploadDocStreamReq_EncKeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEUploadDocStreamReq_EncKeyList.Unmarshal(m, b)
}
func (m *E2EEUploadDocStreamReq_EncKeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEUploadDocStreamReq_EncKeyList.Marshal(b, m, deterministic)
}
func (m *E2EEUploadDocStreamReq_EncKeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEUploadDocStreamReq_EncKeyList.Merge(m, src)
}
func (m *E2EEUploadDocStreamReq_EncKeyList) XXX_Size() int {
	return xxx_messageInfo_E2EEUploadDocStreamReq_EncKeyList.Size(m)
}
func (m *E2EEUploadDocStreamReq_EncKeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEUploadDocStreamReq_EncKeyList.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEUploadDocStreamReq_EncKeyList proto.InternalMessageInfo

func (m *E2EEUploadDocStreamReq_EncKeyList) GetEncDocKeys() []*EncryptedKey {
	if m != nil {
		return m.EncDocKeys
	}
	return nil
}

type E2EEUploadDocStreamResp struct {
	// Types that are valid to be assigned to StageData:
	//	*E2EEUploadDocStreamResp_ReadyForData
	//	*E2EEUploadDocStreamResp_Encryptors
	//	*E2EEUploadDocStreamResp_DocID
	StageData            isE2EEUploadDocStreamResp_StageData `protobuf_oneof:"stageData"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *E2EEUploadDocStreamResp) Reset()         { *m = E2EEUploadDocStreamResp{} }
func (m *E2EEUploadDocStreamResp) String() string { return proto.CompactTextString(m) }
func (*E2EEUploadDocStreamResp) ProtoMessage()    {}
func (*E2EEUploadDocStreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{3}
}

func (m *E2EEUploadDocStreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEUploadDocStreamResp.Unmarshal(m, b)
}
func (m *E2EEUploadDocStreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEUploadDocStreamResp.Marshal(b, m, deterministic)
}
func (m *E2EEUploadDocStreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEUploadDocStreamResp.Merge(m, src)
}
func (m *E2EEUploadDocStreamResp) XXX_Size() int {
	return xxx_messageInfo_E2EEUploadDocStreamResp.Size(m)
}
func (m *E2EEUploadDocStreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEUploadDocStreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEUploadDocStreamResp proto.InternalMessageInfo

type isE2EEUploadDocStreamResp_StageData interface {
	isE2EEUploadDocStreamResp_StageData()
}

type E2EEUploadDocStreamResp_ReadyForData struct {
	ReadyForData bool `protobuf:"varint,1,opt,name=readyForData,proto3,oneof"`
}

type E2EEUploadDocStreamResp_Encryptors struct {
	Encryptors *E2EEUploadDocStreamResp_PubKeyList `protobuf:"bytes,2,opt,name=encryptors,proto3,oneof"`
}

type E2EEUploadDocStreamResp_DocID struct {
	DocID string `protobuf:"bytes,3,opt,name=docID,proto3,oneof"`
}

func (*E2EEUploadDocStreamResp_ReadyForData) isE2EEUploadDocStreamResp_StageData() {}

func (*E2EEUploadDocStreamResp_Encryptors) isE2EEUploadDocStreamResp_StageData() {}

func (*E2EEUploadDocStreamResp_DocID) isE2EEUploadDocStreamResp_StageData() {}

func (m *E2EEUploadDocStreamResp) GetStageData() isE2EEUploadDocStreamResp_StageData {
	if m != nil {
		return m.StageData
	}
	return nil
}

func (m *E2EEUploadDocStreamResp) GetReadyForData() bool {
	if x, ok := m.GetStageData().(*E2EEUploadDocStreamResp_ReadyForData); ok {
		return x.ReadyForData
	}
	return false
}

func (m *E2EEUploadDocStreamResp) GetEncryptors() *E2EEUploadDocStreamResp_PubKeyList {
	if x, ok := m.GetStageData().(*E2EEUploadDocStreamResp_Encryptors); ok {
		return x.Encryptors
	}
	return nil
}

func (m *E2EEUploadDocStreamResp) GetDocID() string {
	if x, ok := m.GetStageData().(*E2EEUploadDocStreamResp_DocID); ok {
		return x.DocID
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*E2EEUploadDocStreamResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*E2EEUploadDocStreamResp_ReadyForData)(nil),
		(*E2EEUploadDocStreamResp_Encryptors)(nil),
		(*E2EEUploadDocStreamResp_DocID)(nil),
	}
}

type E2EEUploadDocStreamResp_PubKeyList struct {
	PubKeys              []*Key   `protobuf:"bytes,1,rep,name=pubKeys,proto3" json:"pubKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *E2EEUploadDocStreamResp_PubKeyList) Reset()         { *m = E2EEUploadDocStreamResp_PubKeyList{} }
func (m *E2EEUploadDocStreamResp_PubKeyList) String() string { return proto.CompactTextString(m) }
func (*E2EEUploadDocStreamResp_PubKeyList) ProtoMessage()    {}
func (*E2EEUploadDocStreamResp_PubKeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{3, 0}
}

func (m *E2EEUploadDocStreamResp_PubKeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEUploadDocStreamResp_PubKeyList.Unmarshal(m, b)
}
func (m *E2EEUploadDocStreamResp_PubKeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEUploadDocStreamResp_PubKeyList.Marshal(b, m, deterministic)
}
func (m *E2EEUploadDocStreamResp_PubKeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEUploadDocStreamResp_PubKeyList.Merge(m, src)
}
func (m *E2EEUploadDocStreamResp_PubKeyList) XXX_Size() int {
	return xxx_messageInfo_E2EEUploadDocStreamResp_PubKeyList.Size(m)
}
func (m *E2EEUploadDocStreamResp_PubKeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEUploadDocStreamResp_PubKeyList.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEUploadDocStreamResp_PubKeyList proto.InternalMessageInfo

func (m *E2EEUploadDocStreamResp_PubKeyList) GetPubKeys() []*Key {
	if m != nil {
		return m.PubKeys
	}
	return nil
}

type DownloadDocStreamReq struct {
	// The ID of the document to download.
	DocID                string   `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadDocStreamReq) Reset()         { *m = DownloadDocStreamReq{} }
func (m *DownloadDocStreamReq) String() string { return proto.CompactTextString(m) }
func (*DownloadDocStreamReq) ProtoMessage()    {}
func (*DownloadDocStreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{4}
}

func (m *DownloadDocStreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadDocStreamReq.Unmarshal(m, b)
}
func (m *DownloadDocStreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadDocStreamReq.Marshal(b, m, deterministic)
}
func (m *DownloadDocStreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadDocStreamReq.Merge(m, src)
}
func (m *DownloadDocStreamReq) XXX_Size() int {
	return xxx_messageInfo_DownloadDocStreamReq.Size(m)
}
func (m *DownloadDocStreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadDocStreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadDocStreamReq proto.InternalMessageInfo

func (m *DownloadDocStreamReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

type DownloadDocStreamResp struct {
	// The ID of the document downloaded.
	DocID string `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	// The decrypted data of the document.
	Plaintext            []byte   `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadDocStreamResp) Reset()         { *m = DownloadDocStreamResp{} }
func (m *DownloadDocStreamResp) String() string { return proto.CompactTextString(m) }
func (*DownloadDocStreamResp) ProtoMessage()    {}
func (*DownloadDocStreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{5}
}

func (m *DownloadDocStreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadDocStreamResp.Unmarshal(m, b)
}
func (m *DownloadDocStreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadDocStreamResp.Marshal(b, m, deterministic)
}
func (m *DownloadDocStreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadDocStreamResp.Merge(m, src)
}
func (m *DownloadDocStreamResp) XXX_Size() int {
	return xxx_messageInfo_DownloadDocStreamResp.Size(m)
}
func (m *DownloadDocStreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadDocStreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadDocStreamResp proto.InternalMessageInfo

func (m *DownloadDocStreamResp) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *DownloadDocStreamResp) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

type E2EEPrepareDownloadDocReq struct {
	DocID                string   `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *E2EEPrepareDownloadDocReq) Reset()         { *m = E2EEPrepareDownloadDocReq{} }
func (m *E2EEPrepareDownloadDocReq) String() string { return proto.CompactTextString(m) }
func (*E2EEPrepareDownloadDocReq) ProtoMessage()    {}
func (*E2EEPrepareDownloadDocReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{6}
}

func (m *E2EEPrepareDownloadDocReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEPrepareDownloadDocReq.Unmarshal(m, b)
}
func (m *E2EEPrepareDownloadDocReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEPrepareDownloadDocReq.Marshal(b, m, deterministic)
}
func (m *E2EEPrepareDownloadDocReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEPrepareDownloadDocReq.Merge(m, src)
}
func (m *E2EEPrepareDownloadDocReq) XXX_Size() int {
	return xxx_messageInfo_E2EEPrepareDownloadDocReq.Size(m)
}
func (m *E2EEPrepareDownloadDocReq) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEPrepareDownloadDocReq.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEPrepareDownloadDocReq proto.InternalMessageInfo

func (m *E2EEPrepareDownloadDocReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

type E2EEPrepareDownloadDocResp struct {
	DocumentAccessMetadata *DocumentAccessMetadata `protobuf:"bytes,1,opt,name=documentAccessMetadata,proto3" json:"documentAccessMetadata,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *E2EEPrepareDownloadDocResp) Reset()         { *m = E2EEPrepareDownloadDocResp{} }
func (m *E2EEPrepareDownloadDocResp) String() string { return proto.CompactTextString(m) }
func (*E2EEPrepareDownloadDocResp) ProtoMessage()    {}
func (*E2EEPrepareDownloadDocResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{7}
}

func (m *E2EEPrepareDownloadDocResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEPrepareDownloadDocResp.Unmarshal(m, b)
}
func (m *E2EEPrepareDownloadDocResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEPrepareDownloadDocResp.Marshal(b, m, deterministic)
}
func (m *E2EEPrepareDownloadDocResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEPrepareDownloadDocResp.Merge(m, src)
}
func (m *E2EEPrepareDownloadDocResp) XXX_Size() int {
	return xxx_messageInfo_E2EEPrepareDownloadDocResp.Size(m)
}
func (m *E2EEPrepareDownloadDocResp) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEPrepareDownloadDocResp.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEPrepareDownloadDocResp proto.InternalMessageInfo

func (m *E2EEPrepareDownloadDocResp) GetDocumentAccessMetadata() *DocumentAccessMetadata {
	if m != nil {
		return m.DocumentAccessMetadata
	}
	return nil
}

type DocumentAccessMetadata struct {
	// Whether or not this user is allowed to access this document.
	IsAccessible bool `protobuf:"varint,1,opt,name=isAccessible,proto3" json:"isAccessible,omitempty"`
	// Whether or not the document is client-side encrypted.
	IsClientSide bool `protobuf:"varint,2,opt,name=isClientSide,proto3" json:"isClientSide,omitempty"`
	// A chain of EncryptedKeys. The user's passwordKey is used to decrypt the first one.
	// Each one is used to decrypt the next one. The final plaintext will be the docKey.
	DocKeyChain []*EncryptedKey `protobuf:"bytes,3,rep,name=docKeyChain,proto3" json:"docKeyChain,omitempty"`
	// The MAC of the ciphertext of the document. Only used when downloading.
	Mac                  string   `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentAccessMetadata) Reset()         { *m = DocumentAccessMetadata{} }
func (m *DocumentAccessMetadata) String() string { return proto.CompactTextString(m) }
func (*DocumentAccessMetadata) ProtoMessage()    {}
func (*DocumentAccessMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{8}
}

func (m *DocumentAccessMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentAccessMetadata.Unmarshal(m, b)
}
func (m *DocumentAccessMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentAccessMetadata.Marshal(b, m, deterministic)
}
func (m *DocumentAccessMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentAccessMetadata.Merge(m, src)
}
func (m *DocumentAccessMetadata) XXX_Size() int {
	return xxx_messageInfo_DocumentAccessMetadata.Size(m)
}
func (m *DocumentAccessMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentAccessMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentAccessMetadata proto.InternalMessageInfo

func (m *DocumentAccessMetadata) GetIsAccessible() bool {
	if m != nil {
		return m.IsAccessible
	}
	return false
}

func (m *DocumentAccessMetadata) GetIsClientSide() bool {
	if m != nil {
		return m.IsClientSide
	}
	return false
}

func (m *DocumentAccessMetadata) GetDocKeyChain() []*EncryptedKey {
	if m != nil {
		return m.DocKeyChain
	}
	return nil
}

func (m *DocumentAccessMetadata) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type E2EEDownloadDocStreamReq struct {
	DocID                string   `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *E2EEDownloadDocStreamReq) Reset()         { *m = E2EEDownloadDocStreamReq{} }
func (m *E2EEDownloadDocStreamReq) String() string { return proto.CompactTextString(m) }
func (*E2EEDownloadDocStreamReq) ProtoMessage()    {}
func (*E2EEDownloadDocStreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{9}
}

func (m *E2EEDownloadDocStreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEDownloadDocStreamReq.Unmarshal(m, b)
}
func (m *E2EEDownloadDocStreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEDownloadDocStreamReq.Marshal(b, m, deterministic)
}
func (m *E2EEDownloadDocStreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEDownloadDocStreamReq.Merge(m, src)
}
func (m *E2EEDownloadDocStreamReq) XXX_Size() int {
	return xxx_messageInfo_E2EEDownloadDocStreamReq.Size(m)
}
func (m *E2EEDownloadDocStreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEDownloadDocStreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEDownloadDocStreamReq proto.InternalMessageInfo

func (m *E2EEDownloadDocStreamReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

type E2EEDownloadDocStreamResp struct {
	CipherText           []byte   `protobuf:"bytes,1,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *E2EEDownloadDocStreamResp) Reset()         { *m = E2EEDownloadDocStreamResp{} }
func (m *E2EEDownloadDocStreamResp) String() string { return proto.CompactTextString(m) }
func (*E2EEDownloadDocStreamResp) ProtoMessage()    {}
func (*E2EEDownloadDocStreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{10}
}

func (m *E2EEDownloadDocStreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E2EEDownloadDocStreamResp.Unmarshal(m, b)
}
func (m *E2EEDownloadDocStreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E2EEDownloadDocStreamResp.Marshal(b, m, deterministic)
}
func (m *E2EEDownloadDocStreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E2EEDownloadDocStreamResp.Merge(m, src)
}
func (m *E2EEDownloadDocStreamResp) XXX_Size() int {
	return xxx_messageInfo_E2EEDownloadDocStreamResp.Size(m)
}
func (m *E2EEDownloadDocStreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_E2EEDownloadDocStreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_E2EEDownloadDocStreamResp proto.InternalMessageInfo

func (m *E2EEDownloadDocStreamResp) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

type UploadDocReq struct {
	// The name of the document to upload.
	DocName string `protobuf:"bytes,1,opt,name=docName,proto3" json:"docName,omitempty"`
	// The data of the document to upload.
	Plaintext            string   `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadDocReq) Reset()         { *m = UploadDocReq{} }
func (m *UploadDocReq) String() string { return proto.CompactTextString(m) }
func (*UploadDocReq) ProtoMessage()    {}
func (*UploadDocReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{11}
}

func (m *UploadDocReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadDocReq.Unmarshal(m, b)
}
func (m *UploadDocReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadDocReq.Marshal(b, m, deterministic)
}
func (m *UploadDocReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadDocReq.Merge(m, src)
}
func (m *UploadDocReq) XXX_Size() int {
	return xxx_messageInfo_UploadDocReq.Size(m)
}
func (m *UploadDocReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadDocReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadDocReq proto.InternalMessageInfo

func (m *UploadDocReq) GetDocName() string {
	if m != nil {
		return m.DocName
	}
	return ""
}

func (m *UploadDocReq) GetPlaintext() string {
	if m != nil {
		return m.Plaintext
	}
	return ""
}

type UploadDocResp struct {
	// The ID of the document uploaded.
	DocID                string   `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadDocResp) Reset()         { *m = UploadDocResp{} }
func (m *UploadDocResp) String() string { return proto.CompactTextString(m) }
func (*UploadDocResp) ProtoMessage()    {}
func (*UploadDocResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{12}
}

func (m *UploadDocResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadDocResp.Unmarshal(m, b)
}
func (m *UploadDocResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadDocResp.Marshal(b, m, deterministic)
}
func (m *UploadDocResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadDocResp.Merge(m, src)
}
func (m *UploadDocResp) XXX_Size() int {
	return xxx_messageInfo_UploadDocResp.Size(m)
}
func (m *UploadDocResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadDocResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadDocResp proto.InternalMessageInfo

func (m *UploadDocResp) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

type DownloadDocReq struct {
	// The ID of the document to download.
	DocID                string   `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadDocReq) Reset()         { *m = DownloadDocReq{} }
func (m *DownloadDocReq) String() string { return proto.CompactTextString(m) }
func (*DownloadDocReq) ProtoMessage()    {}
func (*DownloadDocReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{13}
}

func (m *DownloadDocReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadDocReq.Unmarshal(m, b)
}
func (m *DownloadDocReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadDocReq.Marshal(b, m, deterministic)
}
func (m *DownloadDocReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadDocReq.Merge(m, src)
}
func (m *DownloadDocReq) XXX_Size() int {
	return xxx_messageInfo_DownloadDocReq.Size(m)
}
func (m *DownloadDocReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadDocReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadDocReq proto.InternalMessageInfo

func (m *DownloadDocReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

type DownloadDocResp struct {
	// The ID of the document downloaded.
	DocID string `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	// The decrypted data of the downloaded document.
	Plaintext            string   `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadDocResp) Reset()         { *m = DownloadDocResp{} }
func (m *DownloadDocResp) String() string { return proto.CompactTextString(m) }
func (*DownloadDocResp) ProtoMessage()    {}
func (*DownloadDocResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{14}
}

func (m *DownloadDocResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadDocResp.Unmarshal(m, b)
}
func (m *DownloadDocResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadDocResp.Marshal(b, m, deterministic)
}
func (m *DownloadDocResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadDocResp.Merge(m, src)
}
func (m *DownloadDocResp) XXX_Size() int {
	return xxx_messageInfo_DownloadDocResp.Size(m)
}
func (m *DownloadDocResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadDocResp.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadDocResp proto.InternalMessageInfo

func (m *DownloadDocResp) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *DownloadDocResp) GetPlaintext() string {
	if m != nil {
		return m.Plaintext
	}
	return ""
}

type ShareDocumentReq struct {
	// The ID of the document to share.
	DocID string `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	// The user ID to share it to.
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareDocumentReq) Reset()         { *m = ShareDocumentReq{} }
func (m *ShareDocumentReq) String() string { return proto.CompactTextString(m) }
func (*ShareDocumentReq) ProtoMessage()    {}
func (*ShareDocumentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{15}
}

func (m *ShareDocumentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareDocumentReq.Unmarshal(m, b)
}
func (m *ShareDocumentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareDocumentReq.Marshal(b, m, deterministic)
}
func (m *ShareDocumentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareDocumentReq.Merge(m, src)
}
func (m *ShareDocumentReq) XXX_Size() int {
	return xxx_messageInfo_ShareDocumentReq.Size(m)
}
func (m *ShareDocumentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareDocumentReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShareDocumentReq proto.InternalMessageInfo

func (m *ShareDocumentReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *ShareDocumentReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ShareDocumentResp struct {
	// Whether the share was successful.
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareDocumentResp) Reset()         { *m = ShareDocumentResp{} }
func (m *ShareDocumentResp) String() string { return proto.CompactTextString(m) }
func (*ShareDocumentResp) ProtoMessage()    {}
func (*ShareDocumentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{16}
}

func (m *ShareDocumentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareDocumentResp.Unmarshal(m, b)
}
func (m *ShareDocumentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareDocumentResp.Marshal(b, m, deterministic)
}
func (m *ShareDocumentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareDocumentResp.Merge(m, src)
}
func (m *ShareDocumentResp) XXX_Size() int {
	return xxx_messageInfo_ShareDocumentResp.Size(m)
}
func (m *ShareDocumentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareDocumentResp.DiscardUnknown(m)
}

var xxx_messageInfo_ShareDocumentResp proto.InternalMessageInfo

func (m *ShareDocumentResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UnshareDocumentReq struct {
	// The ID of the document to unshare.
	DocID string `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	// The user ID to share it unshare.
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnshareDocumentReq) Reset()         { *m = UnshareDocumentReq{} }
func (m *UnshareDocumentReq) String() string { return proto.CompactTextString(m) }
func (*UnshareDocumentReq) ProtoMessage()    {}
func (*UnshareDocumentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{17}
}

func (m *UnshareDocumentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnshareDocumentReq.Unmarshal(m, b)
}
func (m *UnshareDocumentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnshareDocumentReq.Marshal(b, m, deterministic)
}
func (m *UnshareDocumentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnshareDocumentReq.Merge(m, src)
}
func (m *UnshareDocumentReq) XXX_Size() int {
	return xxx_messageInfo_UnshareDocumentReq.Size(m)
}
func (m *UnshareDocumentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnshareDocumentReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnshareDocumentReq proto.InternalMessageInfo

func (m *UnshareDocumentReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *UnshareDocumentReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UnshareDocumentResp struct {
	// The unshared document count.
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnshareDocumentResp) Reset()         { *m = UnshareDocumentResp{} }
func (m *UnshareDocumentResp) String() string { return proto.CompactTextString(m) }
func (*UnshareDocumentResp) ProtoMessage()    {}
func (*UnshareDocumentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{18}
}

func (m *UnshareDocumentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnshareDocumentResp.Unmarshal(m, b)
}
func (m *UnshareDocumentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnshareDocumentResp.Marshal(b, m, deterministic)
}
func (m *UnshareDocumentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnshareDocumentResp.Merge(m, src)
}
func (m *UnshareDocumentResp) XXX_Size() int {
	return xxx_messageInfo_UnshareDocumentResp.Size(m)
}
func (m *UnshareDocumentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnshareDocumentResp.DiscardUnknown(m)
}

var xxx_messageInfo_UnshareDocumentResp proto.InternalMessageInfo

func (m *UnshareDocumentResp) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListDocumentsReq struct {
	IncludeDeleted       bool     `protobuf:"varint,1,opt,name=includeDeleted,proto3" json:"includeDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDocumentsReq) Reset()         { *m = ListDocumentsReq{} }
func (m *ListDocumentsReq) String() string { return proto.CompactTextString(m) }
func (*ListDocumentsReq) ProtoMessage()    {}
func (*ListDocumentsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{19}
}

func (m *ListDocumentsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocumentsReq.Unmarshal(m, b)
}
func (m *ListDocumentsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocumentsReq.Marshal(b, m, deterministic)
}
func (m *ListDocumentsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocumentsReq.Merge(m, src)
}
func (m *ListDocumentsReq) XXX_Size() int {
	return xxx_messageInfo_ListDocumentsReq.Size(m)
}
func (m *ListDocumentsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocumentsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocumentsReq proto.InternalMessageInfo

func (m *ListDocumentsReq) GetIncludeDeleted() bool {
	if m != nil {
		return m.IncludeDeleted
	}
	return false
}

type ListDocumentsResp struct {
	// The list of documents.
	Documents            []*ListDocumentsResp_Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListDocumentsResp) Reset()         { *m = ListDocumentsResp{} }
func (m *ListDocumentsResp) String() string { return proto.CompactTextString(m) }
func (*ListDocumentsResp) ProtoMessage()    {}
func (*ListDocumentsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{20}
}

func (m *ListDocumentsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocumentsResp.Unmarshal(m, b)
}
func (m *ListDocumentsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocumentsResp.Marshal(b, m, deterministic)
}
func (m *ListDocumentsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocumentsResp.Merge(m, src)
}
func (m *ListDocumentsResp) XXX_Size() int {
	return xxx_messageInfo_ListDocumentsResp.Size(m)
}
func (m *ListDocumentsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocumentsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocumentsResp proto.InternalMessageInfo

func (m *ListDocumentsResp) GetDocuments() []*ListDocumentsResp_Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type ListDocumentsResp_Document struct {
	// The document ID.
	DocID string `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	// The document name.
	DocName string `protobuf:"bytes,2,opt,name=docName,proto3" json:"docName,omitempty"`
	// The document size.
	Size                 uint64               `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListDocumentsResp_Document) Reset()         { *m = ListDocumentsResp_Document{} }
func (m *ListDocumentsResp_Document) String() string { return proto.CompactTextString(m) }
func (*ListDocumentsResp_Document) ProtoMessage()    {}
func (*ListDocumentsResp_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{20, 0}
}

func (m *ListDocumentsResp_Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocumentsResp_Document.Unmarshal(m, b)
}
func (m *ListDocumentsResp_Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocumentsResp_Document.Marshal(b, m, deterministic)
}
func (m *ListDocumentsResp_Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocumentsResp_Document.Merge(m, src)
}
func (m *ListDocumentsResp_Document) XXX_Size() int {
	return xxx_messageInfo_ListDocumentsResp_Document.Size(m)
}
func (m *ListDocumentsResp_Document) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocumentsResp_Document.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocumentsResp_Document proto.InternalMessageInfo

func (m *ListDocumentsResp_Document) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *ListDocumentsResp_Document) GetDocName() string {
	if m != nil {
		return m.DocName
	}
	return ""
}

func (m *ListDocumentsResp_Document) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListDocumentsResp_Document) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ListDocumentsResp_Document) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type RemoveDocumentReq struct {
	// The ID of the document to remove.
	DocID                string   `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDocumentReq) Reset()         { *m = RemoveDocumentReq{} }
func (m *RemoveDocumentReq) String() string { return proto.CompactTextString(m) }
func (*RemoveDocumentReq) ProtoMessage()    {}
func (*RemoveDocumentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{21}
}

func (m *RemoveDocumentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDocumentReq.Unmarshal(m, b)
}
func (m *RemoveDocumentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDocumentReq.Marshal(b, m, deterministic)
}
func (m *RemoveDocumentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDocumentReq.Merge(m, src)
}
func (m *RemoveDocumentReq) XXX_Size() int {
	return xxx_messageInfo_RemoveDocumentReq.Size(m)
}
func (m *RemoveDocumentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDocumentReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDocumentReq proto.InternalMessageInfo

func (m *RemoveDocumentReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

type RemoveDocumentResp struct {
	// Whether the document removal was successful.
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDocumentResp) Reset()         { *m = RemoveDocumentResp{} }
func (m *RemoveDocumentResp) String() string { return proto.CompactTextString(m) }
func (*RemoveDocumentResp) ProtoMessage()    {}
func (*RemoveDocumentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{22}
}

func (m *RemoveDocumentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDocumentResp.Unmarshal(m, b)
}
func (m *RemoveDocumentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDocumentResp.Marshal(b, m, deterministic)
}
func (m *RemoveDocumentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDocumentResp.Merge(m, src)
}
func (m *RemoveDocumentResp) XXX_Size() int {
	return xxx_messageInfo_RemoveDocumentResp.Size(m)
}
func (m *RemoveDocumentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDocumentResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDocumentResp proto.InternalMessageInfo

func (m *RemoveDocumentResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ListDocActionHistoryReq struct {
	DocID                string               `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	UserID               string               `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ActionStartTime      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=actionStartTime,proto3" json:"actionStartTime,omitempty"`
	ActionEndTime        *timestamp.Timestamp `protobuf:"bytes,4,opt,name=actionEndTime,proto3" json:"actionEndTime,omitempty"`
	Page                 int32                `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              int32                `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListDocActionHistoryReq) Reset()         { *m = ListDocActionHistoryReq{} }
func (m *ListDocActionHistoryReq) String() string { return proto.CompactTextString(m) }
func (*ListDocActionHistoryReq) ProtoMessage()    {}
func (*ListDocActionHistoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{23}
}

func (m *ListDocActionHistoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocActionHistoryReq.Unmarshal(m, b)
}
func (m *ListDocActionHistoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocActionHistoryReq.Marshal(b, m, deterministic)
}
func (m *ListDocActionHistoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocActionHistoryReq.Merge(m, src)
}
func (m *ListDocActionHistoryReq) XXX_Size() int {
	return xxx_messageInfo_ListDocActionHistoryReq.Size(m)
}
func (m *ListDocActionHistoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocActionHistoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocActionHistoryReq proto.InternalMessageInfo

func (m *ListDocActionHistoryReq) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *ListDocActionHistoryReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ListDocActionHistoryReq) GetActionStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActionStartTime
	}
	return nil
}

func (m *ListDocActionHistoryReq) GetActionEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActionEndTime
	}
	return nil
}

func (m *ListDocActionHistoryReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListDocActionHistoryReq) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type ListDocActionHistoryResp struct {
	DocActionHistoryList []*ListDocActionHistoryResp_DocActionHistory `protobuf:"bytes,1,rep,name=DocActionHistoryList,proto3" json:"DocActionHistoryList,omitempty"`
	ResultTotalCount     int32                                        `protobuf:"varint,2,opt,name=ResultTotalCount,proto3" json:"ResultTotalCount,omitempty"`
	Offset               int32                                        `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *ListDocActionHistoryResp) Reset()         { *m = ListDocActionHistoryResp{} }
func (m *ListDocActionHistoryResp) String() string { return proto.CompactTextString(m) }
func (*ListDocActionHistoryResp) ProtoMessage()    {}
func (*ListDocActionHistoryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{24}
}

func (m *ListDocActionHistoryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocActionHistoryResp.Unmarshal(m, b)
}
func (m *ListDocActionHistoryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocActionHistoryResp.Marshal(b, m, deterministic)
}
func (m *ListDocActionHistoryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocActionHistoryResp.Merge(m, src)
}
func (m *ListDocActionHistoryResp) XXX_Size() int {
	return xxx_messageInfo_ListDocActionHistoryResp.Size(m)
}
func (m *ListDocActionHistoryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocActionHistoryResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocActionHistoryResp proto.InternalMessageInfo

func (m *ListDocActionHistoryResp) GetDocActionHistoryList() []*ListDocActionHistoryResp_DocActionHistory {
	if m != nil {
		return m.DocActionHistoryList
	}
	return nil
}

func (m *ListDocActionHistoryResp) GetResultTotalCount() int32 {
	if m != nil {
		return m.ResultTotalCount
	}
	return 0
}

func (m *ListDocActionHistoryResp) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListDocActionHistoryResp_DocActionHistory struct {
	DocID                string               `protobuf:"bytes,1,opt,name=docID,proto3" json:"docID,omitempty"`
	UserID               string               `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	DocName              string               `protobuf:"bytes,3,opt,name=docName,proto3" json:"docName,omitempty"`
	ActionTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=actionTime,proto3" json:"actionTime,omitempty"`
	ActionType           string               `protobuf:"bytes,5,opt,name=actionType,proto3" json:"actionType,omitempty"`
	OtherUserID          string               `protobuf:"bytes,6,opt,name=OtherUserID,proto3" json:"OtherUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListDocActionHistoryResp_DocActionHistory) Reset() {
	*m = ListDocActionHistoryResp_DocActionHistory{}
}
func (m *ListDocActionHistoryResp_DocActionHistory) String() string { return proto.CompactTextString(m) }
func (*ListDocActionHistoryResp_DocActionHistory) ProtoMessage()    {}
func (*ListDocActionHistoryResp_DocActionHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{24, 0}
}

func (m *ListDocActionHistoryResp_DocActionHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocActionHistoryResp_DocActionHistory.Unmarshal(m, b)
}
func (m *ListDocActionHistoryResp_DocActionHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocActionHistoryResp_DocActionHistory.Marshal(b, m, deterministic)
}
func (m *ListDocActionHistoryResp_DocActionHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocActionHistoryResp_DocActionHistory.Merge(m, src)
}
func (m *ListDocActionHistoryResp_DocActionHistory) XXX_Size() int {
	return xxx_messageInfo_ListDocActionHistoryResp_DocActionHistory.Size(m)
}
func (m *ListDocActionHistoryResp_DocActionHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocActionHistoryResp_DocActionHistory.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocActionHistoryResp_DocActionHistory proto.InternalMessageInfo

func (m *ListDocActionHistoryResp_DocActionHistory) GetDocID() string {
	if m != nil {
		return m.DocID
	}
	return ""
}

func (m *ListDocActionHistoryResp_DocActionHistory) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ListDocActionHistoryResp_DocActionHistory) GetDocName() string {
	if m != nil {
		return m.DocName
	}
	return ""
}

func (m *ListDocActionHistoryResp_DocActionHistory) GetActionTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActionTime
	}
	return nil
}

func (m *ListDocActionHistoryResp_DocActionHistory) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *ListDocActionHistoryResp_DocActionHistory) GetOtherUserID() string {
	if m != nil {
		return m.OtherUserID
	}
	return ""
}

func init() {
	proto.RegisterType((*UploadDocStreamReq)(nil), "proto.UploadDocStreamReq")
	proto.RegisterType((*UploadDocStreamResp)(nil), "proto.UploadDocStreamResp")
	proto.RegisterType((*E2EEUploadDocStreamReq)(nil), "proto.E2EEUploadDocStreamReq")
	proto.RegisterType((*E2EEUploadDocStreamReq_PreMetaDataType)(nil), "proto.E2EEUploadDocStreamReq.PreMetaDataType")
	proto.RegisterType((*E2EEUploadDocStreamReq_PostMetaDataType)(nil), "proto.E2EEUploadDocStreamReq.PostMetaDataType")
	proto.RegisterType((*E2EEUploadDocStreamReq_EncKeyList)(nil), "proto.E2EEUploadDocStreamReq.EncKeyList")
	proto.RegisterType((*E2EEUploadDocStreamResp)(nil), "proto.E2EEUploadDocStreamResp")
	proto.RegisterType((*E2EEUploadDocStreamResp_PubKeyList)(nil), "proto.E2EEUploadDocStreamResp.PubKeyList")
	proto.RegisterType((*DownloadDocStreamReq)(nil), "proto.DownloadDocStreamReq")
	proto.RegisterType((*DownloadDocStreamResp)(nil), "proto.DownloadDocStreamResp")
	proto.RegisterType((*E2EEPrepareDownloadDocReq)(nil), "proto.E2EEPrepareDownloadDocReq")
	proto.RegisterType((*E2EEPrepareDownloadDocResp)(nil), "proto.E2EEPrepareDownloadDocResp")
	proto.RegisterType((*DocumentAccessMetadata)(nil), "proto.DocumentAccessMetadata")
	proto.RegisterType((*E2EEDownloadDocStreamReq)(nil), "proto.E2EEDownloadDocStreamReq")
	proto.RegisterType((*E2EEDownloadDocStreamResp)(nil), "proto.E2EEDownloadDocStreamResp")
	proto.RegisterType((*UploadDocReq)(nil), "proto.UploadDocReq")
	proto.RegisterType((*UploadDocResp)(nil), "proto.UploadDocResp")
	proto.RegisterType((*DownloadDocReq)(nil), "proto.DownloadDocReq")
	proto.RegisterType((*DownloadDocResp)(nil), "proto.DownloadDocResp")
	proto.RegisterType((*ShareDocumentReq)(nil), "proto.ShareDocumentReq")
	proto.RegisterType((*ShareDocumentResp)(nil), "proto.ShareDocumentResp")
	proto.RegisterType((*UnshareDocumentReq)(nil), "proto.UnshareDocumentReq")
	proto.RegisterType((*UnshareDocumentResp)(nil), "proto.UnshareDocumentResp")
	proto.RegisterType((*ListDocumentsReq)(nil), "proto.ListDocumentsReq")
	proto.RegisterType((*ListDocumentsResp)(nil), "proto.ListDocumentsResp")
	proto.RegisterType((*ListDocumentsResp_Document)(nil), "proto.ListDocumentsResp.Document")
	proto.RegisterType((*RemoveDocumentReq)(nil), "proto.RemoveDocumentReq")
	proto.RegisterType((*RemoveDocumentResp)(nil), "proto.RemoveDocumentResp")
	proto.RegisterType((*ListDocActionHistoryReq)(nil), "proto.ListDocActionHistoryReq")
	proto.RegisterType((*ListDocActionHistoryResp)(nil), "proto.ListDocActionHistoryResp")
	proto.RegisterType((*ListDocActionHistoryResp_DocActionHistory)(nil), "proto.ListDocActionHistoryResp.DocActionHistory")
}

func init() { proto.RegisterFile("document.proto", fileDescriptor_9d2790a4091b3173) }

var fileDescriptor_9d2790a4091b3173 = []byte{
	// 1501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x41, 0x53, 0x1b, 0xc9,
	0x15, 0x66, 0x10, 0x60, 0xf4, 0xc0, 0x20, 0x1a, 0x8c, 0xb1, 0x12, 0x3b, 0x93, 0x2e, 0x57, 0x42,
	0x54, 0x20, 0x40, 0xd8, 0x49, 0x6a, 0x92, 0x54, 0x3c, 0x20, 0x1c, 0x08, 0xb1, 0x21, 0x03, 0xc4,
	0x4e, 0x88, 0xe3, 0x1a, 0xcd, 0x34, 0x62, 0x2a, 0xd2, 0xf4, 0x78, 0xba, 0x65, 0xac, 0x50, 0xba,
	0x67, 0x2f, 0x5b, 0xb5, 0xaa, 0xda, 0xdb, 0x1e, 0xb6, 0xf6, 0xb6, 0xbf, 0x60, 0x4f, 0x7b, 0xd9,
	0x5f, 0xb1, 0x7f, 0x60, 0xff, 0xc7, 0x56, 0x77, 0xcf, 0xa0, 0x19, 0x69, 0x04, 0xb8, 0xf6, 0xa4,
	0xe9, 0x6f, 0xde, 0xf7, 0xba, 0xdf, 0x7b, 0xdf, 0x7b, 0xd3, 0x82, 0x19, 0x97, 0x3a, 0xad, 0x26,
	0xf1, 0x79, 0x39, 0x08, 0x29, 0xa7, 0x68, 0x5c, 0xfe, 0x14, 0x57, 0xe4, 0x8f, 0xb3, 0x5a, 0x27,
	0xfe, 0x2a, 0xbb, 0xb0, 0xeb, 0x75, 0x12, 0xae, 0xd1, 0x80, 0x7b, 0xd4, 0x67, 0x6b, 0xb6, 0xef,
	0x53, 0x6e, 0xcb, 0x67, 0x45, 0x2a, 0xfe, 0xa2, 0x4e, 0x69, 0xbd, 0x41, 0xd6, 0xe4, 0xaa, 0xd6,
	0x3a, 0x5b, 0xe3, 0x5e, 0x93, 0x30, 0x6e, 0x37, 0x83, 0xc8, 0xa0, 0x40, 0x7c, 0x27, 0x6c, 0x4b,
	0xbe, 0x42, 0xf0, 0x7f, 0x00, 0x9d, 0x04, 0x0d, 0x6a, 0xbb, 0x55, 0xea, 0x1c, 0xf1, 0x90, 0xd8,
	0x4d, 0x8b, 0xbc, 0x43, 0x45, 0xb8, 0xe3, 0x52, 0xe7, 0xa5, 0xdd, 0x24, 0x4b, 0x9a, 0xae, 0x2d,
	0xe7, 0x77, 0x47, 0xac, 0x18, 0x40, 0x8f, 0x20, 0x1f, 0x34, 0x6c, 0xcf, 0xe7, 0xe4, 0x03, 0x5f,
	0x1a, 0xd5, 0xb5, 0xe5, 0xe9, 0xdd, 0x11, 0xab, 0x07, 0x6d, 0x4d, 0x03, 0x08, 0xbb, 0x83, 0xb0,
	0x6a, 0x73, 0x1b, 0x9b, 0x30, 0x3f, 0xe0, 0x9f, 0x05, 0x68, 0x01, 0xc6, 0x5d, 0xea, 0xec, 0x55,
	0x95, 0x7b, 0x4b, 0x2d, 0x04, 0x5a, 0x6b, 0x73, 0xc2, 0xa4, 0xdb, 0x9c, 0xa5, 0x16, 0xf8, 0x8b,
	0x31, 0x58, 0xdc, 0xa9, 0xec, 0xec, 0x64, 0x9c, 0xf3, 0xef, 0x30, 0x15, 0x84, 0xe4, 0x05, 0xe1,
	0xb6, 0xd8, 0x4c, 0x3a, 0x9b, 0xaa, 0xac, 0xaa, 0xd0, 0xca, 0xd9, 0x9c, 0xf2, 0x61, 0x8f, 0x70,
	0xdc, 0x0e, 0xc8, 0xee, 0x88, 0x95, 0xf4, 0x81, 0xfe, 0x0a, 0x40, 0x7c, 0xa7, 0x4a, 0x9d, 0x7d,
	0xd2, 0x56, 0x07, 0x99, 0xaa, 0x2c, 0x5f, 0xef, 0x71, 0xc7, 0x17, 0xc6, 0x7f, 0xf3, 0x18, 0xdf,
	0x1d, 0xb1, 0x12, 0x6c, 0xa4, 0x03, 0x38, 0x5e, 0x70, 0x4e, 0xc2, 0x63, 0x91, 0xab, 0x5c, 0x94,
	0xab, 0x04, 0x86, 0x8e, 0x61, 0x3a, 0xa0, 0x8c, 0x5f, 0x45, 0x30, 0x26, 0xf7, 0x2b, 0xdf, 0x10,
	0x41, 0x82, 0x11, 0x85, 0x90, 0xf2, 0x52, 0x7c, 0x03, 0xb3, 0x7d, 0x51, 0xa2, 0xa5, 0xbe, 0x8a,
	0xf6, 0xea, 0xb9, 0x0e, 0xf3, 0x1e, 0xdb, 0x51, 0xba, 0x20, 0xee, 0x56, 0x7b, 0xbb, 0xe1, 0x11,
	0x5f, 0x55, 0x76, 0xd2, 0xca, 0x7a, 0x55, 0xfc, 0x23, 0x14, 0xfa, 0x8f, 0x80, 0x96, 0x61, 0xb6,
	0x69, 0x3b, 0x07, 0x67, 0xdb, 0xbd, 0x78, 0xd5, 0x3e, 0xfd, 0x70, 0xd1, 0x04, 0xe8, 0x25, 0x0c,
	0x6d, 0xa6, 0xd2, 0xad, 0xe9, 0xb9, 0xe5, 0xa9, 0xca, 0x7c, 0x1c, 0x7e, 0xbc, 0xf3, 0x3e, 0x69,
	0x27, 0xf3, 0xba, 0x35, 0x05, 0x79, 0xc6, 0xed, 0x3a, 0x91, 0x0a, 0xfb, 0x41, 0x83, 0xfb, 0x99,
	0x89, 0x62, 0x01, 0x7a, 0x0c, 0xd3, 0x21, 0xb1, 0xdd, 0xf6, 0x73, 0x1a, 0x5e, 0x09, 0x64, 0x52,
	0xa4, 0x2b, 0x89, 0xa2, 0x7d, 0x79, 0x06, 0xb1, 0x15, 0x0d, 0xe3, 0x92, 0xff, 0xe6, 0xba, 0x12,
	0xb0, 0xa0, 0x7c, 0xd8, 0xaa, 0xa5, 0x6b, 0x1e, 0xd1, 0xd1, 0x62, 0xac, 0xec, 0x5c, 0xd4, 0x38,
	0x6a, 0x59, 0xac, 0x00, 0xf4, 0x38, 0xe8, 0x31, 0xdc, 0x09, 0xe4, 0x2a, 0x8e, 0x19, 0xa2, 0xfd,
	0x44, 0xa8, 0xf1, 0xab, 0x74, 0x9c, 0x2b, 0xb0, 0x50, 0xa5, 0x17, 0xfe, 0x40, 0x0f, 0x64, 0xb6,
	0x12, 0xde, 0x87, 0x7b, 0x19, 0xd6, 0x43, 0x3b, 0xef, 0xe7, 0x03, 0x4d, 0x9d, 0x68, 0x69, 0xbc,
	0x01, 0x0f, 0x44, 0x1e, 0x0e, 0x43, 0x12, 0xd8, 0x21, 0x49, 0xf8, 0x1d, 0xbe, 0x3f, 0x83, 0xe2,
	0x30, 0x0a, 0x0b, 0xd0, 0x09, 0x2c, 0xc6, 0xf3, 0xce, 0x74, 0x1c, 0xc2, 0x98, 0xd0, 0x92, 0xdb,
	0x6b, 0xe1, 0x87, 0x51, 0x36, 0xaa, 0x99, 0x46, 0xd6, 0x10, 0x32, 0xfe, 0x5a, 0x83, 0xc5, 0x6c,
	0x0a, 0xc2, 0x30, 0xed, 0x31, 0x85, 0x79, 0xb5, 0x86, 0x6a, 0x82, 0x49, 0x2b, 0x85, 0x29, 0x1b,
	0xa5, 0xf1, 0x23, 0xcf, 0x25, 0x51, 0x0b, 0xa4, 0x30, 0xf4, 0x14, 0xa6, 0x5c, 0xa9, 0xc2, 0xed,
	0x73, 0xdb, 0xf3, 0x97, 0x72, 0xc3, 0x05, 0x9b, 0xb4, 0x43, 0x05, 0xc8, 0x35, 0x6d, 0x47, 0xb6,
	0x77, 0xde, 0x12, 0x8f, 0x78, 0x1d, 0x96, 0x44, 0x82, 0x3e, 0xa2, 0xa4, 0x7f, 0x50, 0x55, 0xc8,
	0x2e, 0xeb, 0xa3, 0xd4, 0xa8, 0xd1, 0x64, 0x05, 0x13, 0x08, 0xfe, 0x52, 0x83, 0xe9, 0x2b, 0x1d,
	0x8b, 0x3d, 0x86, 0x0f, 0x84, 0x01, 0x2d, 0xe4, 0x13, 0x5a, 0x30, 0x5e, 0x77, 0xcd, 0x13, 0x98,
	0x29, 0xa5, 0x9c, 0x55, 0xb6, 0x91, 0x79, 0x89, 0x23, 0x3e, 0x36, 0x74, 0x5c, 0x0b, 0xbd, 0x1a,
	0xb1, 0x9b, 0xb4, 0xe5, 0x73, 0xbc, 0xa2, 0xe3, 0x9e, 0x92, 0x0c, 0x1d, 0xef, 0xe9, 0x81, 0xed,
	0xb9, 0xfa, 0xc6, 0x0b, 0x9d, 0x53, 0xfd, 0x1f, 0xb4, 0x41, 0xdd, 0x76, 0xb3, 0x1d, 0xe2, 0x0e,
	0xfe, 0x17, 0xdc, 0x4d, 0x38, 0x1d, 0x26, 0x55, 0x63, 0xb3, 0x6b, 0xae, 0xc3, 0x6c, 0x29, 0x6d,
	0x5b, 0x79, 0x88, 0x7e, 0x26, 0x4f, 0xb0, 0x57, 0xed, 0xdb, 0xff, 0xed, 0x5e, 0x15, 0x77, 0xf0,
	0xbf, 0x61, 0xe6, 0x36, 0xb2, 0x35, 0x9e, 0x74, 0xcd, 0x0d, 0x28, 0x94, 0xfa, 0x8c, 0x6f, 0xf2,
	0xfe, 0x95, 0x06, 0xb3, 0xfd, 0x12, 0xbf, 0x65, 0x9f, 0xa5, 0x72, 0x7b, 0xda, 0x35, 0x5f, 0x67,
	0xec, 0x5e, 0x45, 0x5b, 0xc3, 0x77, 0xbf, 0x75, 0x7a, 0x3f, 0xd1, 0xa0, 0x70, 0x74, 0x2e, 0x9b,
	0x51, 0x75, 0xc8, 0xd0, 0x2c, 0xa0, 0x45, 0x98, 0x68, 0x31, 0x12, 0xee, 0x55, 0xa3, 0x23, 0x46,
	0x2b, 0xe3, 0x2f, 0x5d, 0xb3, 0x0a, 0xa8, 0x34, 0xe0, 0xa6, 0x52, 0x46, 0x2b, 0xd7, 0x9e, 0x50,
	0xf1, 0xc5, 0xbb, 0xe7, 0x5b, 0x7b, 0xb2, 0x1c, 0x73, 0x7d, 0x3e, 0x58, 0x20, 0x14, 0xc9, 0x5a,
	0xb2, 0x1b, 0xa3, 0xee, 0x8c, 0x97, 0xc6, 0x6a, 0xd7, 0x2c, 0xc1, 0x7c, 0x69, 0x90, 0x53, 0x99,
	0x47, 0x73, 0x97, 0x38, 0x32, 0xc3, 0x86, 0xce, 0xc3, 0x16, 0xe9, 0xe0, 0xae, 0x06, 0xe8, 0xc4,
	0x67, 0x3f, 0x2d, 0xd6, 0x97, 0x5d, 0x73, 0x1f, 0x16, 0x4a, 0x19, 0x8e, 0x2a, 0x9b, 0x68, 0xe3,
	0xb6, 0xd1, 0xd2, 0x0f, 0xfa, 0x4b, 0x72, 0xc1, 0x70, 0x07, 0xbf, 0x82, 0xf9, 0x01, 0x57, 0x4a,
	0x26, 0x8e, 0xa0, 0xca, 0x43, 0xe5, 0x2c, 0xb5, 0x30, 0x4a, 0x5d, 0xf3, 0xd7, 0x70, 0xaf, 0x94,
	0xc5, 0xa8, 0xcc, 0xa0, 0xe9, 0x4b, 0x2c, 0xcd, 0xb0, 0xa1, 0x6f, 0x74, 0xf0, 0x11, 0x14, 0xc4,
	0x27, 0x25, 0xb6, 0x61, 0x22, 0xd4, 0x5f, 0xc1, 0x8c, 0xe7, 0x3b, 0x8d, 0x96, 0x4b, 0xaa, 0xa4,
	0x41, 0x38, 0x71, 0xa3, 0x8c, 0xf6, 0xa1, 0xc6, 0xfd, 0xae, 0xb9, 0x20, 0x0a, 0xda, 0xef, 0x00,
	0x7f, 0x9a, 0x83, 0xb9, 0x3e, 0x90, 0x05, 0xe8, 0xcf, 0x90, 0x8f, 0x27, 0x6f, 0xfc, 0xdd, 0xfa,
	0x65, 0x34, 0xfa, 0x06, 0x8c, 0xaf, 0x66, 0xb7, 0xd5, 0xe3, 0x14, 0xbf, 0xd3, 0x60, 0x32, 0xc6,
	0x87, 0xd4, 0x23, 0x31, 0x97, 0x46, 0xd3, 0x73, 0x09, 0xc1, 0x18, 0xf3, 0xfe, 0x47, 0xe4, 0x87,
	0x75, 0xcc, 0x92, 0xcf, 0xe8, 0xf7, 0x90, 0x77, 0x42, 0x62, 0x73, 0xe2, 0x9a, 0x3c, 0xba, 0x3c,
	0x15, 0xcb, 0xea, 0x16, 0x5c, 0x8e, 0x6f, 0xc1, 0xe5, 0xe3, 0xf8, 0x16, 0x6c, 0xf5, 0x8c, 0x05,
	0xd3, 0x55, 0x59, 0x30, 0xf9, 0xd2, 0xf8, 0xcd, 0xcc, 0x2b, 0x63, 0x83, 0x75, 0xcd, 0x40, 0xa8,
	0x71, 0x20, 0xe4, 0xca, 0x3f, 0xd1, 0x2b, 0x29, 0x0c, 0x05, 0x61, 0x43, 0x3f, 0xbd, 0x56, 0x27,
	0xd9, 0x03, 0xb3, 0x1c, 0xb8, 0x67, 0xe2, 0xad, 0x88, 0x0f, 0x1b, 0xfa, 0xd3, 0xdf, 0x6e, 0x74,
	0xde, 0x74, 0x70, 0x0d, 0xe6, 0x2c, 0xd2, 0xa4, 0xef, 0x6f, 0x56, 0xb4, 0xf1, 0xbb, 0xae, 0xf9,
	0x44, 0x9c, 0x6f, 0xc0, 0xfe, 0xa6, 0x31, 0x76, 0x0a, 0xa8, 0x9f, 0xc3, 0x02, 0xd1, 0x20, 0x8c,
	0xdb, 0xbc, 0x15, 0x77, 0x65, 0xb4, 0x52, 0x4d, 0xb9, 0x50, 0xca, 0xa0, 0x54, 0x10, 0x2a, 0x5c,
	0x62, 0x65, 0x76, 0xd5, 0x94, 0xdf, 0x8e, 0xc2, 0xfd, 0x28, 0x63, 0xa6, 0x23, 0xfe, 0x80, 0xec,
	0x7a, 0x8c, 0xd3, 0xb0, 0xfd, 0xd1, 0x9d, 0x89, 0xaa, 0x30, 0x6b, 0x4b, 0x0f, 0x47, 0xdc, 0x0e,
	0xb9, 0x28, 0x91, 0x94, 0xc4, 0xf5, 0xf5, 0xeb, 0xa7, 0xa0, 0x67, 0x70, 0x57, 0x41, 0x3b, 0xbe,
	0x2b, 0x7d, 0xdc, 0xac, 0x9e, 0x34, 0x41, 0xe8, 0x31, 0xb0, 0xeb, 0x44, 0x8a, 0x67, 0xdc, 0x92,
	0xcf, 0xe8, 0x01, 0x4c, 0x06, 0x24, 0x7c, 0x2b, 0xf1, 0x09, 0x89, 0xdf, 0x09, 0x48, 0x78, 0x68,
	0xd7, 0x89, 0xf1, 0xa7, 0xae, 0x69, 0xc0, 0x83, 0xd2, 0xb0, 0x24, 0xdc, 0x54, 0x9c, 0x6f, 0xc6,
	0x60, 0x29, 0x9b, 0xca, 0x02, 0xe4, 0x8a, 0xbb, 0x61, 0x1a, 0x17, 0xb6, 0x51, 0x8f, 0xae, 0xa7,
	0x7b, 0x74, 0x80, 0x5e, 0x1e, 0x00, 0x33, 0xbd, 0xa1, 0x12, 0x14, 0x2c, 0xc2, 0x5a, 0x0d, 0x7e,
	0x4c, 0xb9, 0xdd, 0xd8, 0x96, 0x63, 0x6b, 0x54, 0x06, 0x39, 0x80, 0x8b, 0xe2, 0x1d, 0x9c, 0x9d,
	0x31, 0xa2, 0xfe, 0xf6, 0x8c, 0x5b, 0xd1, 0xaa, 0xf8, 0xbd, 0x06, 0x85, 0x7e, 0xe7, 0x1f, 0x59,
	0xff, 0xc4, 0x84, 0xc8, 0xa5, 0x27, 0x84, 0x01, 0xa0, 0x4a, 0x74, 0xcb, 0x82, 0x26, 0xac, 0xc5,
	0x05, 0x2a, 0x5a, 0xb5, 0x03, 0x55, 0xd3, 0xbc, 0x95, 0x40, 0x90, 0x0e, 0x53, 0x07, 0xfc, 0x9c,
	0x84, 0x27, 0xea, 0x48, 0x13, 0xd2, 0x20, 0x09, 0x19, 0x9f, 0x6b, 0x5d, 0xf3, 0x33, 0x0d, 0x8a,
	0xa5, 0xa1, 0x75, 0xaa, 0x30, 0xf4, 0xee, 0x12, 0x67, 0xe5, 0x16, 0x1b, 0xa7, 0x97, 0xf2, 0xbb,
	0x11, 0x0f, 0x84, 0x2a, 0xf5, 0xed, 0x86, 0xab, 0x1f, 0x87, 0xad, 0x66, 0x90, 0xfe, 0xa6, 0xb8,
	0xf2, 0x4d, 0x99, 0x8b, 0x37, 0xcf, 0x2e, 0xce, 0x3d, 0x4e, 0xce, 0x69, 0x8b, 0x91, 0x72, 0x9d,
	0xbe, 0x17, 0x86, 0x1e, 0x33, 0xdd, 0xa6, 0xe7, 0xc7, 0x7d, 0xf7, 0xa6, 0xb3, 0x55, 0x01, 0xec,
	0xd0, 0x66, 0x99, 0xf1, 0x90, 0xfa, 0x75, 0x66, 0x37, 0x78, 0xf4, 0xe8, 0x52, 0xa7, 0xcc, 0xdc,
	0xff, 0xaa, 0xc4, 0x6c, 0xe5, 0xaf, 0x46, 0xd9, 0xff, 0x35, 0xad, 0x36, 0x21, 0xc1, 0xcd, 0x1f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x13, 0x57, 0x0b, 0x05, 0x97, 0x10, 0x00, 0x00,
}
