// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encryption.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnableE2EReq struct {
	// The public key of the organization.
	OrgPubKey string `protobuf:"bytes,1,opt,name=orgPubKey,proto3" json:"orgPubKey,omitempty"`
	// The public key of the user.
	UserPubKey string `protobuf:"bytes,2,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	// The encrypted private key of the organization.
	UserEncPriKey string `protobuf:"bytes,3,opt,name=userEncPriKey,proto3" json:"userEncPriKey,omitempty"`
	// The encrypted private key of the user.
	OrgEncPriKey         string   `protobuf:"bytes,4,opt,name=orgEncPriKey,proto3" json:"orgEncPriKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableE2EReq) Reset()         { *m = EnableE2EReq{} }
func (m *EnableE2EReq) String() string { return proto.CompactTextString(m) }
func (*EnableE2EReq) ProtoMessage()    {}
func (*EnableE2EReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{0}
}

func (m *EnableE2EReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableE2EReq.Unmarshal(m, b)
}
func (m *EnableE2EReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableE2EReq.Marshal(b, m, deterministic)
}
func (m *EnableE2EReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableE2EReq.Merge(m, src)
}
func (m *EnableE2EReq) XXX_Size() int {
	return xxx_messageInfo_EnableE2EReq.Size(m)
}
func (m *EnableE2EReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableE2EReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnableE2EReq proto.InternalMessageInfo

func (m *EnableE2EReq) GetOrgPubKey() string {
	if m != nil {
		return m.OrgPubKey
	}
	return ""
}

func (m *EnableE2EReq) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *EnableE2EReq) GetUserEncPriKey() string {
	if m != nil {
		return m.UserEncPriKey
	}
	return ""
}

func (m *EnableE2EReq) GetOrgEncPriKey() string {
	if m != nil {
		return m.OrgEncPriKey
	}
	return ""
}

type EnableE2EResp struct {
	// The list of organization public keys
	PublicKeys           []string `protobuf:"bytes,1,rep,name=publicKeys,proto3" json:"publicKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableE2EResp) Reset()         { *m = EnableE2EResp{} }
func (m *EnableE2EResp) String() string { return proto.CompactTextString(m) }
func (*EnableE2EResp) ProtoMessage()    {}
func (*EnableE2EResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{1}
}

func (m *EnableE2EResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableE2EResp.Unmarshal(m, b)
}
func (m *EnableE2EResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableE2EResp.Marshal(b, m, deterministic)
}
func (m *EnableE2EResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableE2EResp.Merge(m, src)
}
func (m *EnableE2EResp) XXX_Size() int {
	return xxx_messageInfo_EnableE2EResp.Size(m)
}
func (m *EnableE2EResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableE2EResp.DiscardUnknown(m)
}

var xxx_messageInfo_EnableE2EResp proto.InternalMessageInfo

func (m *EnableE2EResp) GetPublicKeys() []string {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type GetOwnKeysReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnKeysReq) Reset()         { *m = GetOwnKeysReq{} }
func (m *GetOwnKeysReq) String() string { return proto.CompactTextString(m) }
func (*GetOwnKeysReq) ProtoMessage()    {}
func (*GetOwnKeysReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{2}
}

func (m *GetOwnKeysReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnKeysReq.Unmarshal(m, b)
}
func (m *GetOwnKeysReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnKeysReq.Marshal(b, m, deterministic)
}
func (m *GetOwnKeysReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnKeysReq.Merge(m, src)
}
func (m *GetOwnKeysReq) XXX_Size() int {
	return xxx_messageInfo_GetOwnKeysReq.Size(m)
}
func (m *GetOwnKeysReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnKeysReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnKeysReq proto.InternalMessageInfo

type GetOwnKeysResp struct {
	EncPrivKey           string       `protobuf:"bytes,1,opt,name=encPrivKey,proto3" json:"encPrivKey,omitempty"`
	EncryptorID          string       `protobuf:"bytes,2,opt,name=encryptorID,proto3" json:"encryptorID,omitempty"`
	UserPubKeys          *UserPubKeys `protobuf:"bytes,3,opt,name=userPubKeys,proto3" json:"userPubKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetOwnKeysResp) Reset()         { *m = GetOwnKeysResp{} }
func (m *GetOwnKeysResp) String() string { return proto.CompactTextString(m) }
func (*GetOwnKeysResp) ProtoMessage()    {}
func (*GetOwnKeysResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{3}
}

func (m *GetOwnKeysResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnKeysResp.Unmarshal(m, b)
}
func (m *GetOwnKeysResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnKeysResp.Marshal(b, m, deterministic)
}
func (m *GetOwnKeysResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnKeysResp.Merge(m, src)
}
func (m *GetOwnKeysResp) XXX_Size() int {
	return xxx_messageInfo_GetOwnKeysResp.Size(m)
}
func (m *GetOwnKeysResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnKeysResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnKeysResp proto.InternalMessageInfo

func (m *GetOwnKeysResp) GetEncPrivKey() string {
	if m != nil {
		return m.EncPrivKey
	}
	return ""
}

func (m *GetOwnKeysResp) GetEncryptorID() string {
	if m != nil {
		return m.EncryptorID
	}
	return ""
}

func (m *GetOwnKeysResp) GetUserPubKeys() *UserPubKeys {
	if m != nil {
		return m.UserPubKeys
	}
	return nil
}

type UserPubKeys struct {
	UserPubKey           *Key     `protobuf:"bytes,1,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	OrgPubKeys           []*Key   `protobuf:"bytes,2,rep,name=orgPubKeys,proto3" json:"orgPubKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPubKeys) Reset()         { *m = UserPubKeys{} }
func (m *UserPubKeys) String() string { return proto.CompactTextString(m) }
func (*UserPubKeys) ProtoMessage()    {}
func (*UserPubKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{4}
}

func (m *UserPubKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPubKeys.Unmarshal(m, b)
}
func (m *UserPubKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPubKeys.Marshal(b, m, deterministic)
}
func (m *UserPubKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPubKeys.Merge(m, src)
}
func (m *UserPubKeys) XXX_Size() int {
	return xxx_messageInfo_UserPubKeys.Size(m)
}
func (m *UserPubKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPubKeys.DiscardUnknown(m)
}

var xxx_messageInfo_UserPubKeys proto.InternalMessageInfo

func (m *UserPubKeys) GetUserPubKey() *Key {
	if m != nil {
		return m.UserPubKey
	}
	return nil
}

func (m *UserPubKeys) GetOrgPubKeys() []*Key {
	if m != nil {
		return m.OrgPubKeys
	}
	return nil
}

type Key struct {
	PubKey               string   `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	KeyID                string   `protobuf:"bytes,2,opt,name=KeyID,proto3" json:"KeyID,omitempty"`
	OwnerID              string   `protobuf:"bytes,3,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{5}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Key) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Key) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

type EncryptedKey struct {
	EncKey               string   `protobuf:"bytes,1,opt,name=encKey,proto3" json:"encKey,omitempty"`
	EncryptorID          string   `protobuf:"bytes,2,opt,name=encryptorID,proto3" json:"encryptorID,omitempty"`
	OwnerID              string   `protobuf:"bytes,3,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedKey) Reset()         { *m = EncryptedKey{} }
func (m *EncryptedKey) String() string { return proto.CompactTextString(m) }
func (*EncryptedKey) ProtoMessage()    {}
func (*EncryptedKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{6}
}

func (m *EncryptedKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedKey.Unmarshal(m, b)
}
func (m *EncryptedKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedKey.Marshal(b, m, deterministic)
}
func (m *EncryptedKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedKey.Merge(m, src)
}
func (m *EncryptedKey) XXX_Size() int {
	return xxx_messageInfo_EncryptedKey.Size(m)
}
func (m *EncryptedKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedKey.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedKey proto.InternalMessageInfo

func (m *EncryptedKey) GetEncKey() string {
	if m != nil {
		return m.EncKey
	}
	return ""
}

func (m *EncryptedKey) GetEncryptorID() string {
	if m != nil {
		return m.EncryptorID
	}
	return ""
}

func (m *EncryptedKey) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

type ShareE2EKeysReq struct {
	// list of admin's keys
	SharedKeys           []*SharedKeyE2E `protobuf:"bytes,1,rep,name=sharedKeys,proto3" json:"sharedKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShareE2EKeysReq) Reset()         { *m = ShareE2EKeysReq{} }
func (m *ShareE2EKeysReq) String() string { return proto.CompactTextString(m) }
func (*ShareE2EKeysReq) ProtoMessage()    {}
func (*ShareE2EKeysReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{7}
}

func (m *ShareE2EKeysReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareE2EKeysReq.Unmarshal(m, b)
}
func (m *ShareE2EKeysReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareE2EKeysReq.Marshal(b, m, deterministic)
}
func (m *ShareE2EKeysReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareE2EKeysReq.Merge(m, src)
}
func (m *ShareE2EKeysReq) XXX_Size() int {
	return xxx_messageInfo_ShareE2EKeysReq.Size(m)
}
func (m *ShareE2EKeysReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareE2EKeysReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShareE2EKeysReq proto.InternalMessageInfo

func (m *ShareE2EKeysReq) GetSharedKeys() []*SharedKeyE2E {
	if m != nil {
		return m.SharedKeys
	}
	return nil
}

type SharedKeyE2E struct {
	// The public key of the user.
	UserPubKey string `protobuf:"bytes,1,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	// The encrypted private key of the organization.
	UserEncPriKey string `protobuf:"bytes,2,opt,name=userEncPriKey,proto3" json:"userEncPriKey,omitempty"`
	// The encrypted private key of the user.
	OrgEncPriKey         string   `protobuf:"bytes,3,opt,name=orgEncPriKey,proto3" json:"orgEncPriKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedKeyE2E) Reset()         { *m = SharedKeyE2E{} }
func (m *SharedKeyE2E) String() string { return proto.CompactTextString(m) }
func (*SharedKeyE2E) ProtoMessage()    {}
func (*SharedKeyE2E) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{8}
}

func (m *SharedKeyE2E) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedKeyE2E.Unmarshal(m, b)
}
func (m *SharedKeyE2E) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedKeyE2E.Marshal(b, m, deterministic)
}
func (m *SharedKeyE2E) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedKeyE2E.Merge(m, src)
}
func (m *SharedKeyE2E) XXX_Size() int {
	return xxx_messageInfo_SharedKeyE2E.Size(m)
}
func (m *SharedKeyE2E) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedKeyE2E.DiscardUnknown(m)
}

var xxx_messageInfo_SharedKeyE2E proto.InternalMessageInfo

func (m *SharedKeyE2E) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *SharedKeyE2E) GetUserEncPriKey() string {
	if m != nil {
		return m.UserEncPriKey
	}
	return ""
}

func (m *SharedKeyE2E) GetOrgEncPriKey() string {
	if m != nil {
		return m.OrgEncPriKey
	}
	return ""
}

type ShareE2EKeysResp struct {
	// The list of organization public keys
	PublicKeys           []string `protobuf:"bytes,1,rep,name=publicKeys,proto3" json:"publicKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareE2EKeysResp) Reset()         { *m = ShareE2EKeysResp{} }
func (m *ShareE2EKeysResp) String() string { return proto.CompactTextString(m) }
func (*ShareE2EKeysResp) ProtoMessage()    {}
func (*ShareE2EKeysResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{9}
}

func (m *ShareE2EKeysResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareE2EKeysResp.Unmarshal(m, b)
}
func (m *ShareE2EKeysResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareE2EKeysResp.Marshal(b, m, deterministic)
}
func (m *ShareE2EKeysResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareE2EKeysResp.Merge(m, src)
}
func (m *ShareE2EKeysResp) XXX_Size() int {
	return xxx_messageInfo_ShareE2EKeysResp.Size(m)
}
func (m *ShareE2EKeysResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareE2EKeysResp.DiscardUnknown(m)
}

var xxx_messageInfo_ShareE2EKeysResp proto.InternalMessageInfo

func (m *ShareE2EKeysResp) GetPublicKeys() []string {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type GetKeyE2EReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyE2EReq) Reset()         { *m = GetKeyE2EReq{} }
func (m *GetKeyE2EReq) String() string { return proto.CompactTextString(m) }
func (*GetKeyE2EReq) ProtoMessage()    {}
func (*GetKeyE2EReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{10}
}

func (m *GetKeyE2EReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyE2EReq.Unmarshal(m, b)
}
func (m *GetKeyE2EReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyE2EReq.Marshal(b, m, deterministic)
}
func (m *GetKeyE2EReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyE2EReq.Merge(m, src)
}
func (m *GetKeyE2EReq) XXX_Size() int {
	return xxx_messageInfo_GetKeyE2EReq.Size(m)
}
func (m *GetKeyE2EReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyE2EReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyE2EReq proto.InternalMessageInfo

type GetKeyE2EResp struct {
	KeyID                string   `protobuf:"bytes,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	EncPriKey            string   `protobuf:"bytes,3,opt,name=encPriKey,proto3" json:"encPriKey,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyE2EResp) Reset()         { *m = GetKeyE2EResp{} }
func (m *GetKeyE2EResp) String() string { return proto.CompactTextString(m) }
func (*GetKeyE2EResp) ProtoMessage()    {}
func (*GetKeyE2EResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{11}
}

func (m *GetKeyE2EResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyE2EResp.Unmarshal(m, b)
}
func (m *GetKeyE2EResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyE2EResp.Marshal(b, m, deterministic)
}
func (m *GetKeyE2EResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyE2EResp.Merge(m, src)
}
func (m *GetKeyE2EResp) XXX_Size() int {
	return xxx_messageInfo_GetKeyE2EResp.Size(m)
}
func (m *GetKeyE2EResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyE2EResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyE2EResp proto.InternalMessageInfo

func (m *GetKeyE2EResp) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *GetKeyE2EResp) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *GetKeyE2EResp) GetEncPriKey() string {
	if m != nil {
		return m.EncPriKey
	}
	return ""
}

func (m *GetKeyE2EResp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetKeysE2EReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeysE2EReq) Reset()         { *m = GetKeysE2EReq{} }
func (m *GetKeysE2EReq) String() string { return proto.CompactTextString(m) }
func (*GetKeysE2EReq) ProtoMessage()    {}
func (*GetKeysE2EReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{12}
}

func (m *GetKeysE2EReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeysE2EReq.Unmarshal(m, b)
}
func (m *GetKeysE2EReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeysE2EReq.Marshal(b, m, deterministic)
}
func (m *GetKeysE2EReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeysE2EReq.Merge(m, src)
}
func (m *GetKeysE2EReq) XXX_Size() int {
	return xxx_messageInfo_GetKeysE2EReq.Size(m)
}
func (m *GetKeysE2EReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeysE2EReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeysE2EReq proto.InternalMessageInfo

type KeyE2E struct {
	KeyID                string   `protobuf:"bytes,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	EncPriKey            string   `protobuf:"bytes,3,opt,name=encPriKey,proto3" json:"encPriKey,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyE2E) Reset()         { *m = KeyE2E{} }
func (m *KeyE2E) String() string { return proto.CompactTextString(m) }
func (*KeyE2E) ProtoMessage()    {}
func (*KeyE2E) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{13}
}

func (m *KeyE2E) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyE2E.Unmarshal(m, b)
}
func (m *KeyE2E) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyE2E.Marshal(b, m, deterministic)
}
func (m *KeyE2E) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyE2E.Merge(m, src)
}
func (m *KeyE2E) XXX_Size() int {
	return xxx_messageInfo_KeyE2E.Size(m)
}
func (m *KeyE2E) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyE2E.DiscardUnknown(m)
}

var xxx_messageInfo_KeyE2E proto.InternalMessageInfo

func (m *KeyE2E) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *KeyE2E) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *KeyE2E) GetEncPriKey() string {
	if m != nil {
		return m.EncPriKey
	}
	return ""
}

func (m *KeyE2E) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetKeysE2EResp struct {
	KeyList              []*KeyE2E `protobuf:"bytes,1,rep,name=keyList,proto3" json:"keyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetKeysE2EResp) Reset()         { *m = GetKeysE2EResp{} }
func (m *GetKeysE2EResp) String() string { return proto.CompactTextString(m) }
func (*GetKeysE2EResp) ProtoMessage()    {}
func (*GetKeysE2EResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{14}
}

func (m *GetKeysE2EResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeysE2EResp.Unmarshal(m, b)
}
func (m *GetKeysE2EResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeysE2EResp.Marshal(b, m, deterministic)
}
func (m *GetKeysE2EResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeysE2EResp.Merge(m, src)
}
func (m *GetKeysE2EResp) XXX_Size() int {
	return xxx_messageInfo_GetKeysE2EResp.Size(m)
}
func (m *GetKeysE2EResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeysE2EResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeysE2EResp proto.InternalMessageInfo

func (m *GetKeysE2EResp) GetKeyList() []*KeyE2E {
	if m != nil {
		return m.KeyList
	}
	return nil
}

type UpdateKeyE2EReq struct {
	PubKey               string   `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	EncPriKey            string   `protobuf:"bytes,2,opt,name=encPriKey,proto3" json:"encPriKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateKeyE2EReq) Reset()         { *m = UpdateKeyE2EReq{} }
func (m *UpdateKeyE2EReq) String() string { return proto.CompactTextString(m) }
func (*UpdateKeyE2EReq) ProtoMessage()    {}
func (*UpdateKeyE2EReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{15}
}

func (m *UpdateKeyE2EReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateKeyE2EReq.Unmarshal(m, b)
}
func (m *UpdateKeyE2EReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateKeyE2EReq.Marshal(b, m, deterministic)
}
func (m *UpdateKeyE2EReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateKeyE2EReq.Merge(m, src)
}
func (m *UpdateKeyE2EReq) XXX_Size() int {
	return xxx_messageInfo_UpdateKeyE2EReq.Size(m)
}
func (m *UpdateKeyE2EReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateKeyE2EReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateKeyE2EReq proto.InternalMessageInfo

func (m *UpdateKeyE2EReq) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *UpdateKeyE2EReq) GetEncPriKey() string {
	if m != nil {
		return m.EncPriKey
	}
	return ""
}

type UpdateKeyE2EResp struct {
	KeyID                string   `protobuf:"bytes,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateKeyE2EResp) Reset()         { *m = UpdateKeyE2EResp{} }
func (m *UpdateKeyE2EResp) String() string { return proto.CompactTextString(m) }
func (*UpdateKeyE2EResp) ProtoMessage()    {}
func (*UpdateKeyE2EResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{16}
}

func (m *UpdateKeyE2EResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateKeyE2EResp.Unmarshal(m, b)
}
func (m *UpdateKeyE2EResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateKeyE2EResp.Marshal(b, m, deterministic)
}
func (m *UpdateKeyE2EResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateKeyE2EResp.Merge(m, src)
}
func (m *UpdateKeyE2EResp) XXX_Size() int {
	return xxx_messageInfo_UpdateKeyE2EResp.Size(m)
}
func (m *UpdateKeyE2EResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateKeyE2EResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateKeyE2EResp proto.InternalMessageInfo

func (m *UpdateKeyE2EResp) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

type GetFileKeysE2EReq struct {
	KeyID                string   `protobuf:"bytes,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileKeysE2EReq) Reset()         { *m = GetFileKeysE2EReq{} }
func (m *GetFileKeysE2EReq) String() string { return proto.CompactTextString(m) }
func (*GetFileKeysE2EReq) ProtoMessage()    {}
func (*GetFileKeysE2EReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{17}
}

func (m *GetFileKeysE2EReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileKeysE2EReq.Unmarshal(m, b)
}
func (m *GetFileKeysE2EReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileKeysE2EReq.Marshal(b, m, deterministic)
}
func (m *GetFileKeysE2EReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileKeysE2EReq.Merge(m, src)
}
func (m *GetFileKeysE2EReq) XXX_Size() int {
	return xxx_messageInfo_GetFileKeysE2EReq.Size(m)
}
func (m *GetFileKeysE2EReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileKeysE2EReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileKeysE2EReq proto.InternalMessageInfo

func (m *GetFileKeysE2EReq) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *GetFileKeysE2EReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetFileKeysE2EReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type DocEncFileKeyE2E struct {
	KeyID                string   `protobuf:"bytes,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	EncFileKey           string   `protobuf:"bytes,2,opt,name=encFileKey,proto3" json:"encFileKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocEncFileKeyE2E) Reset()         { *m = DocEncFileKeyE2E{} }
func (m *DocEncFileKeyE2E) String() string { return proto.CompactTextString(m) }
func (*DocEncFileKeyE2E) ProtoMessage()    {}
func (*DocEncFileKeyE2E) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{18}
}

func (m *DocEncFileKeyE2E) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocEncFileKeyE2E.Unmarshal(m, b)
}
func (m *DocEncFileKeyE2E) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocEncFileKeyE2E.Marshal(b, m, deterministic)
}
func (m *DocEncFileKeyE2E) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocEncFileKeyE2E.Merge(m, src)
}
func (m *DocEncFileKeyE2E) XXX_Size() int {
	return xxx_messageInfo_DocEncFileKeyE2E.Size(m)
}
func (m *DocEncFileKeyE2E) XXX_DiscardUnknown() {
	xxx_messageInfo_DocEncFileKeyE2E.DiscardUnknown(m)
}

var xxx_messageInfo_DocEncFileKeyE2E proto.InternalMessageInfo

func (m *DocEncFileKeyE2E) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *DocEncFileKeyE2E) GetEncFileKey() string {
	if m != nil {
		return m.EncFileKey
	}
	return ""
}

type GetFileKeysE2EResp struct {
	// The list of user encrypted file keys
	EncFileKeyList       []*DocEncFileKeyE2E `protobuf:"bytes,1,rep,name=encFileKeyList,proto3" json:"encFileKeyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetFileKeysE2EResp) Reset()         { *m = GetFileKeysE2EResp{} }
func (m *GetFileKeysE2EResp) String() string { return proto.CompactTextString(m) }
func (*GetFileKeysE2EResp) ProtoMessage()    {}
func (*GetFileKeysE2EResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{19}
}

func (m *GetFileKeysE2EResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileKeysE2EResp.Unmarshal(m, b)
}
func (m *GetFileKeysE2EResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileKeysE2EResp.Marshal(b, m, deterministic)
}
func (m *GetFileKeysE2EResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileKeysE2EResp.Merge(m, src)
}
func (m *GetFileKeysE2EResp) XXX_Size() int {
	return xxx_messageInfo_GetFileKeysE2EResp.Size(m)
}
func (m *GetFileKeysE2EResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileKeysE2EResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileKeysE2EResp proto.InternalMessageInfo

func (m *GetFileKeysE2EResp) GetEncFileKeyList() []*DocEncFileKeyE2E {
	if m != nil {
		return m.EncFileKeyList
	}
	return nil
}

type UpdateFileKeysE2EReq struct {
	// The list of newly encrypted file keys
	NewEncFileKeyList    []*DocEncFileKeyE2E `protobuf:"bytes,1,rep,name=newEncFileKeyList,proto3" json:"newEncFileKeyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdateFileKeysE2EReq) Reset()         { *m = UpdateFileKeysE2EReq{} }
func (m *UpdateFileKeysE2EReq) String() string { return proto.CompactTextString(m) }
func (*UpdateFileKeysE2EReq) ProtoMessage()    {}
func (*UpdateFileKeysE2EReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{20}
}

func (m *UpdateFileKeysE2EReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileKeysE2EReq.Unmarshal(m, b)
}
func (m *UpdateFileKeysE2EReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileKeysE2EReq.Marshal(b, m, deterministic)
}
func (m *UpdateFileKeysE2EReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileKeysE2EReq.Merge(m, src)
}
func (m *UpdateFileKeysE2EReq) XXX_Size() int {
	return xxx_messageInfo_UpdateFileKeysE2EReq.Size(m)
}
func (m *UpdateFileKeysE2EReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileKeysE2EReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileKeysE2EReq proto.InternalMessageInfo

func (m *UpdateFileKeysE2EReq) GetNewEncFileKeyList() []*DocEncFileKeyE2E {
	if m != nil {
		return m.NewEncFileKeyList
	}
	return nil
}

type UpdateFileKeysE2EResp struct {
	Modified             int64    `protobuf:"varint,1,opt,name=modified,proto3" json:"modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileKeysE2EResp) Reset()         { *m = UpdateFileKeysE2EResp{} }
func (m *UpdateFileKeysE2EResp) String() string { return proto.CompactTextString(m) }
func (*UpdateFileKeysE2EResp) ProtoMessage()    {}
func (*UpdateFileKeysE2EResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{21}
}

func (m *UpdateFileKeysE2EResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileKeysE2EResp.Unmarshal(m, b)
}
func (m *UpdateFileKeysE2EResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileKeysE2EResp.Marshal(b, m, deterministic)
}
func (m *UpdateFileKeysE2EResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileKeysE2EResp.Merge(m, src)
}
func (m *UpdateFileKeysE2EResp) XXX_Size() int {
	return xxx_messageInfo_UpdateFileKeysE2EResp.Size(m)
}
func (m *UpdateFileKeysE2EResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileKeysE2EResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileKeysE2EResp proto.InternalMessageInfo

func (m *UpdateFileKeysE2EResp) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

type UpdateE2EKeyReq struct {
	// The public key of the user.
	UserPubKey string `protobuf:"bytes,1,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	// The encrypted private key of the organization.
	UserEncPriKey        string   `protobuf:"bytes,2,opt,name=userEncPriKey,proto3" json:"userEncPriKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateE2EKeyReq) Reset()         { *m = UpdateE2EKeyReq{} }
func (m *UpdateE2EKeyReq) String() string { return proto.CompactTextString(m) }
func (*UpdateE2EKeyReq) ProtoMessage()    {}
func (*UpdateE2EKeyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{22}
}

func (m *UpdateE2EKeyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateE2EKeyReq.Unmarshal(m, b)
}
func (m *UpdateE2EKeyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateE2EKeyReq.Marshal(b, m, deterministic)
}
func (m *UpdateE2EKeyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateE2EKeyReq.Merge(m, src)
}
func (m *UpdateE2EKeyReq) XXX_Size() int {
	return xxx_messageInfo_UpdateE2EKeyReq.Size(m)
}
func (m *UpdateE2EKeyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateE2EKeyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateE2EKeyReq proto.InternalMessageInfo

func (m *UpdateE2EKeyReq) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *UpdateE2EKeyReq) GetUserEncPriKey() string {
	if m != nil {
		return m.UserEncPriKey
	}
	return ""
}

type UpdateE2EKeyResp struct {
	// The keyID of newly saved E2E key
	KeyID                string   `protobuf:"bytes,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateE2EKeyResp) Reset()         { *m = UpdateE2EKeyResp{} }
func (m *UpdateE2EKeyResp) String() string { return proto.CompactTextString(m) }
func (*UpdateE2EKeyResp) ProtoMessage()    {}
func (*UpdateE2EKeyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{23}
}

func (m *UpdateE2EKeyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateE2EKeyResp.Unmarshal(m, b)
}
func (m *UpdateE2EKeyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateE2EKeyResp.Marshal(b, m, deterministic)
}
func (m *UpdateE2EKeyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateE2EKeyResp.Merge(m, src)
}
func (m *UpdateE2EKeyResp) XXX_Size() int {
	return xxx_messageInfo_UpdateE2EKeyResp.Size(m)
}
func (m *UpdateE2EKeyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateE2EKeyResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateE2EKeyResp proto.InternalMessageInfo

func (m *UpdateE2EKeyResp) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *UpdateE2EKeyResp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*EnableE2EReq)(nil), "proto.EnableE2EReq")
	proto.RegisterType((*EnableE2EResp)(nil), "proto.EnableE2EResp")
	proto.RegisterType((*GetOwnKeysReq)(nil), "proto.GetOwnKeysReq")
	proto.RegisterType((*GetOwnKeysResp)(nil), "proto.GetOwnKeysResp")
	proto.RegisterType((*UserPubKeys)(nil), "proto.UserPubKeys")
	proto.RegisterType((*Key)(nil), "proto.Key")
	proto.RegisterType((*EncryptedKey)(nil), "proto.EncryptedKey")
	proto.RegisterType((*ShareE2EKeysReq)(nil), "proto.ShareE2EKeysReq")
	proto.RegisterType((*SharedKeyE2E)(nil), "proto.SharedKeyE2e")
	proto.RegisterType((*ShareE2EKeysResp)(nil), "proto.ShareE2EKeysResp")
	proto.RegisterType((*GetKeyE2EReq)(nil), "proto.GetKeyE2eReq")
	proto.RegisterType((*GetKeyE2EResp)(nil), "proto.GetKeyE2eResp")
	proto.RegisterType((*GetKeysE2EReq)(nil), "proto.GetKeysE2eReq")
	proto.RegisterType((*KeyE2E)(nil), "proto.KeyE2e")
	proto.RegisterType((*GetKeysE2EResp)(nil), "proto.GetKeysE2eResp")
	proto.RegisterType((*UpdateKeyE2EReq)(nil), "proto.UpdateKeyE2eReq")
	proto.RegisterType((*UpdateKeyE2EResp)(nil), "proto.UpdateKeyE2eResp")
	proto.RegisterType((*GetFileKeysE2EReq)(nil), "proto.GetFileKeysE2eReq")
	proto.RegisterType((*DocEncFileKeyE2E)(nil), "proto.DocEncFileKeyE2E")
	proto.RegisterType((*GetFileKeysE2EResp)(nil), "proto.GetFileKeysE2eResp")
	proto.RegisterType((*UpdateFileKeysE2EReq)(nil), "proto.UpdateFileKeysE2eReq")
	proto.RegisterType((*UpdateFileKeysE2EResp)(nil), "proto.UpdateFileKeysE2eResp")
	proto.RegisterType((*UpdateE2EKeyReq)(nil), "proto.UpdateE2EKeyReq")
	proto.RegisterType((*UpdateE2EKeyResp)(nil), "proto.UpdateE2EKeyResp")
}

func init() { proto.RegisterFile("encryption.proto", fileDescriptor_8293a649ce9418c6) }

var fileDescriptor_8293a649ce9418c6 = []byte{
	// 1133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdf, 0x6e, 0xdc, 0xc4,
	0x17, 0xd6, 0xec, 0x36, 0xe9, 0x2f, 0x27, 0xff, 0xa7, 0x69, 0x13, 0x55, 0xd5, 0x4f, 0xd6, 0x08,
	0x89, 0xca, 0xda, 0xfc, 0x73, 0xb8, 0xf2, 0x05, 0xd4, 0x25, 0x4e, 0x82, 0x96, 0xa8, 0xd5, 0x56,
	0x11, 0x48, 0x51, 0x0a, 0xde, 0xf5, 0x64, 0x59, 0x25, 0xb1, 0x1d, 0xdb, 0x69, 0x88, 0xac, 0xbd,
	0xe2, 0xa2, 0x95, 0xb8, 0xc2, 0x17, 0x5c, 0x22, 0xc4, 0x1b, 0x70, 0x87, 0xc4, 0x25, 0xbc, 0x07,
	0x4f, 0x00, 0xcf, 0x80, 0x66, 0x3c, 0xf6, 0xcc, 0x78, 0x77, 0x21, 0x48, 0x55, 0xd5, 0x8b, 0xf5,
	0xf9, 0xe6, 0xcc, 0x99, 0x33, 0xdf, 0xf9, 0xce, 0x99, 0x06, 0x96, 0x68, 0xd0, 0x8b, 0x6f, 0xa2,
	0x74, 0x10, 0x06, 0x1b, 0x51, 0x1c, 0xa6, 0x21, 0x9e, 0xe2, 0x3f, 0x0f, 0x5b, 0xfc, 0xa7, 0xb7,
	0xde, 0xa7, 0xc1, 0x7a, 0x72, 0xed, 0xf5, 0xfb, 0x34, 0xde, 0x0c, 0xb9, 0x5f, 0xb2, 0xe9, 0x05,
	0x41, 0x98, 0x7a, 0xfc, 0xbb, 0xd8, 0x44, 0x7e, 0x6d, 0xc0, 0x9c, 0x1b, 0x78, 0xdd, 0x73, 0xea,
	0x5a, 0x6e, 0x87, 0x5e, 0xe2, 0x47, 0x30, 0x13, 0xc6, 0xfd, 0xe7, 0x57, 0xdd, 0x36, 0xbd, 0x59,
	0x43, 0x06, 0x7a, 0x3c, 0xd3, 0x91, 0x00, 0xfe, 0x3f, 0xc0, 0x55, 0x42, 0x63, 0xb1, 0xdc, 0xe0,
	0xcb, 0x0a, 0x82, 0xdf, 0x83, 0x79, 0x66, 0xb9, 0x41, 0xef, 0x79, 0x3c, 0x60, 0x2e, 0x4d, 0xee,
	0xa2, 0x83, 0x98, 0xc0, 0x5c, 0x18, 0xf7, 0xa5, 0xd3, 0x1d, 0xee, 0xa4, 0x61, 0xf6, 0x4f, 0x28,
	0x77, 0x7e, 0x40, 0xb0, 0x60, 0x6a, 0xe9, 0x59, 0xdf, 0x22, 0xfc, 0x06, 0x65, 0xa4, 0xca, 0x88,
	0xd8, 0x06, 0x49, 0x69, 0x92, 0x3e, 0xab, 0x80, 0x96, 0x41, 0x64, 0x42, 0xe5, 0xf2, 0x91, 0x44,
	0xc4, 0x7a, 0x75, 0x92, 0xea, 0x22, 0xc1, 0x96, 0x41, 0xd4, 0x74, 0x94, 0x63, 0x24, 0x36, 0x24,
	0x2f, 0x61, 0x5e, 0xc9, 0x2e, 0x89, 0x18, 0x3f, 0xd1, 0x55, 0xf7, 0x7c, 0xd0, 0x6b, 0xd3, 0x9b,
	0x64, 0x0d, 0x19, 0x4d, 0xc6, 0x8f, 0x44, 0xec, 0xf5, 0xdc, 0x31, 0x61, 0xd1, 0xd4, 0x77, 0x59,
	0xab, 0xf8, 0x7e, 0x46, 0x2a, 0xaf, 0x4f, 0x07, 0x49, 0x4a, 0x6c, 0xe3, 0xf8, 0x64, 0x48, 0x16,
	0x61, 0x7e, 0x9f, 0xa6, 0xcf, 0xae, 0x03, 0xb6, 0xb9, 0x43, 0x2f, 0xc9, 0x9f, 0x08, 0x16, 0x54,
	0xa4, 0x38, 0x92, 0xf2, 0x94, 0x5e, 0xc9, 0x8a, 0x29, 0x08, 0x36, 0x60, 0x56, 0x48, 0x25, 0x8c,
	0x3f, 0xd9, 0x15, 0x35, 0x53, 0x21, 0xfc, 0x01, 0xcc, 0x4a, 0xc6, 0x12, 0x5e, 0xb2, 0x59, 0x0b,
	0x17, 0x02, 0xd9, 0x90, 0xcc, 0x25, 0x1d, 0xd5, 0xcd, 0xee, 0xe5, 0xce, 0x97, 0xec, 0x2a, 0x5a,
	0x82, 0xd6, 0x21, 0x6e, 0x67, 0xe4, 0xcc, 0x3f, 0x3d, 0xa4, 0xa9, 0xc7, 0x48, 0x3b, 0xf3, 0x4f,
	0x77, 0xbd, 0xd4, 0x63, 0x7c, 0x46, 0x45, 0x42, 0x0c, 0x15, 0x9f, 0xd5, 0x4a, 0x55, 0xab, 0x8a,
	0x04, 0xbe, 0x34, 0x24, 0x14, 0x66, 0x95, 0x04, 0xb0, 0xa9, 0xc9, 0x0f, 0xf1, 0x44, 0x41, 0x24,
	0xda, 0xa6, 0x37, 0x9a, 0x14, 0x4d, 0x80, 0x4a, 0x25, 0xc9, 0x5a, 0xc3, 0x68, 0xd6, 0x7d, 0xe5,
	0x2a, 0x39, 0x84, 0x26, 0xdb, 0xf2, 0x00, 0xa6, 0x23, 0x55, 0xf8, 0xc2, 0xc2, 0x2b, 0x30, 0xd5,
	0xa6, 0x37, 0x15, 0x79, 0x85, 0x81, 0xd7, 0xe0, 0x6e, 0x78, 0x1d, 0x50, 0x46, 0x6a, 0xa1, 0xf2,
	0xd2, 0x24, 0x5d, 0xd6, 0x53, 0x9c, 0x5f, 0xea, 0x8b, 0xb8, 0x34, 0xe8, 0x29, 0x71, 0x0b, 0xeb,
	0x16, 0xa5, 0x99, 0x7c, 0xc6, 0x1f, 0x08, 0x16, 0x5f, 0x7c, 0xe5, 0xc5, 0x4c, 0x44, 0x82, 0x7c,
	0xbc, 0x03, 0x90, 0x30, 0xc8, 0xaf, 0xd4, 0x37, 0x6b, 0xdd, 0x13, 0x57, 0x7e, 0x51, 0x2e, 0xb8,
	0x16, 0xed, 0x28, 0x6e, 0xf6, 0xf7, 0x28, 0x77, 0x72, 0x04, 0xcb, 0x66, 0x3d, 0x9c, 0x35, 0xc4,
	0x59, 0x46, 0xa4, 0x27, 0xb1, 0x8f, 0xb3, 0x77, 0xd6, 0x5a, 0x27, 0x43, 0xf2, 0x35, 0xcc, 0xa9,
	0x49, 0xd7, 0x66, 0x0f, 0xfa, 0xf7, 0xd9, 0xd3, 0xb8, 0xcd, 0xec, 0x69, 0x8e, 0xce, 0x1e, 0xe2,
	0xc3, 0x92, 0xce, 0xc5, 0x2d, 0x3a, 0x7b, 0x2b, 0x77, 0xd6, 0x01, 0x9b, 0x23, 0x1b, 0x27, 0x37,
	0xf7, 0x02, 0xcc, 0xed, 0xd3, 0x54, 0x54, 0x84, 0x5e, 0x92, 0xbf, 0x10, 0xef, 0xf6, 0x12, 0x48,
	0x22, 0xa6, 0xbb, 0x33, 0xae, 0xbb, 0xe2, 0xb2, 0x85, 0xa1, 0xa8, 0xb4, 0xa1, 0xa9, 0xf4, 0x11,
	0xcc, 0xd0, 0xda, 0xb5, 0x24, 0xc0, 0x94, 0xf4, 0x8a, 0xc6, 0xc9, 0x20, 0x0c, 0xc4, 0xb8, 0x2d,
	0x4d, 0xfb, 0x3a, 0x77, 0x52, 0xd1, 0xc8, 0xf2, 0x6c, 0xcb, 0xc3, 0x5f, 0x64, 0x84, 0x1f, 0xc8,
	0x0a, 0xe4, 0x7b, 0xe5, 0x3f, 0xbd, 0x5f, 0x55, 0x9c, 0x50, 0xb5, 0xa4, 0xfa, 0x0e, 0x71, 0x16,
	0x5b, 0x28, 0x3f, 0xcb, 0xe9, 0xc6, 0x88, 0x12, 0x0c, 0x04, 0x30, 0x2d, 0x6a, 0xfd, 0x4e, 0x6e,
	0x4e, 0x7e, 0x2b, 0xa6, 0x69, 0x95, 0x41, 0x12, 0xe1, 0xf7, 0xe1, 0xee, 0x59, 0x51, 0x25, 0xd1,
	0x3f, 0xf3, 0x72, 0x64, 0x30, 0x9f, 0x72, 0xd5, 0x7e, 0x8d, 0x72, 0xe7, 0x1b, 0x04, 0x4b, 0x66,
	0x2d, 0x82, 0x15, 0xe2, 0x0b, 0x4e, 0x5c, 0x51, 0xe9, 0xe3, 0xb7, 0x45, 0xa2, 0xd1, 0x1a, 0x4b,
	0xe2, 0xc9, 0x90, 0x7c, 0x87, 0x60, 0xf1, 0x28, 0xf2, 0xbd, 0x94, 0x56, 0x5a, 0x9a, 0x38, 0xc9,
	0x34, 0xa6, 0x1a, 0x35, 0xa6, 0xec, 0x83, 0xdc, 0x71, 0xd9, 0x20, 0xa8, 0x45, 0xb3, 0xb6, 0xf0,
	0x46, 0xa6, 0x0f, 0x69, 0xd1, 0xc7, 0x5a, 0xb2, 0x54, 0x79, 0x18, 0x3f, 0x83, 0x25, 0x3d, 0xc8,
	0x24, 0x35, 0x17, 0x2f, 0x22, 0x36, 0x47, 0xdc, 0xad, 0x15, 0x8c, 0x15, 0xee, 0x8a, 0x8f, 0x21,
	0xf9, 0x11, 0xc1, 0xf2, 0x3e, 0x4d, 0xf7, 0x06, 0xe7, 0x54, 0x0a, 0x67, 0x82, 0x5c, 0x56, 0x60,
	0xea, 0x7c, 0x70, 0x31, 0x48, 0xf9, 0x45, 0x9b, 0x9d, 0xc2, 0xc0, 0x18, 0xee, 0x44, 0x5e, 0x9f,
	0x72, 0x9d, 0x34, 0x3b, 0xfc, 0xdb, 0x6e, 0xe7, 0xce, 0x01, 0xdc, 0x33, 0x47, 0x23, 0x5b, 0xdb,
	0x78, 0x73, 0x24, 0x8b, 0x96, 0x41, 0x78, 0x28, 0x86, 0x6c, 0x6f, 0x6d, 0xf1, 0x62, 0x7a, 0x7d,
	0xca, 0x4d, 0x32, 0x24, 0x07, 0xb0, 0xb4, 0x1b, 0xf6, 0xdc, 0xa0, 0x27, 0x42, 0xb9, 0x96, 0x3b,
	0x21, 0xc1, 0xe2, 0xe9, 0x16, 0x6e, 0xe5, 0xff, 0xa6, 0x24, 0x42, 0x7e, 0x41, 0x80, 0xeb, 0x29,
	0x25, 0x11, 0xfe, 0x08, 0x16, 0xa4, 0x93, 0x22, 0xd5, 0x55, 0x21, 0xd5, 0xfa, 0xe9, 0x9d, 0x9a,
	0xbb, 0xed, 0xe5, 0xce, 0x4b, 0x58, 0x31, 0xc7, 0xc4, 0xb6, 0xf6, 0xf0, 0x6e, 0x46, 0x74, 0x77,
	0x36, 0xae, 0xc6, 0x71, 0xa0, 0x24, 0x6a, 0x6b, 0x16, 0x13, 0xe5, 0xef, 0x08, 0x56, 0x8a, 0x92,
	0xd6, 0x4a, 0xe5, 0xc2, 0x72, 0x40, 0xaf, 0xdd, 0xff, 0x94, 0xff, 0xe8, 0x0e, 0x9b, 0xe6, 0x4e,
	0x17, 0x1e, 0x98, 0x63, 0xcf, 0xb0, 0x0e, 0xf0, 0x5e, 0x46, 0x46, 0xf6, 0xe8, 0xcd, 0x78, 0xbb,
	0x6b, 0xf8, 0x70, 0x7f, 0xcc, 0x09, 0x49, 0x84, 0x1f, 0xc2, 0xff, 0x2e, 0x42, 0x7f, 0x70, 0x3a,
	0xa0, 0x3e, 0xaf, 0x69, 0xb3, 0x53, 0xd9, 0xf6, 0x66, 0xee, 0xb4, 0x60, 0xd5, 0x1c, 0xbf, 0xd3,
	0x5a, 0xc6, 0x8b, 0x19, 0x29, 0x7d, 0x89, 0x6d, 0x6c, 0x0f, 0xc9, 0xcf, 0x55, 0x07, 0x17, 0x0f,
	0x07, 0xe3, 0xe9, 0xad, 0xbc, 0x76, 0xf6, 0xe7, 0xb9, 0x73, 0x24, 0x3b, 0xba, 0x8a, 0x6e, 0x3d,
	0xc1, 0x1f, 0xd6, 0xdf, 0xf2, 0xab, 0x7f, 0x7e, 0xc7, 0x75, 0x60, 0x48, 0x5e, 0xa3, 0xb2, 0xc5,
	0xcb, 0xa8, 0x13, 0x1f, 0x2c, 0x65, 0x00, 0x37, 0xf4, 0xa7, 0xe7, 0xe3, 0xdc, 0x79, 0x22, 0x9b,
	0x5f, 0x06, 0xb2, 0x4c, 0xfc, 0x78, 0x5c, 0xad, 0xc6, 0x4d, 0xc0, 0xa7, 0x3b, 0x40, 0x7a, 0xe1,
	0xc5, 0x46, 0x92, 0xc6, 0x61, 0xd0, 0x4f, 0xbc, 0xf3, 0x54, 0x7c, 0xfa, 0x61, 0x6f, 0x23, 0xf1,
	0xcf, 0x0a, 0x51, 0x3d, 0x05, 0xb7, 0xfa, 0x7b, 0xe9, 0x0d, 0x42, 0xdd, 0x69, 0x8e, 0xee, 0xfc,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x72, 0xbe, 0xe1, 0x51, 0x47, 0x0d, 0x00, 0x00,
}
