// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encryption.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessType int32

const (
	AccessType_ORG     AccessType = 0
	AccessType_USER    AccessType = 1
	AccessType_GROUP   AccessType = 2
	AccessType_UNKNOWN AccessType = 19
)

var AccessType_name = map[int32]string{
	0:  "ORG",
	1:  "USER",
	2:  "GROUP",
	19: "UNKNOWN",
}

var AccessType_value = map[string]int32{
	"ORG":     0,
	"USER":    1,
	"GROUP":   2,
	"UNKNOWN": 19,
}

func (x AccessType) String() string {
	return proto.EnumName(AccessType_name, int32(x))
}

func (AccessType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{0}
}

type Key struct {
	Key                  string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	KeyID                string     `protobuf:"bytes,2,opt,name=keyID,proto3" json:"keyID,omitempty"`
	OwnerID              string     `protobuf:"bytes,3,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	OwnerType            AccessType `protobuf:"varint,4,opt,name=ownerType,proto3,enum=proto.AccessType" json:"ownerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Key) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Key) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *Key) GetOwnerType() AccessType {
	if m != nil {
		return m.OwnerType
	}
	return AccessType_ORG
}

type EncryptedKey struct {
	EncKey               string   `protobuf:"bytes,1,opt,name=encKey,proto3" json:"encKey,omitempty"`
	EncryptorID          string   `protobuf:"bytes,2,opt,name=encryptorID,proto3" json:"encryptorID,omitempty"`
	EncryptorVersion     int32    `protobuf:"varint,3,opt,name=encryptorVersion,proto3" json:"encryptorVersion,omitempty"`
	KeyID                string   `protobuf:"bytes,4,opt,name=keyID,proto3" json:"keyID,omitempty"`
	KeyVersion           int32    `protobuf:"varint,5,opt,name=keyVersion,proto3" json:"keyVersion,omitempty"`
	OwnerID              string   `protobuf:"bytes,6,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedKey) Reset()         { *m = EncryptedKey{} }
func (m *EncryptedKey) String() string { return proto.CompactTextString(m) }
func (*EncryptedKey) ProtoMessage()    {}
func (*EncryptedKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{1}
}

func (m *EncryptedKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedKey.Unmarshal(m, b)
}
func (m *EncryptedKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedKey.Marshal(b, m, deterministic)
}
func (m *EncryptedKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedKey.Merge(m, src)
}
func (m *EncryptedKey) XXX_Size() int {
	return xxx_messageInfo_EncryptedKey.Size(m)
}
func (m *EncryptedKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedKey.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedKey proto.InternalMessageInfo

func (m *EncryptedKey) GetEncKey() string {
	if m != nil {
		return m.EncKey
	}
	return ""
}

func (m *EncryptedKey) GetEncryptorID() string {
	if m != nil {
		return m.EncryptorID
	}
	return ""
}

func (m *EncryptedKey) GetEncryptorVersion() int32 {
	if m != nil {
		return m.EncryptorVersion
	}
	return 0
}

func (m *EncryptedKey) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *EncryptedKey) GetKeyVersion() int32 {
	if m != nil {
		return m.KeyVersion
	}
	return 0
}

func (m *EncryptedKey) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

type GetUserPrivateKeysReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserPrivateKeysReq) Reset()         { *m = GetUserPrivateKeysReq{} }
func (m *GetUserPrivateKeysReq) String() string { return proto.CompactTextString(m) }
func (*GetUserPrivateKeysReq) ProtoMessage()    {}
func (*GetUserPrivateKeysReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{2}
}

func (m *GetUserPrivateKeysReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPrivateKeysReq.Unmarshal(m, b)
}
func (m *GetUserPrivateKeysReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPrivateKeysReq.Marshal(b, m, deterministic)
}
func (m *GetUserPrivateKeysReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPrivateKeysReq.Merge(m, src)
}
func (m *GetUserPrivateKeysReq) XXX_Size() int {
	return xxx_messageInfo_GetUserPrivateKeysReq.Size(m)
}
func (m *GetUserPrivateKeysReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPrivateKeysReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPrivateKeysReq proto.InternalMessageInfo

type GetUserPrivateKeysResp struct {
	// List of encrypted asymmetric keys to be decrypted, encrypted with client new passwordKey
	EncryptedKeys        []*EncryptedKey `protobuf:"bytes,1,rep,name=encryptedKeys,proto3" json:"encryptedKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserPrivateKeysResp) Reset()         { *m = GetUserPrivateKeysResp{} }
func (m *GetUserPrivateKeysResp) String() string { return proto.CompactTextString(m) }
func (*GetUserPrivateKeysResp) ProtoMessage()    {}
func (*GetUserPrivateKeysResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{3}
}

func (m *GetUserPrivateKeysResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPrivateKeysResp.Unmarshal(m, b)
}
func (m *GetUserPrivateKeysResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPrivateKeysResp.Marshal(b, m, deterministic)
}
func (m *GetUserPrivateKeysResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPrivateKeysResp.Merge(m, src)
}
func (m *GetUserPrivateKeysResp) XXX_Size() int {
	return xxx_messageInfo_GetUserPrivateKeysResp.Size(m)
}
func (m *GetUserPrivateKeysResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPrivateKeysResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPrivateKeysResp proto.InternalMessageInfo

func (m *GetUserPrivateKeysResp) GetEncryptedKeys() []*EncryptedKey {
	if m != nil {
		return m.EncryptedKeys
	}
	return nil
}

type SetUserKdfMetadataReq struct {
	// new kdfMeta data
	KdfMeta string `protobuf:"bytes,1,opt,name=kdfMeta,proto3" json:"kdfMeta,omitempty"`
	// List of re-encrypted asymmetric keys with the new passwordKey,
	EncryptedKeys        []*EncryptedKey `protobuf:"bytes,2,rep,name=encryptedKeys,proto3" json:"encryptedKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetUserKdfMetadataReq) Reset()         { *m = SetUserKdfMetadataReq{} }
func (m *SetUserKdfMetadataReq) String() string { return proto.CompactTextString(m) }
func (*SetUserKdfMetadataReq) ProtoMessage()    {}
func (*SetUserKdfMetadataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{4}
}

func (m *SetUserKdfMetadataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserKdfMetadataReq.Unmarshal(m, b)
}
func (m *SetUserKdfMetadataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserKdfMetadataReq.Marshal(b, m, deterministic)
}
func (m *SetUserKdfMetadataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserKdfMetadataReq.Merge(m, src)
}
func (m *SetUserKdfMetadataReq) XXX_Size() int {
	return xxx_messageInfo_SetUserKdfMetadataReq.Size(m)
}
func (m *SetUserKdfMetadataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserKdfMetadataReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserKdfMetadataReq proto.InternalMessageInfo

func (m *SetUserKdfMetadataReq) GetKdfMeta() string {
	if m != nil {
		return m.KdfMeta
	}
	return ""
}

func (m *SetUserKdfMetadataReq) GetEncryptedKeys() []*EncryptedKey {
	if m != nil {
		return m.EncryptedKeys
	}
	return nil
}

type SetUserKdfMetadataResp struct {
	// Whether or not the operation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Whether or not the operation needs restart
	Restart bool `protobuf:"varint,2,opt,name=restart,proto3" json:"restart,omitempty"`
	// The keyID of the new passwordKey
	KeyID                string   `protobuf:"bytes,3,opt,name=keyID,proto3" json:"keyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserKdfMetadataResp) Reset()         { *m = SetUserKdfMetadataResp{} }
func (m *SetUserKdfMetadataResp) String() string { return proto.CompactTextString(m) }
func (*SetUserKdfMetadataResp) ProtoMessage()    {}
func (*SetUserKdfMetadataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293a649ce9418c6, []int{5}
}

func (m *SetUserKdfMetadataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserKdfMetadataResp.Unmarshal(m, b)
}
func (m *SetUserKdfMetadataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserKdfMetadataResp.Marshal(b, m, deterministic)
}
func (m *SetUserKdfMetadataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserKdfMetadataResp.Merge(m, src)
}
func (m *SetUserKdfMetadataResp) XXX_Size() int {
	return xxx_messageInfo_SetUserKdfMetadataResp.Size(m)
}
func (m *SetUserKdfMetadataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserKdfMetadataResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserKdfMetadataResp proto.InternalMessageInfo

func (m *SetUserKdfMetadataResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SetUserKdfMetadataResp) GetRestart() bool {
	if m != nil {
		return m.Restart
	}
	return false
}

func (m *SetUserKdfMetadataResp) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.AccessType", AccessType_name, AccessType_value)
	proto.RegisterType((*Key)(nil), "proto.Key")
	proto.RegisterType((*EncryptedKey)(nil), "proto.EncryptedKey")
	proto.RegisterType((*GetUserPrivateKeysReq)(nil), "proto.GetUserPrivateKeysReq")
	proto.RegisterType((*GetUserPrivateKeysResp)(nil), "proto.GetUserPrivateKeysResp")
	proto.RegisterType((*SetUserKdfMetadataReq)(nil), "proto.SetUserKdfMetadataReq")
	proto.RegisterType((*SetUserKdfMetadataResp)(nil), "proto.SetUserKdfMetadataResp")
}

func init() { proto.RegisterFile("encryption.proto", fileDescriptor_8293a649ce9418c6) }

var fileDescriptor_8293a649ce9418c6 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x66, 0xf3, 0xd3, 0x9f, 0x29, 0x20, 0xb3, 0xa5, 0xc5, 0xe2, 0x00, 0xd6, 0x9e, 0xaa, 0xa8,
	0x4d, 0x85, 0x2b, 0xf1, 0x63, 0x4e, 0xa9, 0x5a, 0x55, 0x95, 0x45, 0x5b, 0xb9, 0x0d, 0x3d, 0x20,
	0x0e, 0xae, 0x3d, 0x09, 0x95, 0x8b, 0xd7, 0xdd, 0xdd, 0x52, 0xac, 0x28, 0x12, 0x12, 0x1c, 0x7a,
	0xce, 0x0b, 0x70, 0xe0, 0x31, 0xb8, 0xf2, 0x1c, 0x3c, 0x0b, 0xf2, 0xda, 0x4e, 0x1c, 0x35, 0x48,
	0x5c, 0x38, 0x79, 0xe7, 0x9b, 0x99, 0x9d, 0xef, 0xfb, 0x76, 0xd7, 0x60, 0x60, 0x1c, 0x88, 0x34,
	0x51, 0xe7, 0x3c, 0x6e, 0x27, 0x82, 0x2b, 0x4e, 0x9b, 0xfa, 0xf3, 0x78, 0x5d, 0x7f, 0x82, 0x8d,
	0x3e, 0xc6, 0x1b, 0xf2, 0xda, 0xef, 0xf7, 0x51, 0x6c, 0x72, 0x5d, 0x27, 0x37, 0xfd, 0x38, 0xe6,
	0xca, 0xd7, 0xeb, 0xbc, 0x89, 0x7d, 0x86, 0xba, 0x8b, 0x29, 0x35, 0xa0, 0x1e, 0x61, 0x6a, 0x12,
	0x8b, 0xac, 0x2d, 0x7a, 0xd9, 0x92, 0x3e, 0x84, 0x66, 0x84, 0xe9, 0xfe, 0x8e, 0x59, 0xd3, 0x58,
	0x1e, 0x50, 0x13, 0xe6, 0xf9, 0x75, 0x8c, 0x62, 0x7f, 0xc7, 0xac, 0x6b, 0xbc, 0x0c, 0xe9, 0x26,
	0x2c, 0xea, 0xe5, 0x49, 0x9a, 0xa0, 0xd9, 0xb0, 0xc8, 0xda, 0x7d, 0xfb, 0x41, 0x3e, 0xa3, 0xdd,
	0x09, 0x02, 0x94, 0x32, 0x4b, 0x78, 0x93, 0x1a, 0xf6, 0x8b, 0xc0, 0xdd, 0xdd, 0x5c, 0x03, 0x86,
	0x19, 0x87, 0x55, 0x98, 0xc3, 0x38, 0x70, 0xc7, 0x34, 0x8a, 0x88, 0x5a, 0xb0, 0x54, 0x68, 0xe5,
	0x62, 0xcc, 0xa7, 0x0a, 0xd1, 0xd6, 0xd8, 0x0d, 0x2e, 0xde, 0xa2, 0x90, 0xe7, 0x3c, 0xd6, 0xf4,
	0x9a, 0xde, 0x2d, 0x7c, 0xa2, 0xab, 0x51, 0xd5, 0xf5, 0x04, 0x20, 0xc2, 0xb4, 0xec, 0x6d, 0xea,
	0xde, 0x0a, 0x52, 0xd5, 0x3d, 0x37, 0xa5, 0x9b, 0xbd, 0x86, 0x95, 0x3d, 0x54, 0x5d, 0x89, 0xe2,
	0x48, 0x9c, 0x7f, 0xf2, 0x15, 0xba, 0x98, 0x4a, 0x0f, 0x2f, 0x1d, 0x36, 0xea, 0x3c, 0x85, 0x47,
	0xad, 0xd9, 0x59, 0xbb, 0x41, 0x6b, 0x83, 0x21, 0xfb, 0x4d, 0x60, 0x75, 0x56, 0x5e, 0x26, 0xf4,
	0x15, 0xdc, 0xc3, 0x8a, 0x3b, 0xd2, 0x24, 0x56, 0x7d, 0x6d, 0xc9, 0x5e, 0x2e, 0x3c, 0xad, 0x3a,
	0xe7, 0x4d, 0x57, 0x3a, 0x37, 0x64, 0xd4, 0xf9, 0x46, 0xc0, 0x6c, 0xfd, 0x65, 0x6f, 0xfb, 0x03,
	0xed, 0x0d, 0xd8, 0x54, 0x0f, 0x73, 0xac, 0x77, 0x1a, 0x72, 0x31, 0x65, 0x8e, 0xc5, 0x7c, 0x19,
	0xf6, 0xd8, 0xba, 0xc5, 0x2a, 0x2e, 0x6b, 0xf8, 0x2c, 0x78, 0x66, 0x6f, 0x65, 0x89, 0x52, 0xbe,
	0x63, 0xb1, 0x04, 0x85, 0xe4, 0x71, 0x06, 0x6a, 0x2f, 0xc7, 0xed, 0xc3, 0xf7, 0x43, 0x36, 0xaa,
	0xc1, 0xca, 0x71, 0x4e, 0xc2, 0x0d, 0x7b, 0x6f, 0x50, 0xf9, 0xa1, 0xaf, 0x7c, 0x0f, 0x2f, 0x33,
	0x47, 0xa3, 0x1c, 0x29, 0x8e, 0xbb, 0x0c, 0x6f, 0x2b, 0xaf, 0xfd, 0xb3, 0xf2, 0x1f, 0x64, 0xd4,
	0xf9, 0x4e, 0x32, 0xd7, 0x67, 0x0e, 0xb5, 0xbf, 0x12, 0xfa, 0x85, 0x0c, 0x58, 0x31, 0x29, 0x63,
	0x1a, 0x4d, 0x0a, 0x2a, 0x7a, 0xff, 0xaf, 0x29, 0x3f, 0x09, 0xac, 0xce, 0xe2, 0x27, 0x93, 0xcc,
	0x15, 0x79, 0xa5, 0x9f, 0x8b, 0x76, 0x65, 0xc1, 0x2b, 0xc3, 0x2c, 0x23, 0x50, 0x2a, 0x5f, 0x28,
	0xfd, 0x02, 0x16, 0xbc, 0x32, 0x9c, 0xdc, 0xe8, 0x7a, 0xe5, 0x46, 0x3b, 0xa7, 0xa3, 0xce, 0x49,
	0x76, 0x05, 0x66, 0x0f, 0xb2, 0x5f, 0xd2, 0xe7, 0x03, 0x56, 0xec, 0xcd, 0x1c, 0x4b, 0x89, 0x2b,
	0x5c, 0xb7, 0x58, 0xb1, 0x25, 0x73, 0xac, 0x9e, 0x7f, 0x21, 0x71, 0x8a, 0x7d, 0xae, 0x72, 0xd8,
	0x7a, 0x01, 0x30, 0x79, 0xd0, 0x74, 0x1e, 0xea, 0x87, 0xde, 0x9e, 0x71, 0x87, 0x2e, 0x40, 0xa3,
	0x7b, 0xbc, 0xeb, 0x19, 0x84, 0x2e, 0x42, 0x73, 0xcf, 0x3b, 0xec, 0x1e, 0x19, 0x35, 0xba, 0x04,
	0xf3, 0xdd, 0x03, 0xf7, 0xe0, 0xf0, 0xf4, 0xc0, 0x58, 0xde, 0xde, 0x02, 0x16, 0xf0, 0x8f, 0x6d,
	0xa9, 0x04, 0x8f, 0xfb, 0xd2, 0xbf, 0x50, 0xc5, 0x32, 0xe4, 0x41, 0x5b, 0x86, 0x51, 0x7e, 0xbc,
	0xdb, 0xb0, 0x3b, 0xfe, 0xaf, 0xdd, 0x10, 0x72, 0x36, 0xa7, 0xd1, 0xad, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf3, 0xca, 0xcf, 0x45, 0xef, 0x04, 0x00, 0x00,
}
